### ISSUE TITLE
After log in the router by browser app login refused (r8000)

### ISSUE THREAD

**Issue by canedje** [gruijter/com.gruijter.netgear#10]
After that I manually logged in to my router R8000 by a browser the app is not able to login anymore.
The pairing is messed up.
Login error and ECONNREFUSED error occurs.
The log only shows ECONNREFUSED messages

After re install the app, pairing not possible.
At the moment I do reset the router as test.

EDIT: After resetting the router pairing is possible again

**Comment by gruijter** [comment]
I also noticed that the router can sometimes get into a state that requires a hard reset of the router. This is not caused by the Homey app, but is a bug in the router firmware.
