### ISSUE TITLE
Netgear App issue test

### ISSUE THREAD

**Issue by Nomar67** [gruijter/com.gruijter.netgear#13]
========== STARTING TEST ==========
Node version: v8.12.0
Netgear package version: 3.3.0
OS: linux 4.14.15-g81f15bab94
trying to auto discover the router...
{Firmware:V1.0.16.98WW,RegionTag:WNDR3700_WW,Region:ww,Model:WNDR3700,InternetConnectionStatus:Up,ParentalControlSupported:1,host:192.168.1.1,port:80}
trying to login...
login method: 1
trying to getInfo...
{ModelName:WNDR3700,Description:Netgear Smart Wizard 3.0, specification 1.6 version,SerialNumber:**********,Firmwareversion:V1.0.16.98,SmartAgentversion:3.0,FirewallVersion:net-wall 2.0,VPNVersion:PPP 2.4.3,OthersoftwareVersion:N/A,Hardwareversion:N/A,Otherhardwareversion:N/A,FirstUseDate:Sunday, 30 Sep 2007 01:10:03}
trying to get supportFeatures...
Unauthorized. Incorrect username/password?
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
{}
trying to get Parental Control Status...
Config started error: Error: Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
Parental Control Enabled: [object Object]
trying to get Qos Status...
Config started error: Error: Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
Qos Enabled: [object Object]
trying to get Qos Bandwidth options...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
{}
trying to get Device Access Control Status...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
Block Device Enabled: [object Object]
trying to get attachedDevices...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
Number of attached devices: undefined, method: 1
First attached device: undefined
trying to get Guest Wifi Status...
2.4G-1 Guest wifi is not available
5.0G-1 Guest wifi is not available, method: 1
5.0G-2 Guest wifi is not available
trying to get the Traffic Meter Enabled Status...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
Traffic Meter Enabled: [object Object]
trying to get the Traffic Meter Options...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
{}
trying to get trafficMeter...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
{}
trying to check newFirmware...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
{}
trying to logout...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
{host:192.168.1.1,port:80,username:admin,password:*****,timeout:10000,sessionId:A7D88AE69687E58D9A00,loggedIn:false,configStarted:false,soapVersion:2,loginMethod:1,getAttachedDevicesMethod:1,guestWifiMethod:{get50_1:1},lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
test finished with 11 errors

**Comment by gruijter** [comment]
The wndr3700 does not work with the Genie app, so it also doesn't work with my Homey app. You can try to ask Netgear for a firmware update that makes it work with Genie.
