### ISSUE TITLE
Unable to delete logs

### ISSUE THREAD

**Issue by edwinvdpol** [gruijter/com.gruijter.netgear#14]
When I push the button "Verwijderen" in the Netgear App log view, the log states the following:

`[err] [MyApp] error deleting logfile:  ENOENT: no such file or directory, unlink '/userdata/netgearLog.json'`

**Comment by gruijter** [comment]
This is not really a bug. It happens if you press the delete button multiple times. The message just says that there is no logfile to delete anymore.

**Comment by edwinvdpol** [comment]
But when I push the button "ververs", there is still a log available?

**Comment by gruijter** [comment]
That shouldnt happen. What Homey version are you on?

**Comment by edwinvdpol** [comment]
Homey Firmware Versie: 1.5.13

**Comment by gruijter** [comment]
Weird. Same version I have, and just tested it ok. What browser are you using?
Is the log still there if you refresh the browser webpage?

 I will check the code to see if I see any possible cause for this.

**Comment by edwinvdpol** [comment]
I use the Homey App for Mac. I will reboot my Homey and see what is does after that.

**Comment by edwinvdpol** [comment]
Addition info: I did remove and re-added the app once. Don't know if that is relevant, just mentioning.

**Comment by edwinvdpol** [comment]
I rebooted my Homey. The log where not still not empty. When I push "ververs", nothing happens (which is ok I presume). When I clicked the "Verwijderen" button, the success modal came up "Logs are deleted.". After pushing the "Ververs" button, the logs were gone (as it should be). Don't know what went wrong exactly, but it is fixed now.

**Comment by gruijter** [comment]
Ok, thx for investigating!
