### ISSUE TITLE
Homey v.2.0 device online

### ISSUE THREAD

**Issue by kjettern** [gruijter/com.gruijter.netgear#15]
Can't get the "device came online" working with homey 2.0. Am I the only one? 
I've set it up like: "device came online" if "logic: mac = xxx" then "mark user as home".

**Comment by gruijter** [comment]
Thx for reporting. I have ordered a Homey to be able to do testing for V2. I will investigate this. But so many apps to test, so little time... It might take some time, stay tuned 🤗

**Comment by edwinvdpol** [comment]
I have the same issue, only using IP addresses to check. You are not the only one. 😊

**Comment by gruijter** [comment]
Maybe in the mean time: did you try if the same happens when using better logic in the AND column, in stead of the built in Homey logic?

https://apps.athom.com/app/net.i-dev.betterlogic

**Comment by gruijter** [comment]
I have made a new version 2.3.0 with some changes for Homey V2. I cannot test the changes myself yet. I do not think it will solve your issues, but you never know :)

**Comment by edwinvdpol** [comment]
We will see hehe! There is no tag support in Better Logic yet, so testing with that app is not possible.

**Comment by edwinvdpol** [comment]
Well, your update seems to have worked I guess. We'll see if it keeps running as it should be, but for now, thank you!

**Comment by gruijter** [comment]
Really? Did not expect that actually 🤔. But hey, Im not complaining 😎 maybe the new Homey fw solved it? Let me know if it happens to fail again.

**Comment by edwinvdpol** [comment]
Not sure haha! I did restart the Netgear app, because an error occurred, and nothin' was registered since a few days. All working as it should AFAIK.

**Comment by gruijter** [comment]
@kjettern is it working ok for you now with app v 2.3.0?

**Comment by kjettern** [comment]
@gruijter Hopefully it is.. I can't test it out right now because my Homey is not up at the moment. It will be up again in a few months and if it's not working then, I will start to complain again 😁

**Comment by gruijter** [comment]
Thats a long long way from Homey 😂

Will close the issue for now. You can reopen if the problem persists.
