### ISSUE TITLE
R6220 fails on checkFirmware

### ISSUE THREAD

**Issue by JohanMarini** [gruijter/com.gruijter.netgear#16]
Hi!
The Netgear app does not present any info. When running the compability test, it seems to fail when trying to get info about new Firmware status. It identifies the router correctly (6220). The router has been rebooted and Netgear app has been reinstalled. It serves as a router.
Can you figure out what is the problem?
I submit the result of the compability test.
Kindest Regards
Johan

**Comment by JohanMarini** [comment]
========== STARTING TEST ==========
Node version: v8.12.0
Netgear package version: 3.3.0
OS: linux 4.14.15-g81f15bab94
trying to auto discover the router...
{host:192.168.8.88,port:5000}
trying to login...
login method: 1
trying to getInfo...
{ModelName:R6220,Description:Netgear Smart Wizard 3.0, specification 0.8 version,SerialNumber:**********,Firmwareversion:V1.1.0.80,SmartAgentversion:3.0,FirewallVersion:ACOS NAT-Netfilter v1.0.0.1 (Linux cone NAT Hot Patch 06/21/2010),VPNVersion:N/A,OthersoftwareVersion:1.0.1,Hardwareversion:R6220,Otherhardwareversion:N/A,FirstUseDate:Wednesday, 23 January 2019 23:53:35,DeviceName:R6220,FirmwareDLmethod:Null,DeviceMode:0}
trying to get supportFeatures...
{OpenDNSParentalControl:1.0,AccessControl:1.0,SpeedTest:2.0,GuestNetworkSchedule:1.0,AttachedDevice:2.0,NameNTGRDevice:1.0,MaxMonthlyTrafficLimitation:4095000000}
trying to get Parental Control Status...
Parental Control Enabled: false
trying to get Qos Status...
Qos Enabled: false
trying to get Qos Bandwidth options...
{newUplinkBandwidth:0,newDownlinkBandwidth:0,enabled:0}
trying to get Device Access Control Status...
Block Device Enabled: false
trying to get attachedDevices...
Number of attached devices: 13, method: 2
First attached device: {\IP\:\192.168.8.89\,\Name\:\MARINICLOUD\,\NameUserSet\:false,\MAC\:\00:90:A9:F3:67:19\,\ConnectionType\:\wired\,\Linkspeed\:null,\SignalStrength\:100,\AllowOrBlock\:\Allow\,\Schedule\:\false\,\DeviceType\:999,\DeviceTypeUserSet\:false,\DeviceTypeName\:\\,\DeviceModelUserSet\:false,\Upload\:null,\Download\:null,\QosPriority\:null,\Grouping\:0,\SchedulePeriod\:0,\ConnAPMAC\:\\}
trying to get Guest Wifi Status...
2.4G-1 Guest wifi enabled: true
5.0G-1 Guest wifi is not available, method: 1
5.0G-2 Guest wifi is not available
trying to get the Traffic Meter Enabled Status...
Traffic Meter Enabled: true
trying to get the Traffic Meter Options...
{newControlOption:No Limit,newNewMonthlyLimit:0,restartHour:0,restartMinute:0,restartDay:1}
trying to get trafficMeter...
{newTodayUpload:489.71,newTodayDownload:7614.94,newMonthUpload:11645.26,newMonthDownload:350504.12}
trying to check newFirmware...
socket hang up
{lastResponse:{message:socket hang up,code:ECONNRESET}}
{}
trying to logout...
{host:192.168.8.88,port:5000,username:admin,password:*****,timeout:10000,sessionId:A7D88AE69687E58D9A00,loggedIn:false,configStarted:false,soapVersion:2,loginMethod:1,getAttachedDevicesMethod:2,guestWifiMethod:{get50_1:1},lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?><SOAP-ENV:Envelope xmlns:SOAPSDK1=\http://www.w3.org/2001/XMLSchema\ xmlns:SOAPSDK2=\http://www.w3.org/2001/XMLSchema-instance\ xmlns:SOAPSDK3=\http://schemas.xmlsoap.org/soap/encoding/\ xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\>\n  <SOAP-ENV:Body>\n    <m:SOAPLogoutResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceConfig:1\></m:SOAPLogoutResponse>\n    <ResponseCode>000</ResponseCode>\n  </SOAP-ENV:Body>\n</SOAP-ENV:Envelope>\n}
test finished with 1 errors

**Comment by gruijter** [comment]
Thx for reporting. What happens if you check for a firmware upgrade from the netgear genie app? Does that work ok?

**Comment by JohanMarini** [comment]
Hi!
Yes, that seems to work - including screen shoots on confirmation response and router+genie version (latest versions).



Kindest Regards
Johan

**Comment by gruijter** [comment]
Mmh. Maybe for your router type the command for firmware check is different. I dont know how tech savvy you are, but would you be capable to capture the http traffic between the genie app and your router?

**Comment by gruijter** [comment]
I made a new version 2.3.0: Fixes timeout / socket hangup for certain router types. Homey V2 icons and Insights.

This should fix the problem you are experiencing. Can you install and test from Github? Otherwise you have to wait for the app store release in a number of days.

**Comment by JohanMarini** [comment]
Thanks for very quick action!
I was planning to try out Sharkwire this weekend, to see if I could learn and practice how to capture some http traffic :-)
Instead, I will have a go for Node.js, yes?
Looking forward to that!
Kindest Regards

**Comment by gruijter** [comment]
V 2.3.0 was just released in the appstore. Could you install that and try again? If that works then no need to do hardcore hacking 🤘

**Comment by JohanMarini** [comment]
Hi!
Status info is now presented, but indicates there is no internet...
Seems that the app gets list of connected devices though - I created a flow using ”A device is online” and was presented a picklist of mac adresses.
I will check the upload and download values against Netgear Genie app later.
Indications that devices go online and offline seems to work fine.
The compability test shows ”14 errors” though - I’m not sure why. I added the result below. For me, the most important works anyway - to be able to monitor devices going online and offline. Don’t hesitate contacting me if you want more info though!

Kindest regards

========== STARTING TEST ==========
Node version: v8.12.0
Netgear package version: 3.3.2
OS: linux 4.14.15-g81f15bab94
trying to auto discover the router...
{host:192.168.8.88,port:5000}
trying to login...
login method: 2
trying to getInfo...
{ModelName:R6220,Description:Netgear Smart Wizard 3.0, specification 0.8 version,SerialNumber:**********,Firmwareversion:V1.1.0.80,SmartAgentversion:3.0,FirewallVersion:ACOS NAT-Netfilter v1.0.0.1 (Linux cone NAT Hot Patch 06/21/2010),VPNVersion:N/A,OthersoftwareVersion:1.0.1,Hardwareversion:R6220,Otherhardwareversion:N/A,FirstUseDate:Saturday, 26 January 2019 13:44:49,DeviceName:R6220,FirmwareDLmethod:Null,DeviceMode:0}
trying to get supportFeatures...
{OpenDNSParentalControl:1.0,AccessControl:1.0,SpeedTest:2.0,GuestNetworkSchedule:1.0,AttachedDevice:2.0,NameNTGRDevice:1.0,MaxMonthlyTrafficLimitation:4095000000}
trying to get Parental Control Status...
Parental Control Enabled: false
trying to get Qos Status...
Qos Enabled: false
trying to get Qos Bandwidth options...
{newUplinkBandwidth:0,newDownlinkBandwidth:0,enabled:0}
trying to get Device Access Control Status...
Block Device Enabled: false
trying to get attachedDevices...
Number of attached devices: 17, method: 1
First attached device: {\IP\:\192.168.8.32\,\Name\:\UNKNOWN\,\MAC\:\D0:50:99:92:DE:8D\,\ConnectionType\:\wired\,\Linkspeed\:0,\SignalStrength\:100,\AllowOrBlock\:\Allow\}
trying to get Guest Wifi Status...
2.4G-1 Guest wifi enabled: true
5.0G-1 Guest wifi is not available, method: 1
5.0G-2 Guest wifi is not available
trying to get the Traffic Meter Enabled Status...
Traffic Meter Enabled: true
trying to get the Traffic Meter Options...
{newControlOption:No Limit,newNewMonthlyLimit:0,restartHour:0,restartMinute:0,restartDay:1}
trying to get trafficMeter...
{newTodayUpload:831.01,newTodayDownload:37772.57,newMonthUpload:13449.83,newMonthDownload:409767.07}
trying to check newFirmware...
{currentVersion:V1.1.0.80,newVersion: ,releaseNote:[New features] Supports the Funjsq service for China.[Bug Fixes] Fixes issue where the device name cannot be edited in the GUI.[Bug Fixes] Fixes the issue where the serial number inputting history can be seen on the Router Password Reset page.[Bug Fixes] Fixes the issue where the WiFi password cannot be saved if it contains 64 characters.[Bug Fixes] Fixes the issue where the router can't check for new firmware versions.[Bug Fixes] Fixes the issue where the router can't check for new firmware if the WAN mod}
trying to logout...
{host:192.168.8.88,port:5000,username:admin,password:*****,timeout:20000,sessionId:A7D88AE69687E58D9A00,cookie:[Token=36d82e865c85d7a0],loggedIn:false,configStarted:false,soapVersion:2,loginMethod:2,getAttachedDevicesMethod:1,guestWifiMethod:{get50_1:1},lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?><SOAP-ENV:Envelope xmlns:SOAPSDK1=\http://www.w3.org/2001/XMLSchema\ xmlns:SOAPSDK2=\http://www.w3.org/2001/XMLSchema-instance\ xmlns:SOAPSDK3=\http://schemas.xmlsoap.org/soap/encoding/\ xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\>\n  <SOAP-ENV:Body>\n    <m:SOAPLogoutResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceConfig:1\></m:SOAPLogoutResponse>\n    <ResponseCode>000</ResponseCode>\n  </SOAP-ENV:Body>\n</SOAP-ENV:Envelope>\n}
test finished with 14 errors

**Comment by gruijter** [comment]
Are you using the netgear in router mode or access point mode?
In device settings you can change the internet check to Homey. That should fix your incorrect internet status report. Weird that it sais it finishes with 14 errors, since I see 0 errors. I will check my test routine.

Thx 4 the feedback!

**Comment by JohanMarini** [comment]
Using my R6220 in Router mode.
Also the Upload and Download values seems to be correct.
Thanks a lot for quick responces and help!

**Comment by gruijter** [comment]
Thx 4 the donation @JohanMarini. Much appreciated!
