### ISSUE TITLE
Help with R6220 plz

### ISSUE THREAD

**Issue by zytric** [gruijter/com.gruijter.netgear#17]
Cant install router device.

**Comment by zytric** [comment]
========== STARTING TEST ==========
Node version: v8.12.0
Netgear package version: 3.3.0
OS: linux 4.14.15-g81f15bab94
trying to auto discover the router...
{host:192.168.1.1,port:5000}
trying to login...
login method: 1
trying to getInfo...
{Description:Netgear Smart Wizard 3.0, specification 0.8 version,SerialNumber:**********,Firmwareversion:V1.1.0.80,SmartAgentversion:3.0,FirewallVersion:ACOS NAT-Netfilter v1.0.0.1 (Linux cone NAT Hot Patch 06/21/2010),VPNVersion:N/A,OthersoftwareVersion:1.0.1,Otherhardwareversion:N/A,FirstUseDate:Friday, 25 January 2019 17:20:17,DeviceName:R6220,FirmwareDLmethod:Null,DeviceMode:0}
trying to get supportFeatures...
{OpenDNSParentalControl:1.0,AccessControl:1.0,SpeedTest:2.0,GuestNetworkSchedule:1.0,AttachedDevice:2.0,NameNTGRDevice:1.0,MaxMonthlyTrafficLimitation:4095000000}
trying to get Parental Control Status...
Parental Control Enabled: false
trying to get Qos Status...
Qos Enabled: false
trying to get Qos Bandwidth options...
{newUplinkBandwidth:0,newDownlinkBandwidth:0,enabled:0}
trying to get Device Access Control Status...
Block Device Enabled: false
trying to get attachedDevices...
Number of attached devices: 7, method: 1
First attached device: {\IP\:\192.168.1.2\,\Name\:\ANDROID-C6D8DE9C79E37C82\,\MAC\:\84:DB:AC:3A:AE:4B\,\ConnectionType\:\wireless\,\Linkspeed\:65,\SignalStrength\:78,\AllowOrBlock\:\Allow\}
trying to get Guest Wifi Status...
2.4G-1 Guest wifi enabled: false
5.0G-1 Guest wifi is not available, method: 1
5.0G-2 Guest wifi is not available
trying to get the Traffic Meter Enabled Status...
Traffic Meter Enabled: false
trying to get the Traffic Meter Options...
{newControlOption:No Limit,newNewMonthlyLimit:0,restartHour:0,restartMinute:0,restartDay:1}
trying to get trafficMeter...
{newTodayUpload:0,newTodayDownload:0,newMonthUpload:0,newMonthDownload:0}
trying to check newFirmware...
socket hang up
{lastResponse:{message:socket hang up,code:ECONNRESET}}
{}
trying to logout...
{host:192.168.1.1,port:5000,username:admin,password:*****,timeout:10000,sessionId:A7D88AE69687E58D9A00,loggedIn:false,configStarted:false,soapVersion:2,loginMethod:1,getAttachedDevicesMethod:1,guestWifiMethod:{get50_1:1},lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?><SOAP-ENV:Envelope xmlns:SOAPSDK1=\http://www.w3.org/2001/XMLSchema\ xmlns:SOAPSDK2=\http://www.w3.org/2001/XMLSchema-instance\ xmlns:SOAPSDK3=\http://schemas.xmlsoap.org/soap/encoding/\ xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\>\n  <SOAP-ENV:Body>\n    <m:SOAPLogoutResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceConfig:1\></m:SOAPLogoutResponse>\n    <ResponseCode>000</ResponseCode>\n  </SOAP-ENV:Body>\n</SOAP-ENV:Envelope>\n}
test finished with 6 errors

**Comment by zytric** [comment]
When I click install I get message:
Success!
Model: undefined
SN: 3XSXXXXXXXXXXX

Then i get:
Error: SQLLITE_CONSTRAINT: NOT NULL constraint failed: Device.name


So I guess the name couldnt be found from my device.

**Comment by gruijter** [comment]
New app version was just released. Could you install that and try again?

**Comment by zytric** [comment]
Same error. Still looks like I got Device name as null

**Comment by gruijter** [comment]
And could you try to give the netgear a cold restart? In #16 I see that another 6220 with the same firmware does provide ModelName. Weird...

**Comment by zytric** [comment]
Restarted modem, router, homey, homey app. Reinstalled netgear app. Same error.  :(

**Comment by zytric** [comment]
Diagnostic report:
0a85ef00-148e-46bc-a4a3-9e2334e06ba3

**Comment by zytric** [comment]
Both "model" and "Device.name" seems to be undefined.

**Comment by gruijter** [comment]
Still weird that your 6220 provides different info then #16. But I can fix this in the app. Will include that in the next app release.

**Comment by zytric** [comment]
Wihu. Looking forward for it! Thanks for the quick response.

**Comment by gruijter** [comment]
I made v2.3.1 for you. You can sideload it if you follow these instructions: https://community.athom.com/t/how-to-cli-install-method/198

Otherwise you have to wait for the appstore release :)

**Comment by zytric** [comment]
Thank you very much. Worked!
