### ISSUE TITLE
Homey loses connection with Netgear R7000 router

### ISSUE THREAD

**Issue by wanhoopnl** [gruijter/com.gruijter.netgear#18]
Hi Robin,

Since the update of the Homey Netgear app I am encountering connection lost issues with my Netgear R7000 router. When I restart the app the connection is available, but after a short while the connection is lost again. I tried to reset both Homey and the Router, but this did not help.

Thanks in advance for your help,
Nick

Results compatibiliteitstest (192.168.14.1, SOAP 5000)

========== STARTING TEST ==========
Node version: v8.12.0
Netgear package version: 3.3.4
OS: linux 4.14.15-g81f15bab94
trying to auto discover the router...
{Firmware:V1.0.9.12_1.2.23,RegionTag:R7000_WW,Region:ww,Model:R7000,InternetConnectionStatus:Up,ParentalControlSupported:1,CircleEnabled:0,OpenDNSEnabled:0,SOAPVersion:3.2,ReadyShareSupportedLevel:29,XCloudSupported:1,LoginMethod:1.0,DeviceMode:0,host:192.168.14.1}
trying to login...
{message:Failed to login}
{host:192.168.14.1,username:admin,password:*****,timeout:20000,sessionId:A7D88AE69687E58D9A00,loggedIn:false,configStarted:false,soapVersion:3,loginMethod:2,guestWifiMethod:{},lastResponse:401}

**Comment by gruijter** [comment]
Can you try changing the password in your router ( and matching in Homey off course )?

**Comment by wanhoopnl** [comment]
Changed the password on both Netgear and in Homey app, but still the login fails. Also tried to re-install the app. When I try to add the Netgear device, there is no message at all when I select 'Test de instellingen'.

**Comment by gruijter** [comment]
I still have a R7000 lying around. I will test myself this weekend.

**Comment by seegersnl** [comment]
I have the same problem with my r7000, worked like a charm since the last update. I updated the r7000 to the latest firmware and changed the password in homey and the router but no succes. Update: i switched of the traffic meter in the router en now it seems fine again.

**Comment by gruijter** [comment]
I have hooked up my R7000, did a firmware update to V1.0.9.64. But all works well for me on Homey V1 and Homey V2. I cannot reproduce the connection issues. Did you do a complete power down of both Homey and the router after the firmware update? (I mean really pull the plug, not a soft restart).

**Comment by gruijter** [comment]
@wanhoopnl : I see by the way that you are not using the latest firmware for R7000. Please update and try again.

**Comment by wanhoopnl** [comment]
Hi Robin. I have updated the firmware and the router now nicely connects and is able to login without issues now. I also did a power down of the modem and the router, also afterwards it all worked fine. Thanks for the quick reply and help! I really like this app!
