### ISSUE TITLE
R6220 no data

### ISSUE THREAD

**Issue by maikrovers** [gruijter/com.gruijter.netgear#19]
Everything seams to be okay, but I do not get any data.

**Comment by gruijter** [comment]
Can you post the compatibility test result here ?

**Comment by maikrovers** [comment]
========== STARTING TEST ==========
Node version: v8.12.0
Netgear package version: 3.3.4
OS: linux 4.14.15-g81f15bab94
trying to auto discover the router...
{host:192.168.10.1,port:5000}
trying to login...
login method: 1
trying to getInfo...
{Description:Netgear Smart Wizard 3.0, specification 0.8 version,SerialNumber:**********,Firmwareversion:V1.1.0.86,SmartAgentversion:3.0,FirewallVersion:ACOS NAT-Netfilter v1.0.0.1 (Linux cone NAT Hot Patch 06/21/2010),VPNVersion:N/A,OthersoftwareVersion:1.0.1,Otherhardwareversion:N/A,FirstUseDate:Tuesday, 05 February 2019 17:24:07,DeviceName:R6220,FirmwareDLmethod:Null,DeviceMode:0}
trying to get supportFeatures...
{OpenDNSParentalControl:1.0,AccessControl:1.0,SpeedTest:2.0,GuestNetworkSchedule:1.0,AttachedDevice:2.0,NameNTGRDevice:1.0,MaxMonthlyTrafficLimitation:4095000000}
trying to get Parental Control Status...
Parental Control Enabled: false
trying to get Qos Status...
Qos Enabled: false
trying to get Qos Bandwidth options...
{newUplinkBandwidth:0,newDownlinkBandwidth:0,enabled:1}
trying to get Device Access Control Status...
Block Device Enabled: true
trying to get attachedDevices...
Number of attached devices: 19, method: 1
First attached device: {\IP\:\192.168.10.50\,\Name\:\09AA01AC44160XVD\,\MAC\:\18:B4:30:87:C9:62\,\ConnectionType\:\wireless\,\Linkspeed\:65,\SignalStrength\:94,\AllowOrBlock\:\Allow\}
trying to get Guest Wifi Status...
2.4G-1 Guest wifi enabled: false
5.0G-1 Guest wifi is not available, method: 1
5.0G-2 Guest wifi is not available
trying to get the Traffic Meter Enabled Status...
Traffic Meter Enabled: true
trying to get the Traffic Meter Options...
{newControlOption:No Limit,newNewMonthlyLimit:0,restartHour:0,restartMinute:0,restartDay:1}
trying to get trafficMeter...
{newTodayUpload:215.1,newTodayDownload:1246.46,newMonthUpload:215.1,newMonthDownload:1246.46}
trying to check newFirmware...
socket hang up
{lastResponse:{message:socket hang up,code:ECONNRESET}}
{}
trying to logout...
{host:192.168.10.1,port:5000,username:admin,password:*****,timeout:20000,sessionId:A7D88AE69687E58D9A00,loggedIn:false,configStarted:false,soapVersion:2,loginMethod:1,getAttachedDevicesMethod:1,guestWifiMethod:{get50_1:1},lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?><SOAP-ENV:Envelope xmlns:SOAPSDK1=\http://www.w3.org/2001/XMLSchema\ xmlns:SOAPSDK2=\http://www.w3.org/2001/XMLSchema-instance\ xmlns:SOAPSDK3=\http://schemas.xmlsoap.org/soap/encoding/\ xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\>\n  <SOAP-ENV:Body>\n    <m:SOAPLogoutResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceConfig:1\></m:SOAPLogoutResponse>\n    <ResponseCode>000</ResponseCode>\n  </SOAP-ENV:Body>\n</SOAP-ENV:Envelope>\n}
test finished with 6 errors

**Comment by gruijter** [comment]
Ok, seems to fail on the firmware update check. Could you time how long this takes when you run the firmware check from the genie app? I have the timeout set to 20s. Still, all other functions seem to work properly. So you should be getting some data coming into Homey after some minutes.

**Comment by maikrovers** [comment]
From the genie app it takes about 25sec, so that could be a problem. I do not get any data in homey....

**Comment by gruijter** [comment]
Ok thx for testing. I will Investigate this.

**Comment by maikrovers** [comment]
Perfect thnx.

**Comment by maikrovers** [comment]
I changed my NetGear settings to use another DNS server (instead of 4.4.4.4 from google). After this I get data into my homey.
Stiil strange: Internet connection: No, download speed: 0.02Mbit/s, upload speed: 0.19 Mbit/s....
I think my connection is very slow :), even though I download 500MB within half a minute.... ;)

**Comment by gruijter** [comment]
v2.3.3  Netgear 3.3.5. Fixes timeout / socket hangup. You can sideload from here, or wait for the Athom to approve the appstore release.

Let me know if it works for you :)

Edit: it is already released now in the appstore 🤘

**Comment by maikrovers** [comment]
Yes! Upgraded to the latest version.
Things look better now, but looks like firmware version cannot be found:
2019-02-06 19:37:44 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error:  Cannot read property 'newVersion' of undefined

**Comment by gruijter** [comment]
Can you do the compatibility test again and post it here?

**Comment by maikrovers** [comment]
====== STARTING TEST ==========
Node version: v8.12.0
Netgear package version: 3.3.5
OS: linux 4.14.15-g81f15bab94
t = 0
trying to auto discover the router...
{host:192.168.10.1,port:5000}
t = 0.159
trying to login...
login method: 1
t = 0.259
trying to getInfo...
{Description:Netgear Smart Wizard 3.0, specification 0.8 version,SerialNumber:**********,Firmwareversion:V1.1.0.86,SmartAgentversion:3.0,FirewallVersion:ACOS NAT-Netfilter v1.0.0.1 (Linux cone NAT Hot Patch 06/21/2010),VPNVersion:N/A,OthersoftwareVersion:1.0.1,Otherhardwareversion:N/A,FirstUseDate:Wednesday, 06 February 2019 18:38:32,DeviceName:R6220,FirmwareDLmethod:Null,DeviceMode:0}
t = 0.347
trying to get supportFeatures...
{OpenDNSParentalControl:1.0,AccessControl:1.0,SpeedTest:2.0,GuestNetworkSchedule:1.0,AttachedDevice:2.0,NameNTGRDevice:1.0,MaxMonthlyTrafficLimitation:4095000000}
t = 0.427
trying to get Parental Control Status...
Parental Control Enabled: false
t = 0.856
trying to get Qos Status...
Qos Enabled: false
t = 1.316
trying to get Qos Bandwidth options...
{newUplinkBandwidth:0,newDownlinkBandwidth:0,enabled:1}
t = 1.471
trying to get Device Access Control Status...
Block Device Enabled: true
t = 1.544
trying to get attachedDevices...
Number of attached devices: 14, method: 1
First attached device: {\IP\:\192.168.10.50\,\Name\:\09AA01AC44160XVD\,\MAC\:\18:B4:30:87:C9:62\,\ConnectionType\:\wireless\,\Linkspeed\:65,\SignalStrength\:91,\AllowOrBlock\:\Allow\}
t = 6.848
trying to get Guest Wifi Status...
2.4G-1 Guest wifi enabled: false
5.0G-1 Guest wifi is not available, method: 1
5.0G-2 Guest wifi is not available
t = 7.14
trying to get the Traffic Meter Enabled Status...
Traffic Meter Enabled: true
t = 7.222
trying to get the Traffic Meter Options...
{newControlOption:No Limit,newNewMonthlyLimit:0,restartHour:0,restartMinute:0,restartDay:1}
t = 7.299
trying to get trafficMeter...
{newTodayUpload:120.79,newTodayDownload:941.35,newMonthUpload:1062.04,newMonthDownload:3496.68}
t = 7.4
trying to check newFirmware...
socket hang up
{lastResponse:{message:socket hang up,code:ECONNRESET}}
{}
t = 17.696
trying to logout...
{host:192.168.10.1,port:5000,username:admin,password:*****,timeout:30000,sessionId:A7D88AE69687E58D9A00,loggedIn:false,configStarted:false,soapVersion:2,loginMethod:1,getAttachedDevicesMethod:1,guestWifiMethod:{get50_1:1},lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?><SOAP-ENV:Envelope xmlns:SOAPSDK1=\http://www.w3.org/2001/XMLSchema\ xmlns:SOAPSDK2=\http://www.w3.org/2001/XMLSchema-instance\ xmlns:SOAPSDK3=\http://schemas.xmlsoap.org/soap/encoding/\ xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\>\n  <SOAP-ENV:Body>\n    <m:SOAPLogoutResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceConfig:1\></m:SOAPLogoutResponse>\n    <ResponseCode>000</ResponseCode>\n  </SOAP-ENV:Body>\n</SOAP-ENV:Envelope>\n}
t = 17.754
test finished with 1 errors

**Comment by gruijter** [comment]
Ok thx. Somehow the timeout is still 10s. I need to figure out why. This error should occur only once every hour. Is that correct? And is all other stuff working correctly now?

**Comment by maikrovers** [comment]
It occurs every hour indeed.
All other things are working fine now!
