### ISSUE TITLE
Test of my ORBI RBR020, 2 issues.

### ISSUE THREAD

**Issue by jeesnl** [gruijter/com.gruijter.netgear#21]
========== STARTING TEST ==========
Node version: v8.12.0
Netgear package version: 3.3.5
OS: linux 4.14.15-g81f15bab94
t = 0
trying to auto discover the router...
{Firmware:V2.2.1.210WW,RegionTag:RBR20_WW,Region:ww,Model:RBR20,InternetConnectionStatus:Up,ParentalControlSupported:1,OpenDNSEnabled:0,CircleEnabled:0,DeviceMode:0,SOAPVersion:3.46,ReadyShareSupportedLevel:0,XCloudSupported:1,isBlankState:0,LoginMethod:2.0,host:192.168.1.1,port:80}
t = 0.352
trying to login...
login method: 1
t = 0.506
trying to getInfo...
{ModelName:RBR20,Description:Netgear Smart Wizard 3.0, specification 1.6 version,SerialNumber:**********,SignalStrength:100,Firmwareversion:V2.2.1.210,SmartAgentversion:3.0,FirewallVersion:net-wall 2.0,OthersoftwareVersion:N/A,Hardwareversion:N/A,Otherhardwareversion:N/A,FirstUseDate:Sunday, 30 Sep 2007 01:10:03,DeviceName:ORBI Router Meterkast,DeviceNameUserSet:true,FirmwareDLmethod:HTTPS,FirmwareLastUpdate:2019_1.23_12:30:22,FirmwareLastChecked:2019_2.8_13:17:14,DeviceMode:0,DeviceModeCapability:0;1}
t = 0.678
trying to get supportFeatures...
{OpenDNSParentalControl:1.0,CircleParentalControl:1.0,OrbiTribandSupport:1.0,AccessControl:3.0,SpeedTest:2.0,GuestNetworkSchedule:1.0,TCAcceptance:1.0,SmartConnect:1.0,LightingLED:1.0,TimeZone:2.0,SatelliteInfo:2.0,NameNTGRDevice:1.0,AttachedDevice:2.0,MaxMonthlyTrafficLimitation:4293918720,SystemWps:1.0,SystemDfs:1.0,AvsSupport:1.0}
t = 0.815
trying to get Parental Control Status...
Parental Control Enabled: false
t = 1.401
trying to get Qos Status...
Invalid response code from router: 404
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetQoSEnableStatusResponse xmlns:m=\urn:NETGEAR-ROUTER:service:AdvancedQoS:1\></m:GetQoSEnableStatusResponse>\r\n<ResponseCode>404</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
Qos Enabled: [object Object]
t = 1.66
trying to get Qos Bandwidth options...
Invalid response code from router: 404
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetBandwidthControlOptionsResponse xmlns:m=\urn:NETGEAR-ROUTER:service:AdvancedQoS:1\></m:GetBandwidthControlOptionsResponse>\r\n<ResponseCode>404</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
{}
t = 1.79
trying to get Device Access Control Status...
Block Device Enabled: true
t = 1.912
trying to get attachedDevices...
Number of attached devices: 21, method: 2
First attached device: {\IP\:\192.168.1.6\,\Name\:\SOUNDTOUCH-300\,\NameUserSet\:true,\MAC\:\3C:A3:08:04:13:F6\,\ConnectionType\:\5GHz\,\Linkspeed\:150,\SignalStrength\:70,\AllowOrBlock\:\Allow\,\Schedule\:\false\,\DeviceType\:23,\DeviceTypeUserSet\:true,\DeviceModel\:\Unknown\,\DeviceModelUserSet\:false,\Upload\:0,\Download\:0,\QosPriority\:4,\Grouping\:0,\SchedulePeriod\:0,\ConnAPMAC\:\78:D2:94:3A:6B:19\}
t = 7.592
trying to get Guest Wifi Status...
2.4G-1 Guest wifi enabled: false
5.0G-1 Guest wifi enabled: false, method: 1
5.0G-2 Guest wifi is not available
t = 8.138
trying to get the Traffic Meter Enabled Status...
Traffic Meter Enabled: true
t = 8.259
trying to get the Traffic Meter Options...
{newControlOption:No Limit,newNewMonthlyLimit:0,restartHour:0,restartMinute:0,restartDay:1}
t = 8.398
trying to get trafficMeter...
{newTodayUpload:932.68,newTodayDownload:3805,newMonthUpload:20163,newMonthDownload:51644}
t = 8.549
trying to check newFirmware...
{currentVersion:V2.2.1.210,newVersion:,releaseNote:}
t = 13.215
trying to logout...
{host:192.168.1.1,port:80,username:admin,password:*****,timeout:30000,sessionId:A7D88AE69687E58D9A00,loggedIn:false,configStarted:true,soapVersion:3,loginMethod:1,getAttachedDevicesMethod:2,guestWifiMethod:{get50_1:1},lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:SOAPLogoutResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceConfig:1\></m:SOAPLogoutResponse>\r\n<ResponseCode>000</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
t = 13.346
test finished with 2 errors

**Comment by gruijter** [comment]
Can you check if your router supports QoS at all? If so, you should find something called 'dynamic QoS' in the genie app and in the router settings page. If the orbi does not have QoS the 2 errors from the test are correct.

**Comment by jeesnl** [comment]
My router has a QoS page, that looks lijke this:


------ Origineel bericht ------
Van: "gruijter" <notifications@github.com>
Aan: "gruijter/com.gruijter.netgear" 
<com.gruijter.netgear@noreply.github.com>
CC: "JeeS" <jan.slag@gmail.com>; "Author" <author@noreply.github.com>
Verzonden: 8-2-2019 16:52:07
Onderwerp: Re: [gruijter/com.gruijter.netgear] Test of my ORBI RBR020, 2 
issues. (#21)

**Comment by jeesnl** [comment]
Here the picture

**Comment by jeesnl** [comment]
The QoS setup page only shows the option to run the internet speed test.
![capture](https://user-images.githubusercontent.com/39216786/52491127-a8fa3680-2bc6-11e9-894d-065c3bbf735f.JPG)

**Comment by gruijter** [comment]
When I google a bit I find reports that Orbi only does a speedtest, but there are no real QoS settings.

https://community.netgear.com/t5/Orbi/Orbi-QoS-does-not-work-What-s-up/m-p/1513408

 I would suggest you take this up with Netgear.

**Comment by jeesnl** [comment]
Ok, thanks for the effort.
