### ISSUE TITLE
Transfer speed

### ISSUE THREAD

**Issue by HenricAsk** [gruijter/com.gruijter.netgear#22]
Hi again.

Is it possible to implement that the app can get current Up/download speed of a specific device.
Example: "My_Phone" currently uses 10Mbit bandwidth down and 1Mbit up

Thanks for your work!

**Comment by gruijter** [comment]
Hi Henric,

I actually looked at that already some time ago. But I wasnt able to get reliable data on a device level. I just checked again, and the device up/down speed that I get reported isnt accurate enough to make use of it.

**Comment by HenricAsk** [comment]
Ok! Thanks for checking and quick response :)
