### ISSUE TITLE
Can't install 2.3.5, not compatible with Homey

### ISSUE THREAD

**Issue by tiimbo82** [gruijter/com.gruijter.netgear#23]
athom-cli gives error - please fix the validation issues

**Comment by gruijter** [comment]
I Just installed it from the appstore without issues. What error do you get?

**Comment by tiimbo82** [comment]
Might be issue with English language?

**Comment by gruijter** [comment]
What error do you get? What version Homey? What version CLI? Did you try installing from the app store?

**Comment by tiimbo82** [comment]
Through app store, "this app is not compatible", Homey ver 2.0.4
[image: netgear.png]

**Comment by gruijter** [comment]
Mmh, looks like a Homey fw problem. Try updating to fw 2.0.5

**Comment by tiimbo82** [comment]
I downloaded you're previous version and loaded through CLI, all happy,
thankyou

**Comment by edje724** [comment]
Hi Gruijter, have the same problem with compatibility. How can I download a older version and instal this on Homey?

**Comment by gruijter** [comment]
@edje724 
How did your netgear app v2.3.4 get to be uninstalled? Or are you a new user?

Anyhow:
* easiest would be to update your Homey to 2.0.5 (you have to set your Homey to experimental updates for this)
* Or wait for Homey v2.0.5 to be released to stable
* Or install the netgear app v2.3.4 via cli from here: https://github.com/gruijter/com.gruijter.netgear/tree/ce7bbe111439515e1fa5f6f50082a81ba93e9d78

**Comment by edje724** [comment]
I’m a new user. Thanks for your options, I will try to install the v2.3.4 netgear app first. Let you know...

**Comment by gruijter** [comment]
Homey fw 2.0.5 is now released as stable. Problem with installing from appstore is solved.
