### ISSUE TITLE
Homey can’t connect to R7000

### ISSUE THREAD

**Issue by RexArne** [gruijter/com.gruijter.netgear#24]
After months of properly working, homey seems to have connection problems with my Netgear R7000. 

I already restarted the app and router, but that doesn’t help. 
See (part of) log message below

2019-04-02 13:46:58 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in 
2019-04-02 13:46:58 [log] [ManagerDrivers] [netgear] [0] Firmware=V1.0.9.64_10.2.64 RegionTag=R7000_WW Region=ww Model=R7000 InternetConnectionStatus=Up ParentalControlSupported=1 CircleEnabled=0 OpenDNSEnabled=0 SOAPVersion=3.21 LoginMethod=2.0 ReadyShareSupportedLevel=29 XCloudSupported=1 DeviceMode=0 
2019-04-02 13:46:58 [log] [ManagerDrivers] [netgear] [0] last repsonse from router: 
2019-04-02 13:46:58 [log] [ManagerDrivers] [netgear] [0] error getting new Firmware info 
2019-04-02 13:46:58 [log] [ManagerDrivers] [netgear] [0] error getting router info 
2019-04-02 13:46:58 [err] [ManagerDrivers] [netgear] [0] Login error: Failed to login 
2019-04-02 13:46:38 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Not logged in 
2019-04-02 13:46:38 [log] [ManagerDrivers] [netgear] [0] Firmware=V1.0.9.64_10.2.64 RegionTag=R7000_WW Region=ww Model=R7000 InternetConnectionStatus=Up ParentalControlSupported=1 CircleEnabled=0 OpenDNSEnabled=0 SOAPVersion=3.21 LoginMethod=2.0

**Comment by gruijter** [comment]
Did you already try a cold restart of the router (power off and on)?

**Comment by RexArne** [comment]
Yes, also tried that several times. No result unfortunately.

**Comment by gruijter** [comment]
I can try with my own r7000, but not on short notice. In the mean time: did you also try changing the password?
And you can also try to block/unblock Homey itself via the genie app.

**Comment by gruijter** [comment]
I just tried connecting to my own R7000, and that went without problem. I have firmware V1.0.9.64_10.2.64
Did you try the solutions I provided in my previous post?

**Comment by RexArne** [comment]
I have the same firmware running on my router. 

Changing password had no result. 
I don’t know if it is related, but I also could not log on to the router via Netgear Genie app anymore. In browser there is no problem. After restarting the router, i could log in again with genie app. And also could connect Homey. However after a day or so, connection was gone again. - and also could not log in with genie app -

I am curious what your experiences are after a day or two and whether you think issues with homey and genie app are related.

**Comment by gruijter** [comment]
I will leave my R700 connected to Homey for a few days. See what happens.

Besides the login failure, can you see any other errors in the app log? Maybe you have bad wifi to Homey? Did you change the poll interval to a shorter time maybe? Try setting the poll interval to a longer time, e.g. 2 or 3 minutes to see if that helps.

**Comment by gruijter** [comment]
Just to let you know that my r7000 now also stopped responding after 2 days. I will investigate this further.

**Comment by RexArne** [comment]
Thx for letting me know. Do you also have the issue with logging in to R7000 from Genie App?

As you requested I have changed the polling to 2 minutes yesterday. After a day it is still responding. I assume that polling once every 2 minutes mean that it can take two minutes before homey knows a device came online?

**Comment by gruijter** [comment]
My r7000 was completely blocked. Wifi was on but not working, and I couldn't even login over the webinterface. Had to do a power off/on. I have not had this before. Maybe the latest firmware is not so stable anymore. Or it was just a coincidence this happened. I have not had anyone else complaining about this, and there must be dozens of people that use the Homey app with the r7000. On my r7800 I have no issues at all. But I am working on some tweaks in the login procedure. Maybe that makes a change.

Yes, when setting the polling to 2 minutes it can take up to 2 minutes before Homey knows you are online.

**Comment by RexArne** [comment]
I had a few complete blockages of the R7000 lately - after years of working without any issue - where I had to power off/on. 
At that moment I wasn’t aware of the Homey connection issue, but It makes sense now reading your experience.

**Comment by gruijter** [comment]
This issue on pynetgear and r8000 seems to produce very similar behavior. I'm not using SSL in homey though.

https://github.com/MatMaul/pynetgear/issues/62

**Comment by gruijter** [comment]
This issue on pynetgear with an r8000 shows similar behavior. I'm not using SSL on Homey though.

https://github.com/MatMaul/pynetgear/issues/62

**Comment by gruijter** [comment]
@RexArne I have a new version of the Homey app: v2.4.0

It has multiple fixes and improvements in the HTTP/SOAP handling with a router. Could you give that a try (cli install from github, or wait a few days for the appstore release)

**Comment by RexArne** [comment]
I will try tonight but having some node js issues, so I don’t know if it is possible. Else I will wait on store release

**Comment by RexArne** [comment]
Installed v2.4.0 and changed the polling back to 20 seconds. I leave it for a few days and will give an  update or sooner if it stops again

**Comment by RexArne** [comment]
My R7000 stopped working again, after the update to 2.4.0 (and polling 20s).  I had to power off/on again. I now changed the polling to 60 seconds and will test.

**Comment by gruijter** [comment]
That's unfortunate. I made some more changes in a new version v2.5.0. I have had this running on my R7000 for over a day with 2 Homeys polling it @20s interval, but need to test longer.

You can get it already now from Github.

Edit: also with v2.5.0 the R7000 hangs eventually. I have no clue what is causing this. I suspect an instability in the router firmware itself that gets triggered when polling it (memory leak probably). Maybe you can revert the router to an older firmware, or set the polling to a longer period if that prevents the hangup from happening.

**Comment by gruijter** [comment]
I read some posts on the internet that a downgrade to the previous firmware solves the issue of freezing. You could give that a try also.

https://kb.netgear.com/000060253/R7000-Firmware-Version-1-0-9-42

**Comment by RexArne** [comment]
Thx for the info on that. I have installed v2.5.0 and will test this first for a few days. If not working properly, I might consider a firmware downgrade.

**Comment by gruijter** [comment]
Any news from your side?

**Comment by RexArne** [comment]
With polling on 60 seconds it works fine. But putting it on 20 or 30 seconds results in a unresponsive router.

**Comment by gruijter** [comment]
Thx for testing. I don't know what to do about that from the Homey app. It seems related to the router type and firmware version. I'll close the issue for now.
