### ISSUE TITLE
use tags with allow/block a device

### ISSUE THREAD

**Issue by llentjes** [gruijter/com.gruijter.netgear#25]
Is it possible to use tags with the cards "allow a device" and "block a device"?
This way it would be possible to selective allow/block devices coming online

**Comment by gruijter** [comment]
I would need to make additional flowcards for that. Good idea! Will do that in the next release.

**Comment by llentjes** [comment]
great. Thanks!

**Comment by gruijter** [comment]
New version v2.5.1  2019.05.02 Added Block/Allow device from flow with tag
is pending approval in the appstore.

Be carefull when using flow.athom.com to create your flow! I discovered a bug there that causes major trouble for mac address tags (the action card gets an additional space, resulting in the flow not working). I already made a bug report with athom for this. But in the mean time its better to make the flow from your mobile app.

**Comment by gruijter** [comment]
Hi @llentjes , it got released in the appstore. Can you please test and let me know if it works?

**Comment by gruijter** [comment]
@llentjes can you please provide feedback if this new function works correctly?

**Comment by gruijter** [comment]
@llentjes Bump....
