### ISSUE TITLE
Can't login to Netgear Orbi RBK50

### ISSUE THREAD

**Issue by Thijsseng** [gruijter/com.gruijter.netgear#26]
I try to connect with my Homey to the router. I want recieve my speed en my connect users. 
but without success. 
Also see https://community.athom.com/t/nieuwe-router-netgear-orbi-rbk50/12698/9

========== STARTING TEST ==========
Node version: v8.12.0
Netgear package version: 3.5.0
OS: linux 4.14.15-g81f15bab94
t = 0
trying to auto discover Netgear routers...
[{Firmware:V1.4.0.18WW,RegionTag:RBR50_WW,Region:ww,Model:RBR50,InternetConnectionStatus:Up,ParentalControlSupported:1,SOAPVersion:3.08,ReadyShareSupportedLevel:0,XCloudSupported:1,isBlankState:0,host:192.168.1.1,port:80}]
t = 3.737
trying to login...
login method: 1
t = 3.85
trying to getInfo...
{ModelName:RBR50,Description:Netgear Smart Wizard 3.0, specification 1.6 version,SerialNumber:**********,Firmwareversion:V1.4.0.18,SmartAgentversion:3.0,FirewallVersion:net-wall 2.0,OthersoftwareVersion:N/A,Hardwareversion:N/A,Otherhardwareversion:N/A,FirstUseDate:Sunday, 30 Sep 2007 01:10:03}
t = 4.14
trying to get supportFeatures...
Unauthorized. Incorrect username/password?
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetSupportFeatureListXMLResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceInfo:1\></m:GetSupportFeatureListXMLResponse>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
{}
t = 4.224
trying to get Parental Control Status...
Config started error: Error: Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetSupportFeatureListXMLResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceInfo:1\></m:GetSupportFeatureListXMLResponse>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
Parental Control Enabled: [object Object]
t = 4.225
trying to get Qos Status...
Config started error: Error: Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetSupportFeatureListXMLResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceInfo:1\></m:GetSupportFeatureListXMLResponse>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
Qos Enabled: [object Object]
t = 4.225
trying to get Qos Bandwidth options...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetSupportFeatureListXMLResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceInfo:1\></m:GetSupportFeatureListXMLResponse>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
{}
t = 4.225
trying to get Device Access Control Status...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetSupportFeatureListXMLResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceInfo:1\></m:GetSupportFeatureListXMLResponse>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
Block Device Enabled: [object Object]
t = 4.239
trying to get attachedDevices...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetSupportFeatureListXMLResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceInfo:1\></m:GetSupportFeatureListXMLResponse>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
Number of attached devices: undefined, method: 1
First attached device: undefined
t = 4.239
trying to get Guest Wifi Status...
2.4G-1 Guest wifi is not available
5.0G-1 Guest wifi is not available, method: 1
5.0G-2 Guest wifi is not available
t = 4.24
trying to get the Traffic Meter Enabled Status...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetSupportFeatureListXMLResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceInfo:1\></m:GetSupportFeatureListXMLResponse>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
Traffic Meter Enabled: [object Object]
t = 4.24
trying to get the Traffic Meter Options...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetSupportFeatureListXMLResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceInfo:1\></m:GetSupportFeatureListXMLResponse>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
{}
t = 4.24
trying to get trafficMeter...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetSupportFeatureListXMLResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceInfo:1\></m:GetSupportFeatureListXMLResponse>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
{}
t = 4.241
trying to check newFirmware...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetSupportFeatureListXMLResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceInfo:1\></m:GetSupportFeatureListXMLResponse>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
check newFirmware method: 1
{}
t = 4.241
trying to logout...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetSupportFeatureListXMLResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceInfo:1\></m:GetSupportFeatureListXMLResponse>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
{host:192.168.1.1,port:80,username:admin,password:*****,timeout:19000,sessionId:A7D88AE69687E58D9A00,loggedIn:false,configStarted:false,soapVersion:3,loginMethod:1,getAttachedDevicesMethod:1,checkNewFirmwareMethod:1,guestWifiMethod:{get50_1:1},lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetSupportFeatureListXMLResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceInfo:1\></m:GetSupportFeatureListXMLResponse>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
t = 4.241
test finished with 11 errors

**Comment by gruijter** [comment]
It does login correctly for the first command, but then fails on all the following commands. Did you also try to just par it as a device without running the compatibility test? If so, are you able to pair it?

**Comment by Thijsseng** [comment]
Yes i did. But the same issue.Greets GeertOp 5 mei 2019 21:28 schreef gruijter <notifications@github.com>:It does login correctly for the first command, but then fails on all the following commands. Did you also try to just par it as a device without running the compatibility test? If so, are you able to pair it?

**Comment by gruijter** [comment]
Makes me wonder if Netgear made changes to their login/API. If only I had a orbi to play around with...

**Comment by gruijter** [comment]
Rbk50 works for another user. What could be different in your setup? 

https://community.athom.com/t/nieuwe-router-netgear-orbi-rbk50/12698/15?u=gruijter

**Comment by gruijter** [comment]
Please upgrade to current firmware level: v2.3.1.60. To be able to do that from v1.x.x firmware you need to manually install v2.2.1.212 first.

**Comment by gruijter** [comment]
Any news on this @Thijsseng ? Does the new firmware resolve the issue?

**Comment by Thijsseng** [comment]
It works thank you for your help. Also see the Dutch community.With regards,Geert Thijssen.Op 8 mei 2019 20:43 schreef gruijter <notifications@github.com>:Any news on this @Thijsseng ? Does the new firmware resolve the issue?

**Comment by gruijter** [comment]
Super! 👍
