### ISSUE TITLE
Netgear R6020: Cannot read property 'soap-env:body' of undefined

### ISSUE THREAD

**Issue by mikke1** [gruijter/com.gruijter.netgear#27]
========== STARTING TEST ==========
Node version: v8.16.0
Netgear package version: 3.5.0
OS: linux 4.14.15-g81f15bab94
t = 0
trying to auto discover Netgear routers...
[{host:192.168.1.1,port:5000}]
t = 3.804
trying to login...
login method: 1
t = 4.01
trying to getInfo...
Cannot read property 'soap-env:body' of undefined
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?><v:Envelope xmlns:v=\http://schemas.xmlsoap.org/soap/envelope/\>\n  <v:Body>\n    <m:GetInfoResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceInfo:1\>\n      <ModelName>R6020</ModelName>\n      <Description>Netgear Smart Wizard 3.0, specification 0.8 version</Description>\n      <SerialNumber>53R48CB5001D1</SerialNumber>\n      <Firmwareversion>V1.0.0.40\n</Firmwareversion>\n      <SmartAgentversion>3.0</SmartAgentversion>\n      <FirewallVersion>ACOS NAT-Netfilter v1.0.0.1 (Linux cone NAT Hot Patch 06/21/2010)</FirewallVersion>\n      <VPNVersion>N/A</VPNVersion>\n      <OthersoftwareVersion>1.0.1</OthersoftwareVersion>\n      <Hardwareversion>R6020</Hardwareversion>\n      <Otherhardwareversion>N/A</Otherhardwareversion>\n      <FirstUseDate>Tuesday, 28 May 2019 13:22:02</FirstUseDate>\n      <DeviceName>R6020</DeviceName>\n      <FirmwareDLmethod>HTTP</FirmwareDLmethod>\n      <FirmwareLastUpdate>2019_5.24_20:43:43</FirmwareLastUpdate>\n      <FirmwareLastChecked>2019_5.27_22:50:6</FirmwareLastChecked>\n      <DeviceMode>0</DeviceMode>\n      <DeviceNameUserSet>0</DeviceNameUserSet>\n    </m:GetInfoResponse>\n    <ResponseCode>000</ResponseCode>\n  </v:Body>\n</v:Envelope>\n}
{SerialNumber:**********}
t = 4.309
trying to get supportFeatures...
Cannot read property 'soap-env:body' of undefined
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?><v:Envelope xmlns:v=\http://schemas.xmlsoap.org/soap/envelope/\>\n  <v:Body>\n    <m:GetSupportFeatureListXMLResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceInfo:1\>\n      <newFeatureList>\n<features>\n<OpenDNSParentalControl>1.0</OpenDNSParentalControl>\n<AccessControl>1.0</AccessControl>\n<GuestNetworkSchedule>1.0</GuestNetworkSchedule>\n<AttachedDevice>2.0</AttachedDevice>\n<NameNTGRDevice>1.0</NameNTGRDevice>\n</features>\n</newFeatureList>\n    </m:GetSupportFeatureListXMLResponse>\n    <ResponseCode>000</ResponseCode>\n  </v:Body>\n</v:Envelope>\n}
{}
t = 4.43
trying to get Parental Control Status...
Parental Control Enabled: false
t = 6.073
trying to get Qos Status...
Qos Enabled: false
t = 7.851
trying to get Qos Bandwidth options...
{newUplinkBandwidth:0,newDownlinkBandwidth:0,enabled:1}
t = 8.431
trying to get Device Access Control Status...
Block Device Enabled: false
t = 8.637
trying to get attachedDevices...
Number of attached devices: 7, method: 1
First attached device: {\IP\:\192.168.1.2\,\Name\:\PHILIPS-HUE\,\MAC\:\EC:B5:FA:01:99:48\,\ConnectionType\:\wired\,\Linkspeed\:0,\SignalStrength\:100,\AllowOrBlock\:\Allow\}
t = 15.234
trying to get Guest Wifi Status...
2.4G-1 Guest wifi enabled: false
5.0G-1 Guest wifi is not available, method: 1
5.0G-2 Guest wifi is not available
t = 15.676
trying to get the Traffic Meter Enabled Status...
Invalid response code from router: 404
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?><v:Envelope xmlns:v=\http://schemas.xmlsoap.org/soap/envelope/\>\n  <v:Body>\n    <m:GetTrafficMeterEnabledResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceConfig:1\></m:GetTrafficMeterEnabledResponse>\n    <ResponseCode>404</ResponseCode>\n  </v:Body>\n</v:Envelope>\n}
Traffic Meter Enabled: [object Object]
t = 15.867
trying to get the Traffic Meter Options...
Invalid response code from router: 404
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?><v:Envelope xmlns:v=\http://schemas.xmlsoap.org/soap/envelope/\>\n  <v:Body>\n    <m:GetTrafficMeterOptionsResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceConfig:1\></m:GetTrafficMeterOptionsResponse>\n    <ResponseCode>404</ResponseCode>\n  </v:Body>\n</v:Envelope>\n}
{}
t = 15.955
trying to get trafficMeter...
Invalid response code from router: 404
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?><v:Envelope xmlns:v=\http://schemas.xmlsoap.org/soap/envelope/\>\n  <v:Body>\n    <m:GetTrafficMeterStatisticsResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceConfig:1\></m:GetTrafficMeterStatisticsResponse>\n    <ResponseCode>404</ResponseCode>\n  </v:Body>\n</v:Envelope>\n}
{}
t = 16.152
trying to check newFirmware...
Cannot read property '1' of null
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?><v:Envelope xmlns:v=\http://schemas.xmlsoap.org/soap/envelope/\>\n  <v:Body>\n    <m:CheckAppNewFirmwareResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceConfig:1\>\n      <CurrentVersion>V1.0.0.40\n</CurrentVersion>\n      <NewVersion></NewVersion>\n      <ReleaseNote></ReleaseNote>\n    </m:CheckAppNewFirmwareResponse>\n    <ResponseCode>000</ResponseCode>\n  </v:Body>\n</v:Envelope>\n}
check newFirmware method: 2
{}
t = 22.202
trying to logout...
{host:192.168.1.1,port:5000,username:admin,password:*****,timeout:19000,sessionId:A7D88AE69687E58D9A00,loggedIn:false,configStarted:false,soapVersion:2,loginMethod:1,getAttachedDevicesMethod:1,checkNewFirmwareMethod:2,guestWifiMethod:{get50_1:1},lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?><v:Envelope xmlns:v=\http://schemas.xmlsoap.org/soap/envelope/\>\n  <v:Body>\n    <m:SOAPLogoutResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceConfig:1\></m:SOAPLogoutResponse>\n    <ResponseCode>000</ResponseCode>\n  </v:Body>\n</v:Envelope>\n}
t = 22.314
test finished with 6 errors

**Comment by gruijter** [comment]
Super, thx for this! Netgear apparently decided to change their SOAP response for your router. I made a new version for Homey. It is pending approval in the appstore. Can you please test and post the test result here again?

If you know how to 'sideload' an app on Homey, you can already start testing now. https://github.com/gruijter/com.gruijter.netgear

**Comment by mikke1** [comment]
Wow, that was quick! Thanks!
I don't know how to sideload, but will test and post results here as soon as app is approved in the appstore.

**Comment by gruijter** [comment]
Athom just approved it. Go get it (v2.5.2) !

**Comment by mikke1** [comment]
The router has been added successfully now, but it doesn't show any info. Internet connected and attached devices shows “-“. Up/download speed is also blank, but I think that’s because of the router itself. 
I have restarted the router, homey and the Netgear app (after reinstalling).
I’ll post the full test below.

**Comment by mikke1** [comment]
========== STARTING TEST ==========
Node version: v8.16.0
Netgear package version: 3.5.1
OS: linux 4.14.15-g81f15bab94
t = 0
trying to auto discover Netgear routers...
[{host:192.168.1.1,port:5000}]
t = 4.181
trying to login...
login method: 1
t = 4.269
trying to getInfo...
{ModelName:R6020,Description:Netgear Smart Wizard 3.0, specification 0.8 version,SerialNumber:**********,Firmwareversion:V1.0.0.40\n,SmartAgentversion:3.0,FirewallVersion:ACOS NAT-Netfilter v1.0.0.1 (Linux cone NAT Hot Patch 06/21/2010),VPNVersion:N/A,OthersoftwareVersion:1.0.1,Hardwareversion:R6020,Otherhardwareversion:N/A,FirstUseDate:Tuesday, 28 May 2019 18:30:20,DeviceName:R6020,FirmwareDLmethod:HTTP,FirmwareLastUpdate:2019_5.24_20:43:43,FirmwareLastChecked:2019_5.28_14:10:54,DeviceMode:0,DeviceNameUserSet:0}
t = 4.42
trying to get supportFeatures...
{OpenDNSParentalControl:1.0,AccessControl:1.0,GuestNetworkSchedule:1.0,AttachedDevice:2.0,NameNTGRDevice:1.0}
t = 4.532
trying to get Parental Control Status...
Parental Control Enabled: false
t = 5.688
trying to get Qos Status...
Qos Enabled: false
t = 7.202
trying to get Qos Bandwidth options...
{newUplinkBandwidth:0,newDownlinkBandwidth:0,enabled:1}
t = 7.638
trying to get Device Access Control Status...
Block Device Enabled: false
t = 7.714
trying to get attachedDevices...
Number of attached devices: 9, method: 2
First attached device: {\IP\:\192.168.1.3\,\Name\:\--\,\NameUserSet\:false,\MAC\:\B4:E6:2A:63:3C:23\,\ConnectionType\:\2.4GHz\,\SSID\:\Winternet is coming\,\Linkspeed\:144,\SignalStrength\:83,\AllowOrBlock\:\Allow\,\Schedule\:false,\DeviceTypeUserSet\:false,\Grouping\:0,\SchedulePeriod\:0}
t = 8.27
trying to get Guest Wifi Status...
2.4G-1 Guest wifi enabled: false
5.0G-1 Guest wifi is not available, method: 1
5.0G-2 Guest wifi is not available
t = 8.689
trying to get the Traffic Meter Enabled Status...
Invalid response code from router: 404
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?><v:Envelope xmlns:v=\http://schemas.xmlsoap.org/soap/envelope/\>\n  <v:Body>\n    <m:GetTrafficMeterEnabledResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceConfig:1\></m:GetTrafficMeterEnabledResponse>\n    <ResponseCode>404</ResponseCode>\n  </v:Body>\n</v:Envelope>\n}
Traffic Meter Enabled: [object Object]
t = 8.886
trying to get the Traffic Meter Options...
Invalid response code from router: 404
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?><v:Envelope xmlns:v=\http://schemas.xmlsoap.org/soap/envelope/\>\n  <v:Body>\n    <m:GetTrafficMeterOptionsResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceConfig:1\></m:GetTrafficMeterOptionsResponse>\n    <ResponseCode>404</ResponseCode>\n  </v:Body>\n</v:Envelope>\n}
{}
t = 9.079
trying to get trafficMeter...
Invalid response code from router: 404
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?><v:Envelope xmlns:v=\http://schemas.xmlsoap.org/soap/envelope/\>\n  <v:Body>\n    <m:GetTrafficMeterStatisticsResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceConfig:1\></m:GetTrafficMeterStatisticsResponse>\n    <ResponseCode>404</ResponseCode>\n  </v:Body>\n</v:Envelope>\n}
{}
t = 9.292
trying to check newFirmware...
Cannot read property '1' of null
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?><v:Envelope xmlns:v=\http://schemas.xmlsoap.org/soap/envelope/\>\n  <v:Body>\n    <m:CheckAppNewFirmwareResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceConfig:1\>\n      <CurrentVersion>V1.0.0.40\n</CurrentVersion>\n      <NewVersion></NewVersion>\n      <ReleaseNote></ReleaseNote>\n    </m:CheckAppNewFirmwareResponse>\n    <ResponseCode>000</ResponseCode>\n  </v:Body>\n</v:Envelope>\n}
check newFirmware method: 2
{}
t = 15.363
trying to logout...
{host:192.168.1.1,port:5000,username:admin,password:*****,timeout:19000,sessionId:A7D88AE69687E58D9A00,loggedIn:false,configStarted:false,soapVersion:2,loginMethod:1,getAttachedDevicesMethod:2,checkNewFirmwareMethod:2,guestWifiMethod:{get50_1:1},lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?><v:Envelope xmlns:v=\http://schemas.xmlsoap.org/soap/envelope/\>\n  <v:Body>\n    <m:SOAPLogoutResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceConfig:1\></m:SOAPLogoutResponse>\n    <ResponseCode>000</ResponseCode>\n  </v:Body>\n</v:Envelope>\n}
t = 15.456
test finished with 4 errors

**Comment by gruijter** [comment]
This looks better, but not perfect. Your router doesnt appear to have traffic statistics, so that is why you do not see up/download speed.

Do you still not get the number of attached devices and internet connection status after waiting some minutes? In the device settings you can select Homey as the device that checks if you are online. That should always work. 

Could you post the result here when browsing to http://routerlogin.net/currentsetting.htm

**Comment by mikke1** [comment]
No status at all, even after setting “Internet check” to Homey. Have tried deconnecting devices for 10+ minutes to see if it updates, but it still just says “-“. 

Results from currentsetting:
Firmware=V1.0.0.40WW RegionTag=R6020_WW Region=WW Model=R6020 InternetConnectionStatus=UP ParentalControlSupported=1 SOAPVersion=3.23 ReadyShareSupportedLevel=0 LoginMethod=2.0

**Comment by gruijter** [comment]
Just uploaded v2.5.3. That should fix the internet connected status and the attached device status for you. Can you test again when the app gets released?

**Comment by mikke1** [comment]
Yes, will do!

**Comment by gruijter** [comment]
It is ready in the store now.

**Comment by mikke1** [comment]
It works perfectly now, thank you so much for your help! The wife is also happy now, too. I will definitely donate a couple of beers!

**Comment by gruijter** [comment]
Awesome, happy it works! And donation received. Many thx🍻🤗
