### ISSUE TITLE
AFter update to V2.06 My R8000 is not connecting anymore to the app

### ISSUE THREAD

**Issue by canedje** [gruijter/com.gruijter.netgear#3]
After the last update I can not connect my router anymore.
I removed the Device Icon and tried to reinstall but I’m not able to connect.
Receiving the error, by pushing the test button: connect ECONNREFUSED xxxxxxxx:5000 Where xxxxx is my Ip adress.
I do have the Nigthhawk X6 R8000.
It worked fine before the update
I changed the SOAP port to 5000 (It was that number the version before)
Also not changing the SOAP port is not working (I don’t know what the SOAP port is about)

see:
Firmware=V1.0.4.18_10.1.49 RegionTag=R8000_WW Region=ww Model=R8000 InternetConnectionStatus=Up ParentalControlSupported=1 CircleEnabled=0 OpenDNSEnabled=0 SOAPVersion=3.21 LoginMethod=2.0 ReadyShareSupportedLevel=29 XCloudSupported=1 SmartNetworkSupported=0 DeviceMode=0

**Comment by gruijter** [comment]
Hi @canedje. Weird. Did you recently update the router firmware maybe? You could try to reboot both your router and homey, and see if you can pair then. Leave the soap port empty, and also the ip address. Only fill in the password during pairing.

**Comment by canedje** [comment]
No I didn't update the router firmware.
I did reset the Homey by PtP already yesterday.
I didn't reset the router yet. I will try tonight.
I also removed and did reinstall the app
I removed the device icon because it was showing a broken Chain and tried reinstall it by adding a device.

I tried pairing again, by only filling the password and left every thing else untouched. No result giving error after pushing the testbutton: router.getSoapPort is not a function

debug log:
![knipsel](https://user-images.githubusercontent.com/23150947/46393090-1ad7e600-c6e4-11e8-92a7-ed97a22c1e84.PNG)

**Comment by canedje** [comment]
I did reset the router. No result.
To be honest I do believe it is something in the app, because that is the only thing changed by the update

EDIT: I succeeded after several tries.
The modus I succeeded was:
entering the password, left the IP untouched and entered 5000 for the SOAP port

**Comment by gruijter** [comment]
Ok, I will have to check what changed. Actually the pairing was last changed 2 versions ago. Could it be that the pairing problem was already there in the previous version?

**Comment by canedje** [comment]
See my edit answer
I succeeded at the end after several tries by yes or no using handsettings on all the fields of the pairing settings.

**Comment by gruijter** [comment]
Ah, ok. I think I only need to check the auto Port detection part then. The error you posted then makes sense to me. Will try to get it fixed in a next Version😀

**Comment by canedje** [comment]
Thanks for the efford
Indeed entering the SOAP port by hand after resetting the router did the trick
