### ISSUE TITLE
Can connect but not access RAX 120 

### ISSUE THREAD

**Issue by lolpold** [gruijter/com.gruijter.netgear#30]
========== STARTING TEST ==========
Node version: v8.16.0
Netgear package version: 3.7.0
OS: linux 4.14.15-g81f15bab94
Info: Homey fw:2.2.0-rc.7 app: 2.5.5
t = 0
trying to auto discover Netgear routers...
t = 3.205
trying to login...
login method: 2
t = 3.265
trying to getInfo...
{ModelName:RAX120,Description:Netgear Smart Wizard 3.0, specification 1.6 version,SerialNumber:**********,Firmwareversion:V1.0.0.84,SmartAgentversion:3.0,FirewallVersion:net-wall 2.0,OthersoftwareVersion:N/A,Hardwareversion:RAX120,Otherhardwareversion:N/A,FirstUseDate:Sunday, 30 Sep 2007 01:10:03,DeviceName:RAX120,FirmwareDLmethod:HTTPS,FirmwareLastUpdate:2019_4.4_16:18:53,FirmwareLastChecked:2019_6.10_11:32:42,DeviceMode:0,DeviceModeCapability:0;1;2,DeviceNameUserSet:false}
t = 3.33
trying to get supportFeatures...
{DynamicQoS:1.0,AccessControl:1.0,SpeedTest:2.0,GuestNetworkSchedule:1.0,TCAcceptance:1.0,DeviceTypeIdentification:1.0,AttachedDevice:2.0,NameNTGRDevice:1.0,SmartConnect:2.0,MaxMonthlyTrafficLimitation:4095000000,SupportAXMode:1,SupportWPA3:1}
t = 3.434
trying to get the Device configuration...
{BlankState:0,NewBlockSiteEnable:0,NewBlockSiteName:0,NewTimeZone:+1,NewDaylightSaving:1}
t = 3.513
trying to get the LAN configuration...
{NewLANSubnet:255.255.255.0,NewWANLAN_Subnet_Match:0,NewLANMACAddress:0836C9181DDB,NewLANIP:10.0.0.1,NewDHCPEnabled:true}
t = 3.609
trying to get the WAN configuration...
{NewEnable:1,NewConnectionType:DHCP,NewExternalIPAddress:92.32.240.11,NewSubnetMask:255.255.248.0,NewAddressingType:DHCP,NewDefaultGateway:92.32.240.1,NewMACAddress:0836C9181DDC,NewMACAddressOverride:0,NewMaxMTUSize:1500,NewDNSEnabled:1,NewDNSServers:195.54.122.204 81.26.226.3}
t = 3.659
trying to get Parental Control Status...
Invalid response code from router: 404
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetEnableStatusResponse xmlns:m=\urn:NETGEAR-ROUTER:service:ParentalControl:1\></m:GetEnableStatusResponse>\r\n<ResponseCode>404</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
Parental Control Enabled: [object Object]
t = 3.754
trying to get Qos Status...
[{Firmware:V1.0.0.84WW,RegionTag:RAX120_WW,Region:ww,Model:RAX120,InternetConnectionStatus:Up,ParentalControlSupported:0,SOAPVersion:3.34,ReadyShareSupportedLevel:25,XCloudSupported:1,LoginMethod:2.0,host:10.0.0.1,port:80}]
t = 3.955
trying to login...
login method: 2
t = 4.1
trying to getInfo...
Qos Enabled: false
t = 4.41
trying to get Qos Bandwidth options...
{ModelName:RAX120,Description:Netgear Smart Wizard 3.0, specification 1.6 version,SerialNumber:**********,Firmwareversion:V1.0.0.84,SmartAgentversion:3.0,FirewallVersion:net-wall 2.0,OthersoftwareVersion:N/A,Hardwareversion:RAX120,Otherhardwareversion:N/A,FirstUseDate:Sunday, 30 Sep 2007 01:10:03,DeviceName:RAX120,FirmwareDLmethod:HTTPS,FirmwareLastUpdate:2019_4.4_16:18:53,FirmwareLastChecked:2019_6.10_11:32:42,DeviceMode:0,DeviceModeCapability:0;1;2,DeviceNameUserSet:false}
t = 4.436
trying to get supportFeatures...
{newUplinkBandwidth:0,newDownlinkBandwidth:0,enabled:2}
t = 4.478
trying to get Device Access Control Status...
{DynamicQoS:1.0,AccessControl:1.0,SpeedTest:2.0,GuestNetworkSchedule:1.0,TCAcceptance:1.0,DeviceTypeIdentification:1.0,AttachedDevice:2.0,NameNTGRDevice:1.0,SmartConnect:2.0,MaxMonthlyTrafficLimitation:4095000000,SupportAXMode:1,SupportWPA3:1}
t = 4.509
trying to get the Device configuration...
Block Device Enabled: true
t = 4.536
trying to get attachedDevices...
{BlankState:0,NewBlockSiteEnable:0,NewBlockSiteName:0,NewTimeZone:+1,NewDaylightSaving:1}
t = 4.587
trying to get the LAN configuration...
{NewLANSubnet:255.255.255.0,NewWANLAN_Subnet_Match:0,NewLANMACAddress:0836C9181DDB,NewLANIP:10.0.0.1,NewDHCPEnabled:true}
t = 4.654
trying to get the WAN configuration...
{NewEnable:1,NewConnectionType:DHCP,NewExternalIPAddress:92.32.240.11,NewSubnetMask:255.255.248.0,NewAddressingType:DHCP,NewDefaultGateway:92.32.240.1,NewMACAddress:0836C9181DDC,NewMACAddressOverride:0,NewMaxMTUSize:1500,NewDNSEnabled:1,NewDNSServers:195.54.122.204 81.26.226.3}
t = 4.722
trying to get Parental Control Status...
Invalid response code from router: 404
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetEnableStatusResponse xmlns:m=\urn:NETGEAR-ROUTER:service:ParentalControl:1\></m:GetEnableStatusResponse>\r\n<ResponseCode>404</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
Parental Control Enabled: [object Object]
t = 4.874
trying to get Qos Status...
Qos Enabled: false
t = 5.345
trying to get Qos Bandwidth options...
{newUplinkBandwidth:0,newDownlinkBandwidth:0,enabled:2}
t = 5.397
trying to get Device Access Control Status...
Block Device Enabled: true
t = 5.447
trying to get attachedDevices...
Cannot read property '1' of null
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetAttachDeviceResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceInfo:1\>    <NewAttachDevice>\r\n                    8@1;10.0.0.7;GOOGLE-HOME-MINI;E4:F0:42:1C:4B:F4;wireless;390;84;Allow;47@2;10.0.0.4;SHIELD;00:04:4B:4A:D2:59;wired;;100;Allow;47@3;10.0.0.6;CHROMECAST-AUDIO;54:60:09:EE:92:94;wireless;263;96;Allow;47@4;10.0.0.8;GOOGLE-HOME;D8:6C:63:4A:09:56;wireless;433;88;Allow;47@5;10.0.0.11;ROCKROBO;7C:49:EB:A1:77:30;wireless;26;94;Allow;47@6;10.0.0.10;HOMEY ;10:CE:A9:44:E8:C9;wireless;72;100;Allow;2@7;10.0.0.14;HARMONYHUB;C8:DB:26:05:8E:72;wireless;72;92;Allow;47@8;10.0.0.2;PHILIPS-HUE;00:17:88:AF:B2:00;wired;;100;Allow;47</NewAttachDevice>\r\n</m:GetAttachDeviceResponse>\r\n<ResponseCode>000</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
Number of attached devices: undefined, method: 1
First attached device: undefined
t = 15.415
trying to get Guest Wifi Status...
2.4G-1 Guest wifi is not available
5.0G-1 Guest wifi is not available, method: 1
5.0G-2 Guest wifi is not available
t = 15.461
trying to get Smart Connect Status...
Config started error: Error: Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetGuestAccessEnabledResponse xmlns:m=\urn:NETGEAR-ROUTER:service:WLANConfiguration:1\></m:GetGuestAccessEnabledResponse>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
Smart Connect Enabled: [object Object]
t = 15.462
trying to get the Traffic Meter Enabled Status...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetGuestAccessEnabledResponse xmlns:m=\urn:NETGEAR-ROUTER:service:WLANConfiguration:1\></m:GetGuestAccessEnabledResponse>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
Traffic Meter Enabled: [object Object]
t = 15.462
trying to get the Traffic Meter Options...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetGuestAccessEnabledResponse xmlns:m=\urn:NETGEAR-ROUTER:service:WLANConfiguration:1\></m:GetGuestAccessEnabledResponse>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
{}
t = 15.463
trying to get trafficMeter...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetGuestAccessEnabledResponse xmlns:m=\urn:NETGEAR-ROUTER:service:WLANConfiguration:1\></m:GetGuestAccessEnabledResponse>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
{}
t = 15.469
trying to check newFirmware...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetGuestAccessEnabledResponse xmlns:m=\urn:NETGEAR-ROUTER:service:WLANConfiguration:1\></m:GetGuestAccessEnabledResponse>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
check newFirmware method: 1
{}
t = 15.472
trying to logout...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetGuestAccessEnabledResponse xmlns:m=\urn:NETGEAR-ROUTER:service:WLANConfiguration:1\></m:GetGuestAccessEnabledResponse>\r\n<ResponseCode>401</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
{host:10.0.0.1,port:80,tls:false,username:admin,password:*****,timeout:19000,sessionId:A7D88AE69687E58D9A00,cookie:[jwt_local=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOiIyNDA3MjQiLCJpc3MiOiJ3d3cubmV0Z2Vhci5jb20iLCJzdWIiOiJub2RlLW5ldGdlYXJqcyJ9.78d731c9c9ab8ae06661b61d7948e919789afec0263c2595fcba73b0f6a5f287],loggedIn:false,configStarted:false,soapVersion:3,loginMethod:2,getAttachedDevicesMethod:1,checkNewFirmwareMethod:1,guestWifiMethod:{get50_1:1},lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetAttachDeviceResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceInfo:1\>    <NewAttachDevice>\r\n                    8@1;10.0.0.7;GOOGLE-HOME-MINI;E4:F0:42:1C:4B:F4;wireless;390;84;Allow;47@2;10.0.0.4;SHIELD;00:04:4B:4A:D2:59;wired;;100;Allow;47@3;10.0.0.6;CHROMECAST-AUDIO;54:60:09:EE:92:94;wireless;260;96;Allow;47@4;10.0.0.8;GOOGLE-HOME;D8:6C:63:4A:09:56;wireless;390;88;Allow;47@5;10.0.0.11;ROCKROBO;7C:49:EB:A1:77:30;wireless;26;94;Allow;47@6;10.0.0.10;HOMEY ;10:CE:A9:44:E8:C9;wireless;72;100;Allow;2@7;10.0.0.14;HARMONYHUB;C8:DB:26:05:8E:72;wireless;72;92;Allow;47@8;10.0.0.2;PHILIPS-HUE;00:17:88:AF:B2:00;wired;;100;Allow;47</NewAttachDevice>\r\n</m:GetAttachDeviceResponse>\r\n<ResponseCode>000</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
t = 15.473
test finished with 9 errors
Cannot read property '1' of null
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetAttachDeviceResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceInfo:1\>    <NewAttachDevice>\r\n                    8@1;10.0.0.7;GOOGLE-HOME-MINI;E4:F0:42:1C:4B:F4;wireless;390;84;Allow;47@2;10.0.0.4;SHIELD;00:04:4B:4A:D2:59;wired;;100;Allow;47@3;10.0.0.6;CHROMECAST-AUDIO;54:60:09:EE:92:94;wireless;260;96;Allow;47@4;10.0.0.8;GOOGLE-HOME;D8:6C:63:4A:09:56;wireless;390;88;Allow;47@5;10.0.0.11;ROCKROBO;7C:49:EB:A1:77:30;wireless;26;94;Allow;47@6;10.0.0.10;HOMEY ;10:CE:A9:44:E8:C9;wireless;72;100;Allow;2@7;10.0.0.14;HARMONYHUB;C8:DB:26:05:8E:72;wireless;72;92;Allow;47@8;10.0.0.2;PHILIPS-HUE;00:17:88:AF:B2:00;wired;;100;Allow;47</NewAttachDevice>\r\n</m:GetAttachDeviceResponse>\r\n<ResponseCode>000</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
Number of attached devices: undefined, method: 1
First attached device: undefined
t = 16.029
trying to get Guest Wifi Status...
2.4G-1 Guest wifi is not available
5.0G-1 Guest wifi is not available, method: 1
5.0G-2 Guest wifi is not available
t = 16.032
trying to get Smart Connect Status...
Config started error: Error: Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetAttachDeviceResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceInfo:1\>    <NewAttachDevice>\r\n                    8@1;10.0.0.7;GOOGLE-HOME-MINI;E4:F0:42:1C:4B:F4;wireless;390;84;Allow;47@2;10.0.0.4;SHIELD;00:04:4B:4A:D2:59;wired;;100;Allow;47@3;10.0.0.6;CHROMECAST-AUDIO;54:60:09:EE:92:94;wireless;260;96;Allow;47@4;10.0.0.8;GOOGLE-HOME;D8:6C:63:4A:09:56;wireless;390;88;Allow;47@5;10.0.0.11;ROCKROBO;7C:49:EB:A1:77:30;wireless;26;94;Allow;47@6;10.0.0.10;HOMEY ;10:CE:A9:44:E8:C9;wireless;72;100;Allow;2@7;10.0.0.14;HARMONYHUB;C8:DB:26:05:8E:72;wireless;72;92;Allow;47@8;10.0.0.2;PHILIPS-HUE;00:17:88:AF:B2:00;wired;;100;Allow;47</NewAttachDevice>\r\n</m:GetAttachDeviceResponse>\r\n<ResponseCode>000</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
Smart Connect Enabled: [object Object]
t = 16.032
trying to get the Traffic Meter Enabled Status...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetAttachDeviceResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceInfo:1\>    <NewAttachDevice>\r\n                    8@1;10.0.0.7;GOOGLE-HOME-MINI;E4:F0:42:1C:4B:F4;wireless;390;84;Allow;47@2;10.0.0.4;SHIELD;00:04:4B:4A:D2:59;wired;;100;Allow;47@3;10.0.0.6;CHROMECAST-AUDIO;54:60:09:EE:92:94;wireless;260;96;Allow;47@4;10.0.0.8;GOOGLE-HOME;D8:6C:63:4A:09:56;wireless;390;88;Allow;47@5;10.0.0.11;ROCKROBO;7C:49:EB:A1:77:30;wireless;26;94;Allow;47@6;10.0.0.10;HOMEY ;10:CE:A9:44:E8:C9;wireless;72;100;Allow;2@7;10.0.0.14;HARMONYHUB;C8:DB:26:05:8E:72;wireless;72;92;Allow;47@8;10.0.0.2;PHILIPS-HUE;00:17:88:AF:B2:00;wired;;100;Allow;47</NewAttachDevice>\r\n</m:GetAttachDeviceResponse>\r\n<ResponseCode>000</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
Traffic Meter Enabled: [object Object]
t = 16.033
trying to get the Traffic Meter Options...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetAttachDeviceResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceInfo:1\>    <NewAttachDevice>\r\n                    8@1;10.0.0.7;GOOGLE-HOME-MINI;E4:F0:42:1C:4B:F4;wireless;390;84;Allow;47@2;10.0.0.4;SHIELD;00:04:4B:4A:D2:59;wired;;100;Allow;47@3;10.0.0.6;CHROMECAST-AUDIO;54:60:09:EE:92:94;wireless;260;96;Allow;47@4;10.0.0.8;GOOGLE-HOME;D8:6C:63:4A:09:56;wireless;390;88;Allow;47@5;10.0.0.11;ROCKROBO;7C:49:EB:A1:77:30;wireless;26;94;Allow;47@6;10.0.0.10;HOMEY ;10:CE:A9:44:E8:C9;wireless;72;100;Allow;2@7;10.0.0.14;HARMONYHUB;C8:DB:26:05:8E:72;wireless;72;92;Allow;47@8;10.0.0.2;PHILIPS-HUE;00:17:88:AF:B2:00;wired;;100;Allow;47</NewAttachDevice>\r\n</m:GetAttachDeviceResponse>\r\n<ResponseCode>000</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
{}
t = 16.033
trying to get trafficMeter...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetAttachDeviceResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceInfo:1\>    <NewAttachDevice>\r\n                    8@1;10.0.0.7;GOOGLE-HOME-MINI;E4:F0:42:1C:4B:F4;wireless;390;84;Allow;47@2;10.0.0.4;SHIELD;00:04:4B:4A:D2:59;wired;;100;Allow;47@3;10.0.0.6;CHROMECAST-AUDIO;54:60:09:EE:92:94;wireless;260;96;Allow;47@4;10.0.0.8;GOOGLE-HOME;D8:6C:63:4A:09:56;wireless;390;88;Allow;47@5;10.0.0.11;ROCKROBO;7C:49:EB:A1:77:30;wireless;26;94;Allow;47@6;10.0.0.10;HOMEY ;10:CE:A9:44:E8:C9;wireless;72;100;Allow;2@7;10.0.0.14;HARMONYHUB;C8:DB:26:05:8E:72;wireless;72;92;Allow;47@8;10.0.0.2;PHILIPS-HUE;00:17:88:AF:B2:00;wired;;100;Allow;47</NewAttachDevice>\r\n</m:GetAttachDeviceResponse>\r\n<ResponseCode>000</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
{}
t = 16.033
trying to check newFirmware...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetAttachDeviceResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceInfo:1\>    <NewAttachDevice>\r\n                    8@1;10.0.0.7;GOOGLE-HOME-MINI;E4:F0:42:1C:4B:F4;wireless;390;84;Allow;47@2;10.0.0.4;SHIELD;00:04:4B:4A:D2:59;wired;;100;Allow;47@3;10.0.0.6;CHROMECAST-AUDIO;54:60:09:EE:92:94;wireless;260;96;Allow;47@4;10.0.0.8;GOOGLE-HOME;D8:6C:63:4A:09:56;wireless;390;88;Allow;47@5;10.0.0.11;ROCKROBO;7C:49:EB:A1:77:30;wireless;26;94;Allow;47@6;10.0.0.10;HOMEY ;10:CE:A9:44:E8:C9;wireless;72;100;Allow;2@7;10.0.0.14;HARMONYHUB;C8:DB:26:05:8E:72;wireless;72;92;Allow;47@8;10.0.0.2;PHILIPS-HUE;00:17:88:AF:B2:00;wired;;100;Allow;47</NewAttachDevice>\r\n</m:GetAttachDeviceResponse>\r\n<ResponseCode>000</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
check newFirmware method: 1
{}
t = 16.034
trying to logout...
Not logged in
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetAttachDeviceResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceInfo:1\>    <NewAttachDevice>\r\n                    8@1;10.0.0.7;GOOGLE-HOME-MINI;E4:F0:42:1C:4B:F4;wireless;390;84;Allow;47@2;10.0.0.4;SHIELD;00:04:4B:4A:D2:59;wired;;100;Allow;47@3;10.0.0.6;CHROMECAST-AUDIO;54:60:09:EE:92:94;wireless;260;96;Allow;47@4;10.0.0.8;GOOGLE-HOME;D8:6C:63:4A:09:56;wireless;390;88;Allow;47@5;10.0.0.11;ROCKROBO;7C:49:EB:A1:77:30;wireless;26;94;Allow;47@6;10.0.0.10;HOMEY ;10:CE:A9:44:E8:C9;wireless;72;100;Allow;2@7;10.0.0.14;HARMONYHUB;C8:DB:26:05:8E:72;wireless;72;92;Allow;47@8;10.0.0.2;PHILIPS-HUE;00:17:88:AF:B2:00;wired;;100;Allow;47</NewAttachDevice>\r\n</m:GetAttachDeviceResponse>\r\n<ResponseCode>000</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
{host:10.0.0.1,port:80,tls:false,username:admin,password:*****,timeout:19000,sessionId:A7D88AE69687E58D9A00,cookie:[jwt_local=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOiIyNDA3MjQiLCJpc3MiOiJ3d3cubmV0Z2Vhci5jb20iLCJzdWIiOiJub2RlLW5ldGdlYXJqcyJ9.78d731c9c9ab8ae06661b61d7948e919789afec0263c2595fcba73b0f6a5f287],loggedIn:false,configStarted:false,soapVersion:3,loginMethod:2,getAttachedDevicesMethod:1,checkNewFirmwareMethod:1,guestWifiMethod:{get50_1:1},lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n<m:GetAttachDeviceResponse xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceInfo:1\>    <NewAttachDevice>\r\n                    8@1;10.0.0.7;GOOGLE-HOME-MINI;E4:F0:42:1C:4B:F4;wireless;390;84;Allow;47@2;10.0.0.4;SHIELD;00:04:4B:4A:D2:59;wired;;100;Allow;47@3;10.0.0.6;CHROMECAST-AUDIO;54:60:09:EE:92:94;wireless;260;96;Allow;47@4;10.0.0.8;GOOGLE-HOME;D8:6C:63:4A:09:56;wireless;390;88;Allow;47@5;10.0.0.11;ROCKROBO;7C:49:EB:A1:77:30;wireless;26;94;Allow;47@6;10.0.0.10;HOMEY ;10:CE:A9:44:E8:C9;wireless;72;100;Allow;2@7;10.0.0.14;HARMONYHUB;C8:DB:26:05:8E:72;wireless;72;92;Allow;47@8;10.0.0.2;PHILIPS-HUE;00:17:88:AF:B2:00;wired;;100;Allow;47</NewAttachDevice>\r\n</m:GetAttachDeviceResponse>\r\n<ResponseCode>000</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}
t = 16.034
test finished with 16 errors

**Comment by lolpold** [comment]
The issue started about when I upgraded to RC7, haven't done any changes to the router or settings in homey.

**Comment by gruijter** [comment]
Have you already tried to do a ptp of the router?

**Comment by lolpold** [comment]
What does ptp stand for?

**Comment by gruijter** [comment]
Pull the plug (full power down and up) 😉

**Comment by lolpold** [comment]
Router: PTP x 2 
Router: Reboot x 3
Homey: PTP x 1
Homey: Reboot x 4 

So yes that has been done sadly :(

**Comment by gruijter** [comment]
Ok thx. I'l see what I can make out from your logs and make some code changes probably. I will let you know when I have something new to test for you. Do you know how to sideload an app from github?

**Comment by lolpold** [comment]
Okey great! I can google it :)

**Comment by gruijter** [comment]
I just uploaded v2.5.6  to the appstore for approval by Athom.
It should fix getAttachedDevices for your router. 

You can install from github (sideload) or wait for the appstore approval.

Let me know if this indeed fixes your issue :)

**Comment by gruijter** [comment]
And could you run the test again and post it here? Thx.

**Comment by lolpold** [comment]
========== STARTING TEST ==========
Node version: v8.16.0
Netgear package version: 3.7.1
OS: linux 4.14.15-g81f15bab94
Info: Homey fw:2.2.0-rc.7 app: 2.5.6
t = 0
trying to auto discover Netgear routers...
[{Firmware:V1.0.1.86WW,RegionTag:RAX120_WW,Region:ww,Model:RAX120,InternetConnectionStatus:Up,SOAPVersion:3.34,ReadyShareSupportedLevel:25,XCloudSupported:1,isBlankState:0,LoginMethod:2.0,host:10.0.0.1,port:80}]
t = 3.936
trying to login...
login method: 2
t = 3.983
trying to getInfo...
{ModelName:RAX120,Description:Netgear Smart Wizard 3.0, specification 1.6 version,SerialNumber:**********,Firmwareversion:V1.0.1.86,SmartAgentversion:3.0,FirewallVersion:net-wall 2.0,OthersoftwareVersion:N/A,Hardwareversion:RAX120,Otherhardwareversion:N/A,FirstUseDate:Sunday, 30 Sep 2007 01:10:03,DeviceName:RAX120,FirmwareDLmethod:HTTPS,FirmwareLastUpdate:2019_6.10_16:40:17,FirmwareLastChecked:2019_6.13_6:47:2,DeviceMode:0,DeviceModeCapability:0;1;2,DeviceNameUserSet:false}
t = 4.109
trying to get supportFeatures...
{DynamicQoS:1.0,AccessControl:1.0,SpeedTest:2.0,GuestNetworkSchedule:1.0,TCAcceptance:1.0,DeviceTypeIdentification:1.0,AttachedDevice:2.0,NameNTGRDevice:1.0,SmartConnect:2.0,MaxMonthlyTrafficLimitation:4095000000,SupportAXMode:1,SupportWPA3:1}
t = 4.21
trying to get the Device configuration...
{BlankState:0,NewBlockSiteEnable:0,NewBlockSiteName:0,NewTimeZone:+1,NewDaylightSaving:1}
t = 4.278
trying to get the LAN configuration...
{NewLANSubnet:255.255.255.0,NewWANLAN_Subnet_Match:0,NewLANMACAddress:0836C9181DDB,NewLANIP:10.0.0.1,NewDHCPEnabled:true}
t = 4.35
trying to get the WAN configuration...
{NewEnable:1,NewConnectionType:DHCP,NewExternalIPAddress:92.32.240.11,NewSubnetMask:255.255.248.0,NewAddressingType:DHCP,NewDefaultGateway:92.32.240.1,NewMACAddress:0836C9181DDC,NewMACAddressOverride:0,NewMaxMTUSize:1500,NewDNSEnabled:1,NewDNSServers:81.26.228.3 81.26.227.3}
t = 4.424
trying to get Parental Control Status...
Invalid response code from router: 404
{lastResponse:\r\n

**Comment by lolpold** [comment]
Now it works to get everything! 
But my last issue with the flow being disabled is back now for some reason. 
I will try to reset the app and the router again to see if that helps. 

Will open new issue if I can't get it working. Good job fixing this though 🥇
