### ISSUE TITLE
 [Feature request/improvement] Add router to trigger a flow if a device is nearby without connecting.

### ISSUE THREAD

**Issue by Phearz** [gruijter/com.gruijter.netgear#31]
Should the Netgear routers log when a handshake with a non connecting device that is within its vicinity and trigger an even based on that. 

In other words scan for mac addresses and trigger based on that. Isn't that logged in a netgear router ? 

If it was possible it would be so awesome to make a guest logic management based on that and don't always ask your friends to connect to you wifi to keep track of them entering your home.

If its not possible sorry to have wasted your time 
// Dennis Törnkvist

**Comment by gruijter** [comment]
Nice idea. Unfortunately not possible from the netgear soap interface. For this functionality you would need special software e.g. on a raspberry pi. Also not sure if it is legal to scan for unconnected devices....
