### ISSUE TITLE
Opslaan button missing

### ISSUE THREAD

**Issue by canedje** [gruijter/com.gruijter.netgear#32]
On my Android phone 
At the end of the procedure the "opslaan" button is missing.
Are attached picture 
![Screenshot_20191015-165140_Homey](https://user-images.githubusercontent.com/23150947/66847267-67026b00-ef73-11e9-8c30-245fa290b8d0.jpg)

**Comment by gruijter** [comment]
Fixed in V 3.0.1 (pending approval in the appstore)
Can you please verify and let me know if it works now on all your phones?
