### ISSUE TITLE
Error "Failed to login" / "socket timeout"

### ISSUE THREAD

**Issue by Eternity-again** [gruijter/com.gruijter.netgear#34]
App log: 3c7bb98f-8742-429b-92ee-b08dc21755ea
App version v3.0.1

I noticed a phone not reporting online/offline. The App states that my router (R7000) could not be logged into. Wrong credentials. 

I entered the unchanged credentials again. The R7000 device is seen and the error is gone. After a short while (1 minute) the device is lost again/ Socket timeout / wrong credentials

**Comment by gruijter** [comment]
I think I can reproduce the problem on my own R7000. I will further investigate. Thx 4 reporting the issue!

**Comment by seegersnl** [comment]
Same issue here cannot login r7000 and v3.0.1 i am on the latest beta rc19. Update: enabled upnp and restarted the router, can login now but still get two errors don’t now wat it is but maybe you can get some info from it. After a while I cannot login anymore (second log).

========== STARTING TEST ==========
Node version: v8.16.0
Netgear package version: 3.9.7
OS: linux 4.14.15-g81f15bab94
Info: Homey fw:3.0.0-rc.19 app: 3.0.1
t = 0
trying to auto discover Netgear routers...
[{Firmware:V1.0.9.88_10.2.88,RegionTag:R7000_WW,Region:ww,Model:R7000,InternetConnectionStatus:Up,ParentalControlSupported:1,CircleEnabled:0,OpenDNSEnabled:0,SOAPVersion:3.21,LoginMethod:2.0,ReadyShareSupportedLevel:29,XCloudSupported:1,DeviceMode:0,host:192.168.1.1,port:5000}]
t = 3.97
trying to login...
login method: 2
t = 4.032
trying to getInfo...
{ModelName:R7000,Description:Netgear Smart Wizard 3.0, specification 0.7 version,SerialNumber:**********,Firmwareversion:V1.0.9.88,SmartAgentversion:3.0,FirewallVersion:ACOS NAT-Netfilter v3.0.0.5 (Linux Cone NAT Hot Patch 06/11/2010),VPNVersion:N/A,OthersoftwareVersion:10.2.88,Hardwareversion:R7000,Otherhardwareversion:N/A,FirstUseDate:Friday, 09 Aug 2019 21:57:22,DeviceName:R7000,FirmwareDLmethod:Null,FirmwareLastUpdate:Null,FirmwareLastChecked:Null,DeviceMode:0}
t = 4.197
trying to get System Uptime (hh:mm:ss)...
472:24:14
t = 4.254
trying to getSystemInfo...
{NewCPUUtilization:33,NewPhysicalMemory:256,NewMemoryUtilization:61,NewPhysicalFlash:128,NewAvailableFlash:128}
t = 4.328
trying to get supportFeatures...
{DynamicQoS:1.0,OpenDNSParentalControl:1.0,CircleParentalControl:2.0,MaxMonthlyTrafficLimitation:4095000000,AccessControl:1.0,SpeedTest:2.0,BitDefenderSecurity:1.0,GuestNetworkSchedule:1.0,TCAcceptance:1.0,SmartConnect:2.0,AttachedDevice:2.0,NameNTGRDevice:1.0,DeviceTypeIcon:2.1,PasswordReset:2.0}
t = 4.424
trying to get the Device configuration...
{BlankState:0,NewBlockSiteEnable:0,NewTimeZone:+1,NewDaylightSaving:1}
t = 4.5
trying to get the LAN configuration...
{NewLANSubnet:255.255.255.0,NewWANLAN_Subnet_Match:1,NewLANMACAddress:DCEF099F8B09,NewLANIP:192.168.1.1,NewDHCPEnabled:true}
t = 4.581
trying to get the WAN configuration...
{NewEnable:1,NewConnectionType:DHCP,NewExternalIPAddress:5.132.87.151,NewSubnetMask:255.255.255.0,NewAddressingType:DHCP,NewDefaultGateway:5.132.87.1,NewMACAddress:DCEF099F8B0A,NewMACAddressOverride:0,NewMaxMTUSize:1500,NewDNSEnabled:1,NewDNSServers:37.143.84.228 37.143.84.229 }
t = 4.972
trying to get Parental Control Status...
Parental Control Enabled: false
t = 5.167
trying to get Qos Status...
Qos Enabled: false
t = 5.216
trying to get Qos Bandwidth options...
{newUplinkBandwidth:0,newDownlinkBandwidth:0,enabled:2}
t = 5.278
trying to get Device Access Control Status...
Block Device Enabled: true
t = 5.329
trying to get attachedDevices method 1...
Number of attached devices: 18
First attached device: {\IP\:\192.168.1.2\,\Name\:\--\,\MAC\:\40:CB:C0:C2:77:FF\,\ConnectionType\:\wired\,\Linkspeed\:null,\SignalStrength\:100,\AllowOrBlock\:\Allow\}
t = 8.372
trying to get attachedDevices method 2...
Number of attached devices: 18
First attached device: {\IP\:\192.168.1.105\,\Name\:\SEEGERS\,\NameUserSet\:false,\MAC\:\00:11:32:9C:D9:2A\,\ConnectionType\:\wired\,\SignalStrength\:100,\AllowOrBlock\:\Allow\,\Schedule\:false,\DeviceType\:33,\DeviceTypeUserSet\:false,\DeviceTypeV2\:20,\DeviceTypeNameV2\:\NAS\,\Upload\:0,\Download\:0,\QosPriority\:0,\DeviceModelUserSet\:false,\DeviceModel\:\DS218+\,\Grouping\:0,\SchedulePeriod\:0}
t = 9.747
trying to get available and selected WiFi channels...
Available channels 2.4G-1: Auto,1,2,3,4,5,6,7,8,9,10,11,12,13
selected channel 2.4G-1: Auto
Available channels 5.0G-1: 36,40,44,48
selected channel 5.0G-1: 44
Available channels 5.0G-2: 36,40,44,48,52,56,60,64,100,104,108,112,116,120,124,128
5.0G-2 channel is not available
t = 10.646
trying to get Smart Connect Status...
Smart Connect Enabled: false
t = 10.95
trying to get Guest Wifi Status...
2.4G-1 Guest wifi enabled: false
5.0G-1 Guest wifi enabled: false, method: 2
5.0G-2 Guest wifi enabled: false
t = 11.115
trying to get the Traffic Meter Enabled Status...
Traffic Meter Enabled: true
t = 11.164
trying to get the Traffic Meter Options...
{newControlOption:No Limit,newNewMonthlyLimit:0,restartHour:0,restartMinute:0,restartDay:1}
t = 11.647
trying to get trafficMeter...
{newTodayUpload:471.32,newTodayDownload:3623,newMonthUpload:10068,newMonthDownload:57666}
t = 11.7
trying to check newFirmware...
check newFirmware method: 2
{currentVersion:1.0.9.88,newVersion:,releaseNote:}
t = 15.335
trying to get router logs...
socket hang up
{lastResponse:{message:socket hang up,code:ECONNRESET}}
last log: undefined
t = 16.148
trying to logout...
connect ECONNREFUSED 192.168.1.1:5000
{lastResponse:{message:connect ECONNREFUSED 192.168.1.1:5000,code:ECONNREFUSED}}
{host:192.168.1.1,port:5000,tls:false,username:admin,password:*****,timeout:18000,sessionId:A7D88AE69687E58D9A00,cookie:true,loggedIn:true,configStarted:false,soapVersion:3,loginMethod:2,checkNewFirmwareMethod:2,guestWifiMethod:{get50_1:2},lastResponse:...}
t = 16.154
test finished with 2 errors



========== STARTING TEST ==========
Node version: v8.16.0
Netgear package version: 3.9.7
OS: linux 4.14.15-g81f15bab94
Info: Homey fw:3.0.0-rc.19 app: 3.0.1
t = 0
trying to auto discover Netgear routers...
[{Firmware:V1.0.9.88_10.2.88,RegionTag:R7000_WW,Region:ww,Model:R7000,InternetConnectionStatus:Up,ParentalControlSupported:1,CircleEnabled:0,OpenDNSEnabled:0,SOAPVersion:3.21,LoginMethod:2.0,ReadyShareSupportedLevel:29,XCloudSupported:1,DeviceMode:0,host:192.168.1.1}]
t = 3.808
trying to login...
{message:Failed to login}
{host:192.168.1.1,port:5000,tls:false,username:admin,password:*****,timeout:18000,sessionId:A7D88AE69687E58D9A00,loggedIn:true,configStarted:false,soapVersion:3,loginMethod:2.22,checkNewFirmwareMethod:2,guestWifiMethod:{get50_1:2},lastResponse:{message:connect ECONNREFUSED 192.168.1.1:5000,code:ECONNREFUSED}}

**Comment by gruijter** [comment]
It seems to be related to buggy firmware of the r7000. It now surfaces because in app v3.0.1 I added retrieving the router logs.
A ptp (power cycle) of the r7000 solves it temporarely. In the next version I will make log retrieval user selectable so hopefully the r700 bug doesn't surface anymore.

**Comment by gruijter** [comment]
Caused by buggy R7000 firmware. You need to do a PTP (power cycle) of the R7000. Should occur less often in app v3.0.2 due to disabled log retrieval.
