### ISSUE TITLE
Test rrsult

### ISSUE THREAD

**Issue by Eternity-again** [gruijter/com.gruijter.netgear#35]
========== STARTING TEST ==========
Node version: v8.16.0
Netgear package version: 3.9.7
OS: linux 4.14.15-g81f15bab94
Info: Homey fw:3.0.0-rc.17 app: 3.0.1
t = 0
trying to auto discover Netgear routers...
{message:No Netgear router could be discovered}
{host:192.168.1.2,port:,tls:false,username:admin,password:*****,timeout:18000,sessionId:A7D88AE69687E58D9A00,loggedIn:false,configStarted:false,soapVersion:3,loginMethod:2,guestWifiMethod:{},lastResponse:{message:No Netgear router could be discovered}}

LOG
[log] [MyApp] Router compatibility test started2019-10-24 09:14:34 [log] [MyApp] Router discovery started2019-10-24 09:14:00 [attached_device] [5] device init LGwebOSTV - 78:5D:C8:73:68:812019-10-24 09:14:00 [attached_device] [4] device init volumio - B8:27:EB:5E:45:9E2019-10-24 09:14:00 [attached_device] [3] device init LIBREELEC - B8:27:EB:B0:57:372019-10-24 09:14:00 [attached_device] [2] device init iPhonevanMidas - 84:89:AD:A9:36:682019-10-24 09:14:00 [attached_device] [1] device init Motorola-moto g(7) plus - 0C:CB:85:9F:04:252019-10-24 09:14:00 [attached_device] [0] device init iPhone8vanTobias - 80:4A:14:92:B4:EA2019-10-24 09:14:00 [attached_device] AttachedDeviceDriver onInit2019-10-24 09:13:58 [log_analyzer] LogAnalyzerDriver onInit2019-10-24 09:13:58 [netgear] NetgearDriver onInit2019-10-17 21:57:08 [log] [MyApp] app unload called2019-10-17 21:51:42 [netgear] [0] Online: 00:04:20:EF:0D:3D HarmonyHub 192.168.1.1012019-10-17 21:48:51 [attached_device] [2] Connected: iPhonevanMidas - 84:89:AD:A9:36:68 192.168.1.1122019-10-17 21:46:51 [netgear] [0] Offline: 00:04:20:EF:0D:3D --2019-10-17 21:44:47 [attached_device] [4] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 21:44:47 [attached_device] [4] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 21:44:47 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 21:44:47 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 21:18:40 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 21:14:37 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 20:52:38 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 20:00:39 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: read ECONNRESET2019-10-17 19:58:35 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 19:57:33 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 19:52:34 [netgear] [0] Online: 00:04:20:EF:0D:3D HarmonyHub 192.168.1.1012019-10-17 19:49:34 [attached_device] [4] Connected: LGwebOSTV - 78:5D:C8:73:68:81 192.168.1.1092019-10-17 19:46:32 [attached_device] [1] Connected: Motorola-moto g(7) plus - 0C:CB:85:9F:04:25 192.168.1.1052019-10-17 19:33:36 [netgear] [0] error getting traffic meter info2019-10-17 19:29:35 [netgear] [0] error getting traffic meter info2019-10-17 19:26:37 [netgear] [0] Offline: 00:04:20:EF:0D:3D --2019-10-17 19:25:28 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 19:23:36 [netgear] [0] Online: 00:04:20:EF:0D:3D -- --2019-10-17 19:22:28 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 18:59:26 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 18:57:36 [attached_device] [1] Disconnected: Motorola-moto g(7) plus - 0C:CB:85:9F:04:252019-10-17 18:56:29 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 18:54:32 [netgear] [0] Offline: 00:04:20:EF:0D:3D --2019-10-17 18:52:29 [netgear] [0] Online: 00:04:20:EF:0D:3D -- --2019-10-17 18:39:26 [attached_device] [2] Disconnected: iPhonevanMidas - 84:89:AD:A9:36:682019-10-17 18:06:22 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 18:05:21 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 18:02:49 [netgear] [0] error getting traffic meter info2019-10-17 17:59:23 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 17:58:22 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 17:56:22 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 17:45:22 [netgear] [0] Online: 28:F0:76:20:D7:8C iMac-van-Ernst 192.168.1.1142019-10-17 17:38:35 [attached_device] [2] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } signal_strength t@2019-10-17 17:37:22 [attached_device] [2] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } signal_strength t@2019-10-17 17:37:22 [attached_device] [4] Disconnected: LGwebOSTV - 78:5D:C8:73:68:812019-10-17 17:36:24 [netgear] [0] Offline: 00:04:20:EF:0D:3D HarmonyHub2019-10-17 17:35:23 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 17:30:21 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 17:27:23 [attached_device] [2] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } signal_strength t@2019-10-17 17:26:18 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 17:25:22 [attached_device] [2] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } signal_strength t@2019-10-17 17:10:54 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 17:09:59 [attached_device] [2] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 17:09:59 [attached_device] [2] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 17:09:59 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 17:09:59 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 16:46:38 [attached_device] [2] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 16:46:38 [attached_device] [2] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 16:46:38 [attached_device] [4] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 16:46:38 [attached_device] [4] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 16:46:38 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 16:46:38 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 16:45:38 [attached_device] [2] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 16:45:38 [attached_device] [2] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 16:45:38 [attached_device] [4] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 16:45:38 [attached_device] [4] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 16:45:38 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 16:45:38 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 16:44:56 [attached_device] [2] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 16:44:56 [attached_device] [2] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 16:44:56 [attached_device] [4] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 16:44:56 [attached_device] [4] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 16:44:56 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 16:44:56 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 16:44:56 [netgear] [0] error getting traffic meter info2019-10-17 16:40:49 [attached_device] [2] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 16:40:49 [attached_device] [2] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 16:40:49 [attached_device] [4] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 16:40:49 [attached_device] [4] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 16:40:49 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 16:40:49 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 16:40:49 [netgear] [0] error getting traffic meter info2019-10-17 16:27:32 [attached_device] [4] Connected: LGwebOSTV - 78:5D:C8:73:68:81 192.168.1.1092019-10-17 16:24:15 [attached_device] [2] Connected: iPhonevanMidas - 84:89:AD:A9:36:68 192.168.1.1122019-10-17 16:23:15 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } signal_strength t@2019-10-17 16:18:14 [attached_device] [1] Connected: Motorola-moto g(7) plus - 0C:CB:85:9F:04:25 192.168.1.1052019-10-17 16:17:55 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: The connection was terminated while the message was still being sent2019-10-17 16:16:51 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: The connection was terminated while the message was still being sent2019-10-17 16:15:31 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 16:14:30 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 16:12:30 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 16:11:32 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 16:10:30 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 16:09:32 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 16:08:30 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 16:07:12 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 16:06:12 [attached_device] [1] Disconnected: Motorola-moto g(7) plus - 0C:CB:85:9F:04:252019-10-17 16:06:12 [netgear] [0] error getting traffic meter info2019-10-17 16:06:11 [netgear] [0] Still busy. Skipping a poll2019-10-17 16:04:47 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 16:03:13 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 15:57:26 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 15:57:26 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 15:57:10 [netgear] [0] Still busy. Skipping a poll2019-10-17 15:31:49 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 15:31:49 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 15:13:08 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 15:09:07 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 15:06:09 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 14:49:12 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } signal_strength t@2019-10-17 14:48:21 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } signal_strength t@2019-10-17 14:47:15 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } signal_strength t@2019-10-17 14:45:08 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: read ECONNRESET2019-10-17 14:43:12 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } signal_strength t@2019-10-17 14:42:14 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } signal_strength t@2019-10-17 14:40:06 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 14:39:09 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: read ECONNRESET2019-10-17 14:38:12 [attached_device] [1] Connected: Motorola-moto g(7) plus - 0C:CB:85:9F:04:25 192.168.1.1052019-10-17 14:19:05 [netgear] [0] error getting traffic meter info2019-10-17 14:14:08 [netgear] [0] error getting traffic meter info2019-10-17 14:06:03 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: read ECONNRESET2019-10-17 13:58:02 [attached_device] [1] Disconnected: Motorola-moto g(7) plus - 0C:CB:85:9F:04:252019-10-17 13:49:04 [netgear] [0] error getting traffic meter info2019-10-17 13:14:15 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 13:10:00 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 13:08:35 [netgear] [0] error getting traffic meter info2019-10-17 13:07:21 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 13:07:21 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 13:06:14 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 13:05:33 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 13:04:52 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 12:44:59 [netgear] [0] error getting traffic meter info2019-10-17 12:41:54 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 12:40:55 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 12:30:25 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 12:30:25 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 12:12:53 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 12:09:01 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 12:09:01 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 12:05:01 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 12:05:01 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 11:47:52 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } signal_strength t@2019-10-17 11:46:52 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } signal_strength t@2019-10-17 11:45:52 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } signal_strength t@2019-10-17 11:42:52 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } signal_strength t@2019-10-17 11:39:03 [netgear] [0] Online: 04:CF:8C:F3:03:29 lumi-gateway-v3_miio259195784 192.168.1.1072019-10-17 11:37:50 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 11:37:02 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 11:37:02 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 11:37:02 [netgear] [0] Offline: 04:CF:8C:F3:03:29 lumi-gateway-v3_miio2591957842019-10-17 11:35:49 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 11:28:50 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 11:08:59 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: read ECONNRESET2019-10-17 11:07:52 [netgear] [0] error getting traffic meter info2019-10-17 11:07:05 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 11:06:08 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 10:57:47 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 10:46:47 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } signal_strength t@2019-10-17 10:45:47 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } signal_strength t@2019-10-17 10:44:58 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } signal_strength t@2019-10-17 10:34:49 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 10:32:57 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 10:32:57 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 10:26:46 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 10:24:47 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Failed to login2019-10-17 10:06:56 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: read ECONNRESET2019-10-17 10:03:45 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 10:03:23 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: The connection was terminated while the message was still being sent2019-10-17 10:01:17 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 10:01:17 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 09:58:59 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 09:58:59 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 09:54:00 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 09:50:34 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 09:50:34 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 09:48:47 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 09:48:47 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 09:47:02 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: Failed to login2019-10-17 09:46:01 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } signal_strength t@2019-10-17 09:44:43 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } signal_strength t@2019-10-17 09:44:02 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 09:30:53 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } signal_strength t@2019-10-17 09:29:43 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } signal_strength t@2019-10-17 09:29:17 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 09:28:18 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 09:26:52 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 09:25:58 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 09:23:04 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefined2019-10-17 09:23:04 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } download_speed undefined2019-10-17 09:19:44 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 09:17:11 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 09:12:58 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 09:10:57 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 08:58:50 [err] [ManagerDrivers] [netgear] [0] updateRouterDeviceState error: socket hang up2019-10-17 08:56:27 [attached_device] [1] { Error: invalid_type at Remote IPC Process message: 'invalid_type' } upload_speed undefinedBeantwoordenDoorsturen |   | BeantwoordenDoorsturen |   |  
-- | -- | -- | -- | --
  | BeantwoordenDoorsturen

**Comment by gruijter** [comment]
Caused by buggy R7000 firmware. You need to do a PTP (power cycle) of the R7000. Should occur less often in app v3.0.2 due to disabled log retrieval.
