### ISSUE TITLE
Beta not installeble

### ISSUE THREAD

**Issue by mho747** [gruijter/com.gruijter.netgear#37]
Hi, i have by accident upgraded the app. Unfortunately beta is replaced by orginal 2.5.3 version. I was a happy user of the beta but dont know how to install beta agian. Can you help out how to do?

Keep up the good work! Thanks in advance

**Comment by gruijter** [comment]
https://homey.app/a/com.gruijter.netgear/test

**Comment by mho747** [comment]
Dank je wel!
Super gaaf.
Wordt ren update nu ook vanzelf aangeboden?

Fijne dag

Martijn van Hoorn

**Comment by gruijter** [comment]
I will soon promote the test version to stable. Updates will then be pushed automatically, if you selected auto-update in Homey.
