### ISSUE TITLE
App keeps disconnecting

### ISSUE THREAD

**Issue by jabroersen** [gruijter/com.gruijter.netgear#38]
Hi,

The Netgear app keeps disconnecting...once I do a cold reboot (power off-5+min-power on) it reconnects for a while but after an hour or so, it disconnects with an login error again...can you assist?

These are my test results:
========== STARTING TEST ==========
Node version: v8.16.0
Netgear package version: 3.9.7
OS: linux 4.14.15-g3c513a6eca
Info: Homey fw:3.2.0 app: 3.0.4
t = 0
trying to auto discover Netgear routers...
[{Firmware:V1.2.0.62_1.0.1WW,RegionTag:R6800_WW,Region:WW,Model:R6800,InternetConnectionStatus:UP,ParentalControlSupported:1,SOAPVersion:3.21,ReadyShareSupportedLevel:29,XCloudSupported:1,LoginMethod:2.0,isBlankState:0,host:192.168.1.1,port:5000}]
t = 3.707
trying to login...
{message:Failed to login}
{host:192.168.1.1,port:5000,tls:false,username:admin,password:*****,timeout:18000,sessionId:A7D88AE69687E58D9A00,loggedIn:false,configStarted:false,soapVersion:3,loginMethod:2.22,guestWifiMethod:{},lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<SOAP-ENV:Envelope\r\n   xmlns:SOAP-ENV=\http://schemas.xmlsoap.org/soap/envelope/\\r\n   SOAP-ENV:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\>\r\n<SOAP-ENV:Body>\r\n\t<m:SOAPLoginResponse\r\n      xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceConfig:1\>\r\n  </m:SOAPLoginResponse>\r\n   <ResponseCode>503</ResponseCode>\r\n</SOAP-ENV:Body>\r\n</SOAP-ENV:Envelope>\r\n}

**Comment by gruijter** [comment]
https://github.com/gruijter/com.gruijter.netgear/issues/36#issuecomment-551015048

Check this link and try the suggested settings in Homey

**Comment by jabroersen** [comment]
Unfortunately same result


On 16 Dec 2019, at 20:27, gruijter <notifications@github.com> wrote:

﻿

#36 (comment)<https://github.com/gruijter/com.gruijter.netgear/issues/36#issuecomment-551015048>

Check this link and try the suggested settings in Homey

**Comment by gruijter** [comment]
> and always do a PTP of the router after changing these settings!

Did you PTP the router too?

**Comment by jabroersen** [comment]
Yes...before adding the router in homey I cold booted the router and homey, after adding the router, at the point of the popup, i cold booted my router, after it was up again I pressed OK on the open screen in homey, then I rebooted homey.

Same behavour as before, it works for an hour or two, then the login failer error



On 17 Dec 2019, at 18:18, gruijter <notifications@github.com<mailto:notifications@github.com>> wrote:


and always do a PTP of the router after changing these settings!

Did you PTP the router too?

**Comment by gruijter** [comment]
Mmh, thats too bad 😯

Maybe you can try doing a router test right after the ptp, and post the result here so I can check if I see anything weird from the test response.

**Comment by jabroersen** [comment]
Thnx for helping out! Here are the results :) :

========== STARTING TEST ==========
Node version: v8.16.0
Netgear package version: 3.9.7
OS: linux 4.14.15-g3c513a6eca
Info: Homey fw:3.2.0 app: 3.0.4
t = 0
trying to auto discover Netgear routers...
[{Firmware:V1.2.0.62_1.0.1WW,RegionTag:R6800_WW,Region:WW,Model:R6800,InternetConnectionStatus:UP,ParentalControlSupported:1,SOAPVersion:3.21,ReadyShareSupportedLevel:29,XCloudSupported:1,LoginMethod:2.0,isBlankState:0,host:192.168.1.1,port:5000}]
t = 4.222
trying to login...
login method: 2
t = 4.329
trying to getInfo...
{ModelName:R6800,Description:Netgear Smart Wizard 3.0, specification 0.8 version,SerialNumber:**********,Firmwareversion:V1.2.0.62,SmartAgentversion:3.0,FirewallVersion:ACOS NAT-Netfilter v1.0.0.1 (Linux cone NAT Hot Patch 06/21/2010),VPNVersion:N/A,OthersoftwareVersion:1.0.1,Hardwareversion:R6800,Otherhardwareversion:N/A,FirstUseDate:Tuesday, 10 December 2019 19:57:26,DeviceName:R6800,FirmwareDLmethod:Null,FirmwareLastChecked:2019_12.18_9:50:41,DeviceMode:0}
t = 4.407
trying to get System Uptime (hh:mm:ss)...
socket hang up
{lastResponse:{message:socket hang up,code:ECONNRESET}}
{}
t = 5.208
trying to getSystemInfo...
socket hang up
{lastResponse:{message:socket hang up,code:ECONNRESET}}
{}
t = 5.268
trying to get supportFeatures...
{OpenDNSParentalControl:1.0,AccessControl:1.0,SpeedTest:2.0,GuestNetworkSchedule:1.0,SmartConnect:2.0,AttachedDevice:2.0,NameNTGRDevice:1.0,TimeZone:2.0,MaxMonthlyTrafficLimitation:4095000000,SupportXMLEncoded:1.0,TCAcceptance:1.0}
t = 5.339
trying to get the Device configuration...
{BlankState:0,NewBlockSiteEnable:0,NewBlockSiteName:0,NewTimeZone:+01,NewDaylightSaving:0}
t = 5.414
trying to get the LAN configuration...
{NewLANSubnet:255.255.255.0,NewLANIP:192.168.1.1,NewDHCPEnabled:1,NewWANLAN_Subnet_Match:1,NewLANMACAddress:78D29469C6AB}
t = 6.18
trying to get the WAN configuration...
{NewEnable:1,NewConnectionType:DHCP,NewExternalIPAddress:192.168.2.15,NewSubnetMask:255.255.255.0,NewAddressingType:DHCP,NewDefaultGateway:192.168.2.254,NewMACAddress:78D29469C6AD,NewMACAddressOverride:0,NewMaxMTUSize:1500,NewDNSEnabled:1,NewDNSServers:192.168.2.254}
t = 6.295
trying to get Parental Control Status...
Parental Control Enabled: false
t = 6.87
trying to get Qos Status...
Qos Enabled: false
t = 7.665
trying to get Qos Bandwidth options...
{newUplinkBandwidth:0,newDownlinkBandwidth:0,enabled:1}
t = 7.726
trying to get Device Access Control Status...
Block Device Enabled: true
t = 7.787
trying to get attachedDevices method 1...
Number of attached devices: 16
First attached device: {\IP\:\192.168.1.30\,\Name\:\--\,\MAC\:\78:28:CA:07:4E:50\,\ConnectionType\:\wireless\,\Linkspeed\:54,\SignalStrength\:91,\AllowOrBlock\:\Allow\}
t = 14.733
trying to get attachedDevices method 2...
Number of attached devices: 16
First attached device: {\IP\:\192.168.1.30\,\Name\:\--\,\NameUserSet\:false,\MAC\:\78:28:CA:07:4E:50\,\ConnectionType\:\2.4GHz\,\SSID\:\JABWIFI_nomap\,\Linkspeed\:54,\SignalStrength\:91,\AllowOrBlock\:\Allow\,\Schedule\:false,\DeviceTypeUserSet\:false,\Grouping\:0,\SchedulePeriod\:0}
t = 16.396
trying to get available and selected WiFi channels...
Available channels 2.4G-1: Auto,1,2,3,4,5,6,7,8,9,10,11,12,13
2.4G-1 channel is not available
Available channels 5.0G-1: Auto,36,40,44,48,52,56,60,64,100,104,108,112,116,120,124,128
5.0G-1 channel is not available
Available channels 5.0G-2: Auto,36,40,44,48,52,56,60,64,100,104,108,112,116,120,124,128
5.0G-2 channel is not available
t = 17.633
trying to get Smart Connect Status...
Smart Connect Enabled: false
t = 18.78
trying to get Guest Wifi Status...
2.4G-1 Guest wifi enabled: false
5.0G-1 Guest wifi is not available, method: 1
5.0G-2 Guest wifi is not available
t = 19.852
trying to get the Traffic Meter Enabled Status...
Traffic Meter Enabled: true
t = 19.916
trying to get the Traffic Meter Options...
{newControlOption:No Limit,newNewMonthlyLimit:0,restartHour:0,restartMinute:0,restartDay:1}
t = 19.988
trying to get trafficMeter...
{newTodayUpload:1142.4,newTodayDownload:4219.5,newMonthUpload:16305.83,newMonthDownload:50205.42}
t = 20.074
trying to check newFirmware...
check newFirmware method: 2
{currentVersion:V1.2.0.62,newVersion:,releaseNote:}
t = 22.923
trying to get router logs...
socket hang up
{lastResponse:{message:socket hang up,code:ECONNRESET}}
last log: undefined
t = 22.989
trying to logout...
{host:192.168.1.1,port:5000,tls:false,username:admin,password:*****,timeout:18000,sessionId:A7D88AE69687E58D9A00,cookie:true,loggedIn:false,configStarted:false,soapVersion:3,loginMethod:2,checkNewFirmwareMethod:2,guestWifiMethod:{get50_1:1},lastResponse:...}
t = 23.05
test finished with 3 errors



On 17 Dec 2019, at 19:01, gruijter <notifications@github.com> wrote:

﻿

Mmh, thats too bad 😯

Maybe you can try doing a router test right after the ptp, and post the result here so I can check if I see anything weird from the test response.

**Comment by gruijter** [comment]
I don't see much weirdness, only that for certain commands your Netgear just decides to 'hang up'. This is caused by firmware instability. Maybe an older version fw is more stable, but in general I do not advise people to downgrade their router firmware due to possible security vulnerabilities.

I do see however that you seem to be using the Netgear behind another router. Did you configure this correctly? If you do not set this up correctly it can cause network issues that can also lead to the Netgear hanging up.

**Comment by jabroersen** [comment]
Thnx for looking in to it.

I think I set it up correctly…the Internet modem/router is set to DHCP, WiFi of. The Netgear router has a static IP adress, within the DHCP range (reserved) and has DHCP server on within another range (192.168.2.x for Internet and 192.168.1.x for WiFi)…

**Comment by gruijter** [comment]
Im not a network expert myself, but it sounds like you know what you are doing 😉

Not much more I can do for you right now unfortunately. When you do try other firmware and/or network setup, let me know if that makes a difference.

**Comment by jabroersen** [comment]
Thnx! I’ll uninstall the app for no wand await another firmware update to try again 😉

**Comment by gruijter** [comment]
New Firmware released by Netgear introduced new problems in parsing attached devices. I have made a new release that can manage these firmware issues, and also fixes some other minor issues.

Netgear package 3.9.9. Fixed fw update on R7000. Fix parsing of <unknown> devices. Fix delete Devicelist. Selectable login method added.

Get it here:
https://homey.app/a/com.gruijter.netgear/test/

Try this version and let me know what happens. You can also try setting the login method to 'Old' in the Homey device settings.
