### ISSUE TITLE
Netgear R8000 - Connection problem after ~1 day

### ISSUE THREAD

**Issue by KevinJoss** [gruijter/com.gruijter.netgear#39]
Hello Gruijter,

First of all, I would like to thank you for your application. This one is very good and useful with Homey :) 

I explain my problem.
When I connect your application to my Netgrar R8000 router, everything is working at beginning. 

This is the log : 
========== STARTING TEST ==========
Node version: v8.16.0
Netgear package version: 3.9.7
OS: linux 4.14.15-g3c513a6eca
Info: Homey fw:3.2.0 app: 3.0.4
t = 0
trying to auto discover Netgear routers...
[{Firmware:V1.0.4.46_10.1.63,RegionTag:R8000_WW,Region:ww,Model:R8000,InternetConnectionStatus:Up,ParentalControlSupported:1,CircleEnabled:0,OpenDNSEnabled:0,SOAPVersion:3.21,LoginMethod:2.0,ReadyShareSupportedLevel:29,XCloudSupported:1,SmartNetworkSupported:0,DeviceMode:0,host:192.168.1.1,port:5000}]
t = 3.624
trying to login...
login method: 2
t = 4.733
trying to getInfo...
{ModelName:R8000,Description:Netgear Smart Wizard 3.0, specification 0.7 version,SerialNumber:**********,Firmwareversion:V1.0.4.46,SmartAgentversion:3.0,FirewallVersion:ACOS NAT-Netfilter v3.0.0.5 (Linux Cone NAT Hot Patch 06/11/2010),VPNVersion:N/A,OthersoftwareVersion:10.1.63,Hardwareversion:R8000,Otherhardwareversion:N/A,FirstUseDate:Friday, 31 May 2019 09:32:57,DeviceName:R8000,FirmwareDLmethod:Null,FirmwareLastUpdate:Null,FirmwareLastChecked:Null,DeviceMode:0}
t = 4.873
trying to get System Uptime (hh:mm:ss)...
 2 days 05:06:51
t = 4.938
trying to getSystemInfo...
{NewCPUUtilization:20,NewPhysicalMemory:256,NewMemoryUtilization:60,NewPhysicalFlash:128,NewAvailableFlash:128}
t = 5.04
trying to get supportFeatures...
{DynamicQoS:1.0,OpenDNSParentalControl:1.0,CircleParentalControl:2.0,MaxMonthlyTrafficLimitation:4095000000,AccessControl:1.0,SpeedTest:2.0,BitDefenderSecurity:1.0,GuestNetworkSchedule:1.0,TCAcceptance:1.0,SmartConnect:2.0,AttachedDevice:2.0,NameNTGRDevice:1.0}
t = 5.152
trying to get the Device configuration...
{BlankState:0,NewBlockSiteEnable:0,NewTimeZone:+1,NewDaylightSaving:0}
t = 5.325
trying to get the LAN configuration...
{NewLANSubnet:255.255.255.0,NewWANLAN_Subnet_Match:0,NewLANMACAddress:3C37867A00A1,NewLANIP:192.168.1.1,NewDHCPEnabled:true}
t = 10.785
trying to get the WAN configuration...
{NewEnable:1,NewConnectionType:DHCP,NewExternalIPAddress:80.219.12.43,NewSubnetMask:255.255.252.0,NewAddressingType:DHCP,NewDefaultGateway:80.219.12.1,NewMACAddress:3C37867A00A2,NewMACAddressOverride:0,NewMaxMTUSize:1500,NewDNSEnabled:1,NewDNSServers:62.2.24.162 62.2.17.61 62.2.24.158 }
t = 10.833
trying to get Parental Control Status...
Parental Control Enabled: false
t = 11.003
trying to get Qos Status...
Qos Enabled: true
t = 11.043
trying to get Qos Bandwidth options...
{newUplinkBandwidth:10.89,newDownlinkBandwidth:104.88,enabled:2}
t = 11.085
trying to get Device Access Control Status...
Block Device Enabled: true
t = 11.136
trying to get attachedDevices method 1...
Number of attached devices: 9
First attached device: {\IP\:\192.168.1.2\,\Name\:\STOCKY\,\MAC\:\00:08:9B:E2:25:AD\,\ConnectionType\:\wired\,\Linkspeed\:null,\SignalStrength\:100,\AllowOrBlock\:\Allow\}
t = 14.343
trying to get attachedDevices method 2...
Number of attached devices: 9
First attached device: {\IP\:\192.168.1.2\,\Name\:\STOCKY\,\NameUserSet\:true,\MAC\:\00:08:9B:E2:25:AD\,\ConnectionType\:\wired\,\SignalStrength\:100,\AllowOrBlock\:\Allow\,\Schedule\:false,\DeviceType\:33,\DeviceTypeUserSet\:true,\Upload\:0,\Download\:0,\QosPriority\:2,\DeviceModel\:\--\,\Grouping\:0,\SchedulePeriod\:0}
t = 17.624
trying to get available and selected WiFi channels...
Available channels 2.4G-1: Auto,1,2,3,4,5,6,7,8,9,10,11,12,13
selected channel 2.4G-1: Auto
Available channels 5.0G-1: 36,40,44,48,52,56,60,64,100,104,108,112,116,120,124,128
selected channel 5.0G-1: Auto
Available channels 5.0G-2: 36,40,44,48,52,56,60,64,100,104,108,112,116,120,124,128
5.0G-2 channel is not available
t = 17.876
trying to get Smart Connect Status...
Smart Connect Enabled: false
t = 18.045
trying to get Guest Wifi Status...
2.4G-1 Guest wifi enabled: true
5.0G-1 Guest wifi enabled: false, method: 2
5.0G-2 Guest wifi enabled: false
t = 18.169
trying to get the Traffic Meter Enabled Status...
Traffic Meter Enabled: true
t = 18.209
trying to get the Traffic Meter Options...
{newControlOption:No Limit,newNewMonthlyLimit:0,restartHour:0,restartMinute:0,restartDay:1}
t = 18.254
trying to get trafficMeter...
{newTodayUpload:36.51,newTodayDownload:1049,newMonthUpload:11151,newMonthDownload:186465}
t = 18.3
trying to check newFirmware...
check newFirmware method: 2
{currentVersion:1.0.4.46,newVersion:,releaseNote:}
t = 23.589
trying to get router logs...
last log: [DoS attack: Smurf] attack packets in last 20 sec from ip [91.134.139.255], Sunday, Dec 29,2019 16:51:56
t = 23.675
trying to logout...
{host:192.168.1.1,port:5000,tls:false,username:admin,password:*****,timeout:18000,sessionId:A7D88AE69687E58D9A00,cookie:true,loggedIn:false,configStarted:false,soapVersion:3,loginMethod:2,checkNewFirmwareMethod:2,guestWifiMethod:{get50_1:2},lastResponse:...}
t = 23.714
test finished without errors :)

Your application works but after maybe 15h - 30h, your application writes "failed to login" and the official android app of Nighthawk doesnt work anymore.... the only solution is to reboot my router to restart everything. 
Here is the log of test button when I have the problem : (when I discover the router and the problem is here the SAOP port is not found automatically)
========== STARTING TEST ==========
Node version: v8.16.0
Netgear package version: 3.9.7
OS: linux 4.14.15-g3c513a6eca
Info: Homey fw:3.2.0 app: 3.0.4
t = 0
trying to auto discover Netgear routers...
[{Firmware:V1.0.4.46_10.1.63,RegionTag:R8000_WW,Region:ww,Model:R8000,InternetConnectionStatus:Up,ParentalControlSupported:1,CircleEnabled:0,OpenDNSEnabled:0,SOAPVersion:3.21,LoginMethod:2.0,ReadyShareSupportedLevel:29,XCloudSupported:1,SmartNetworkSupported:0,DeviceMode:0,host:192.168.1.1}]
t = 3.45
trying to login...
{message:Failed to login}
{host:192.168.1.1,port:5000,tls:false,username:admin,password:*****,timeout:18000,sessionId:A7D88AE69687E58D9A00,loggedIn:false,configStarted:false,soapVersion:3,loginMethod:2.22,checkNewFirmwareMethod:2,guestWifiMethod:{get50_1:2},lastResponse:{message:connect ECONNREFUSED 192.168.1.1:5000,code:ECONNREFUSED}}

I hope you will understand my problem and find the solution. Because its annoying to restart all the time my router (now I use your action to restart it before the problem appears). 

Many thanks one more time. 
Happy new year in advance ! 

Kevin

**Comment by gruijter** [comment]
New Firmware released by Netgear introduced new problems in parsing attached devices. I have made a new release that can manage these firmware issues, and also fixes some other minor issues.

Netgear package 3.9.9. Fixed fw update on R7000. Fix parsing of <unknown> devices. Fix delete Devicelist. Selectable login method added.

Get it here:
https://homey.app/a/com.gruijter.netgear/test/

Let me know if this works :)

**Comment by KevinJoss** [comment]
Hi Gruijter,

Thanks for all updates you did for your application ! It's always great to have a sustained application :)

I come back about my problem of "Failed to login after few hours". Now i've more time to look for why i've this problem (with the current situation....). To summary, i still have exatly the same problem. But like i said the last time, i've programmed an auto reboot of my R8000 every 6 hours if no important device is running. But sometimes, if i'm on my comupter i don't restart the router end at this end of the day, your plugin is "Failed to login". Like before, when your plugin can't connect, the Nighthawk application can't either. 

While these days i try different settings for login method (old/new) and device list aslo (old/new) but the same result. I also try to disable all additionnal report functionnality.

But one thing i'm sure is if i complety disable this application, i don't have smurf attack from Homey IP (192.168.1.4).
If you look the time between different smurf from homey ip, it's always 15 minutes. Maybe it will help you ?

```
[Admin login] from source 192.168.1.41, Tuesday, Mar 31,2020 18:18:06
[DoS attack: Smurf] attack packets in last 20 sec from ip [192.168.1.4], Tuesday, Mar 31,2020 18:16:35
[Time synchronized with NTP server] Tuesday, Mar 31,2020 18:14:46
[Internet connected] IP address: 192.168.0.2, Tuesday, Mar 31,2020 18:13:56
[DoS attack: Smurf] attack packets in last 20 sec from ip [192.168.1.4], Tuesday, Mar 31,2020 18:01:35
```

i also try to reset factory my router and restore the backup. But same problem after it.

Of course it's not a big problem, but it could be great if we success to find it together :D !
Many thanks one more time for your work.

Kevin Joss

**Comment by KevinJoss** [comment]
Hi Gruijter,

Between yesterday and today i tried something new. I completely disabled your application on Homey. I know like this, there isn't SAOP problem with the router. But i've created a HomeAssistant docker with the NetGear application on it and add the tracker for all my devices. And, on day after, same problem.... the SAOP connection is down. The Nighthawk app isn't able to connect to the router (even the rest is okay, wifi, wan, web interface, etc...).
(https://www.home-assistant.io/integrations/netgear/)

So in fact, it's exactly the same problem after approximatively the same time.

It seems not linked to your application inside Homey. I don't know if you use the same API as HomeAssistant ??? I think yes. So the problem can come from the API or from the firmware of my router ? Maybe it's buggy....

What do you think ?

**Comment by gruijter** [comment]
HA is using a python version of the Netgear API wrapper. I am using a nodejs version that I built myself. So they are seperate code builds. But the py-netgear community  and I have exchanged ideas and info on the Netgear SOAP interface (I put a huge amount of time in reverse engineering the protocol, since Netgear is not publishing the SOAP interface specs).

In short: your findings with HA is another confirmation of my suspicion that the Netgear firmware is buggy. The router needs a PTP on regular basis. And by polling the SOAP interface (like HA and Homey do) the router needs a PTP more frequently. In case of the R8000 apparently every day.

I would guess that if you use their own Nighthawk app to get the attached devices every minute, the router would also hang after a day. Would be great if you could try that 😨🤣

With newer router firmware it actually has become worse. So I am hoping for a new fw release by Netgear that is more stable. Maybe you can write to them complaining about router hangups when using the Nighthawk app often?

**Comment by KevinJoss** [comment]
I thought that there wasn't an official API from Netgear, because i didn't find anything on internet. So you did an amazing job man ;) 
Yes now it's confirmed it directly linked to the Netgear firmware. I increased all time (on/off) polling at many minutes and disable all other features (internet speed, internet check, etc...). Maybe the time will be longer and like that, i avoid to restart to many times.

Ahahaha I could test to use the Nighthawk app each minute while an entire day :) ^^ but yes i think it should be the same...

Of course i'll send an complain to Netgear about the stability of the APP... More we are to speak about it, better the result could be ! 

I think you can consider this case resloved because you can't do anything else.

Ah, one more thing, even i disabled your app, I still have DoS smurf attack on the log of my router from the IP of Homey... So forget that i said.

Have a good day !
