### ISSUE TITLE
unhandledRejection!

### ISSUE THREAD

**Issue by schononas** [gruijter/com.gruijter.netgear#4]
Hi
The only thing in the logg is this message, and I get a new one every time Homey tries to poll the router.

Router info:
Firmware=V1.0.2.60_10.0.44 RegionTag=R6400v2_WW Region=ww Model=R6400v2 InternetConnectionStatus=Up ParentalControlSupported=1 CircleEnabled=0 OpenDNSEnabled=0 SOAPVersion=3.21 ReadyShareSupportedLevel=29 XCloudSupported=1 LoginMethod=2.0 DeviceMode=0

Error:
2018-10-07 23:07:39 [err] [MyApp] unhandledRejection! TypeError: Cannot read property '0' of undefined at parseString (/node_modules/netgear/netgear.js:418:97) at Parser. (/node_modules/xml2js/lib/parser.js:303:18) at emitOne (events.js:116:13) at Parser.emit (events.js:211:7) at SAXParser.onclosetag (/node_modules/xml2js/lib/parser.js:261:26) at emit (/node_modules/sax/lib/sax.js:624:35) at emitNode (/node_modules/sax/lib/sax.js:629:5) at closeTag (/node_modules/sax/lib/sax.js:889:7) at SAXParser.write (/node_modules/sax/lib/sax.js:1436:13) at Parser.exports.Parser.Parser.parseString (/node_modules/xml2js/lib/parser.js:322:31)

**Comment by gruijter** [comment]
Hi @schononas , thx for reporting this. It seems to be an xml parsing error. I know that netgear uses xml that is not compliant to the standard. Illegal characters will choke the parsing. I have seen before that a connected device uses weird characters as device name, like heos is using the '&'. Try disconnecting all ip devices, except homey and your phone, and see if you still have this error.
I dont have a r6400 myself, so its really hard for me to debug this error.

**Comment by schononas** [comment]
Hi again, even if I disconnect all other devices I get the same error as described before. What can I do to help you fix this problem. I really want to get this app working with my router so if you need to connect with teamwiever and debug or something I can be at help! I'm a programmer myself but not this type of programming thoe so hopefully I will be able to help you!

**Comment by gruijter** [comment]
Yes, a teamviewer session would definitely be usefull. I would then however need access to a windows laptop, and would need to install some software on that machine (node, atom, and maybe some other tools). And I would need access to your router, including admin password. But if all that is ok for you we could try this. Drop me an email or better pm me on athom slack (gruijter)

**Comment by schononas** [comment]
I have sent you a pm on slack

**Comment by gruijter** [comment]
In the meantime.... Maybe you can try installing the new version from GitHub. This version is waiting approval in the appstore for almost 2 weeks now (Athom is very busy doing V2.0 of Homey firmware). But I made some changes in there that might already solve the problem you are experiencing.

You can find instructions on how to 'sideload' apps here:
https://developer.athom.com/docs/apps/tutorial-Getting%20Started.html

Just replace step 4 (create the app) with you downloading the Github version.

**Comment by gruijter** [comment]
Fixed in v 2.0.8 😎
