### ISSUE TITLE
"Device is online (mac)" not working

### ISSUE THREAD

**Issue by lolpold** [gruijter/com.gruijter.netgear#42]
Getting the error "The netgear device is unknown or not ready" when using the "Device is online (mac)" under "And...". After 10 seconds the error "Network request failed" pops up.
[log.txt](https://github.com/gruijter/com.gruijter.netgear/files/4203757/log.txt)

I can see the mac id's in this list here, so I know that they are present.
[attachhed device list.txt](https://github.com/gruijter/com.gruijter.netgear/files/4203767/attachhed.device.list.txt)

All the new features are set to "Auto" and the reporting is set to "No".
Getting the same error with IP option.

**Comment by lolpold** [comment]
Getting the same error with IP option.

**Comment by gruijter** [comment]
Thx for reporting!

Do you mean this happens when creating the flow, or when using the flow? Are you maybe creating the flow with the web inteface? Then try to create it via the Homey app.

Secondly: why do you use the 'old' way of doing presence detection? There is a new, much better way. See the forum: https://community.athom.com/t/netgear-router-app-network-control-presence-detection-energy-monitoring/2259/235

**Comment by lolpold** [comment]
The flow has worked like a charm for many weeks. The issue started when I updated my Homey to version 4.0.0. I am using it in this fashion: https://homey.app/f/iCzg31
I miss the option to have "Device is offline/online" under "And...".
Because I only want the flow to work when I am the first person to be at home. So that the flow doesn't start when my wife is already at home. 
If you have a better way for this I am all ears :)

**Comment by gruijter** [comment]
Ah, I see. I replicated your flow, and I get the same issue when running it. This is a bug in my app then. Maybe I have some time this weekend to look into it.

**Comment by lolpold** [comment]
Some times you don't see the forest because of all the trees... 
I found a better way of doing this with the Logic variable "Device connected".
https://homey.app/f/Td8C31

There are so many ways of doing the same thing, so you get stuck in the way you first learned it. 
So for my sake this issue can be closed. 
Thank you as always for listening to my rambles :)

**Comment by gruijter** [comment]
Argh, I knew this solution was out there. But also I couldn't find it anymore. Glad that you did!

I'll keep the issue open until I fixed the bug though. Have a good weekend

**Comment by gruijter** [comment]
Should be fixed

**Comment by Nnk2** [comment]
It is. Thank you!

------------------------
Sent from iPhone
------------------------
