### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by RainierM** [gruijter/com.gruijter.netgear#43]
I have the same problem with an R7000P as described in incident https://github.com/gruijter/com.gruijter.netgear/issues/41 
It used to work fine for months, but since the latest update is got 'screwed'
The router is on the latest firmware V1.3.1.64 in access point mode, but login fails, even after reboots of things like 'homey' and the router.
Tests shows no problems and the password is 100% correct
PS. Running on the app version 3.0.8 
Homey is now on 4.0, but before with 3.x I had the same problem.
Also tried things like 'login method' old/new/auto

**Comment by kjettern** [comment]
+1 here. I was going to turn on my guest network, but then I realised that there was no access to my netgear x6.. I've had no problems before. Password is the same. When running the test, everything is reporting OK.
