### ISSUE TITLE
Connection after a few seconds lost

### ISSUE THREAD

**Issue by labarten** [gruijter/com.gruijter.netgear#44]
========== STARTING TEST ==========
Node version: v8.16.0
Netgear package version: 4.0.3
OS: linux 4.14.15-g3c513a6eca
Info: Homey fw:4.0.0 app: 3.0.9
t = 0
trying to auto discover Netgear routers...
[{Firmware:V1.0.9.88_10.2.88,RegionTag:R7000_WW,Region:ww,Model:R7000,InternetConnectionStatus:Up,ParentalControlSupported:1,CircleEnabled:0,OpenDNSEnabled:0,SOAPVersion:3.21,LoginMethod:2.0,ReadyShareSupportedLevel:29,XCloudSupported:1,DeviceMode:0,host:192.168.1.1}]
t = 3.776
trying to login using method 1...
method 1 failed.
trying to login using method 2...
method 2 failed.
trying to login using auto method...
{message:Failed to login}
{host:192.168.1.1,port:5000,tls:false,username:admin,password:*****,timeout:18000,sessionId:A7D88AE69687E58D9A00,loggedIn:false,configStarted:false,soapVersion:3,loginMethod:2,guestWifiMethod:{},lastResponse:{message:connect ECONNREFUSED 192.168.1.1:5000,code:ECONNREFUSED}}

Yesterday my homey installed and direct with the netgear app, with a lot off effort finally the netgear app works. Until today now.... i have looked in several closed issues but non of them worked...

**Comment by fspaan** [comment]
Same here, device R8000.

**Comment by labarten** [comment]
I got still the same error every time, when i passed to login and start some settings like detect a smartphone on the internet. It works for 10 mins. After that i were kicked out. And can’t login with the nighthawk app or homey app. I have to restart the router before i can login on homey and nighthawk.

**Comment by edwinvdpol** [comment]
I have the same problem.

It looks like my router (R6400v2) is detecting an DoS attack, and prevents Homey to login:

`[DoS attack: Smurf] attack packets in last 20 sec from ip [192.168.1.1], Thursday, Sep 10,2020 09:31:58
[DoS attack: Smurf] attack packets in last 20 sec from ip [192.168.1.1], Thursday, Sep 10,2020 09:16:58
[DoS attack: Smurf] attack packets in last 20 sec from ip [192.168.1.1], Thursday, Sep 10,2020 09:01:58`

I tried both `New` and `Old` login, both have the same outcome.

**Firmware**
V1.0.4.98_10.0.71

**Comment by gruijter** [comment]
Caused by unstable router firmware. PTP of the router solves it temporarily
