### ISSUE TITLE
New router firmware trigger

### ISSUE THREAD

**Issue by AdyRock** [gruijter/com.gruijter.netgear#45]
The 'New router firmware available' trigger firs every few seconds even though the router firmware is up to date.
![Screenshot_20200417-130425_Homey](https://user-images.githubusercontent.com/38184396/79615783-6ce03100-80fb-11ea-8e44-7f7b283b998e.jpg)

**Comment by AdyRock** [comment]
========== STARTING TEST ==========
Node version: v12.16.1
Netgear package version: 4.0.4
OS: linux 4.14.15-g3c513a6eca
Info: Homey fw:4.2.0-rc.2 app: 3.1.0
t = 0
trying to auto discover Netgear routers...
[{Firmware:V1.0.5.12WW,RegionTag:R9000_WW,Region:ww,Model:R9000,InternetConnectionStatus:Up,ParentalControlSupported:1,SOAPVersion:3.34,ReadyShareSupportedLevel:29,XCloudSupported:1,isBlankState:0,LoginMethod:2.0,host:192.168.1.1,port:80},{Firmware:V1.0.1.206WW,Region:ww,Model:EX8000,SOAPVersion:3.61,isBlankState:0,LoginMethod:2.0,host:192.168.1.12,port:80}]
t = 132.772
trying to login using method 1...
method 1 ok.
trying to login using method 2...
method 2 ok.
trying to login using auto method...
reported login method: 2
t = 138.081
trying to getInfo...
{Description:Netgear Smart Wizard 3.0, specification 1.6 version,SmartAgentversion:3.0,FirewallVersion:net-wall 2.0,OthersoftwareVersion:N/A,Otherhardwareversion:N/A,FirstUseDate:Sunday, 30 Sep 2007 01:10:03,DeviceMode:0,DeviceNameUserSet:false,ModelName:R9000,SerialNumber:**********,Firmwareversion:V1.0.5.12,Hardwareversion:R9000,DeviceName:R9000,FirmwareDLmethod:MANUAL,FirmwareLastUpdate:2020_2.9_16:18:48,FirmwareLastChecked:2020_4.17_22:52:35,DeviceModeCapability:0;1;2}
t = 138.142
trying to getSystemInfo...
{NewCPUUtilization:10,NewPhysicalMemory:32,NewMemoryUtilization:22,NewPhysicalFlash:128,NewAvailableFlash:128.06}
t = 139.984
trying to get supportFeatures...
{DynamicQoS:1.0,OpenDNSParentalControl:1.0,AccessControl:1.0,SpeedTest:2.0,GuestNetworkSchedule:1.0,TCAcceptance:1.0,DeviceTypeIdentification:1.0,AttachedDevice:2.0,NameNTGRDevice:1.0,SmartConnect:2.0,MaxMonthlyTrafficLimitation:4095000000,SupportXMLEncoded:1.0,TimeZone:3.1}
t = 140.031
trying to get the LAN configuration...
{NewLANSubnet:255.255.255.0,NewWANLAN_Subnet_Match:0,NewLANMACAddress:A040A060081E,NewLANIP:192.168.1.1,NewDHCPEnabled:true}
t = 140.076
trying to get the WAN configuration...
{NewEnable:1,NewConnectionType:PPPoE,NewAddressingType:PPPoE,NewMACAddress:A040A060081F,NewMACAddressOverride:0,NewDNSEnabled:1,NewExternalIPAddress:212.159.74.123,NewSubnetMask:255.255.255.255,NewDefaultGateway:212.159.74.123,NewMaxMTUSize:1492,NewDNSServers:212.159.6.9 212.159.6.10}
t = 140.179
trying to get the Traffic Meter Enabled Status...
Traffic Meter Enabled: true
t = 140.218
trying to get trafficMeter...
{newTodayUpload:4560,newTodayDownload:9415,newMonthUpload:121923,newMonthDownload:130807}
t = 140.257
trying to get the Traffic Meter Options...
{newControlOption:No Limit,newNewMonthlyLimit:0,restartHour:0,restartMinute:0,restartDay:1}
t = 140.305
trying to get System Uptime (hh:mm:ss)...
008:09:22
t = 140.347
trying to get the Device configuration...
{BlankState:0,NewBlockSiteEnable:0,NewBlockSiteName:0,NewTimeZone:0,NewDaylightSaving:1,TimeZoneOffset:0,TimeZoneState:2}
t = 140.393
trying to get Parental Control Status...
Parental Control Enabled: false
t = 140.912
trying to get Qos Status...
Qos Enabled: false
t = 140.97
trying to get Qos Bandwidth options...
{newUplinkBandwidth:17.01,newDownlinkBandwidth:74.32,enabled:2}
t = 141.031
trying to get available and selected WiFi channels...
Available channels 2.4G-1: Auto,1,2,3,4,5,6,7,8,9,10,11,12,13
selected channel 2.4G-1: 9
Available channels 5.0G-1: 36,40,44,48,52,56,60,64,100,104,108,112,116,120,124,128
selected channel 5.0G-1: 104
5.0G-2 channels are not available
5.0G-2 channel is not available
t = 141.342
trying to get Smart Connect Status...
Smart Connect Enabled: false
t = 142.101
trying to get router logs...
no response code from router
{lastResponse:<?xml version=.0 encoding=UTF-8?> <SOAP-ENV:Envelope    xmlns:SOAP-ENV=http://schemas.xmlsoap.org/soap/envelope/\r    SOAP-ENV:encodingStyle=http://schemas.xmlsoap.org/soap/encoding/> <SOAP-ENV:Body> </SOAP-ENV:Body> </SOAP-ENV:Envelope> }
last log: undefined
t = 142.221
trying to get Guest Wifi Status...
2.4G-1 Guest wifi enabled: true
5.0G-1 Guest wifi enabled: true, method: 1
5.0G-2 Guest wifi is not available
t = 149.875
trying to get Device Access Control Status...
Block Device Enabled: true
t = 149.967
trying to get attachedDevices method 1...
Number of attached devices: 41
First attached device:
{IP:192.168.1.21,Name:Cannon Printer,MAC:F4:81:39:20:E4:46,ConnectionType:wireless,Linkspeed:56,SignalStrength:58,AllowOrBlock:Allow}
t = 159.016
trying to get attachedDevices method 2...
Number of attached devices: 42
First attached device:
{NameUserSet:false,SignalStrength:58,AllowOrBlock:Allow,Schedule:false,DeviceTypeUserSet:false,QosPriority:4,DeviceModelUserSet:false,Grouping:0,SchedulePeriod:0,IP:192.168.1.21,Name:Cannon Printer,MAC:F4:81:39:20:E4:46,ConnectionType:2.4GHz,SSID:NETGEAR60,Linkspeed:56,DeviceType:30,Upload:0,Download:0,ConnAPMAC:a0:40:a0:60:08:1e}
t = 165.04
trying to check newFirmware...
check newFirmware method: 2
{currentVersion:V1.0.5.12,newVersion:V1.0.5.12,releaseNote:}
t = 173.726
trying to logout...
{host:192.168.1.1,port:80,tls:false,username:admin,password:*****,timeout:18000,sessionId:A7D88AE69687E58D9A00,cookie:true,loggedIn:false,configStarted:false,soapVersion:3,loginMethod:2,getAttachedDevicesMethod:2,checkNewFirmwareMethod:2,guestWifiMethod:{get50_1:1},lastResponse:...}
t = 174.08
test finished with 1 errors

**Comment by gruijter** [comment]
do you still have this problem?

**Comment by AdyRock** [comment]
Yep. Just checked and it's still the same. 
No big deal now as I have a new Draytek router and the Netgear is now just an access point. I will see if it can manage to do that and if it's still a box of .... then I will replace it completely.
