### ISSUE TITLE
No Serial No. Problem - getInfo - remove New in response

### ISSUE THREAD

**Issue by dokmadeinitaly** [gruijter/com.gruijter.netgear#46]
I recive this problem when i add my device:
No Serial Number.

**Comment by gruijter** [comment]
can you post the results of the compatibility test here? This can be started from the app settings page. Thx!

**Comment by dokmadeinitaly** [comment]
Here Is:

========== STARTING TEST ==========
Node version: v12.16.1
Netgear package version: 4.1.0
OS: linux 4.14.15-g3c513a6eca
Info: Homey fw:4.2.0 app: 3.2.0
t = 0
trying to auto discover Netgear routers...
[{Firmware:V1.0.0.15_1.0.1PE,RegionTag:D1500,Region:ww,Model:D1500,InternetConnectionStatus:Up,ParentalControlSupported:0,SOAPVersion:1.11,ReadyShareSupportedLevel:0,host:192.168.1.1,port:80}]
t = 19.011
trying to login using method 1...
method 1 ok.
trying to login using method 2...
method 2 failed.
trying to login using auto method...
reported login method: 1
t = 19.786
trying to getInfo...
{NewManufacturerName:NETGEAR,
Inc.,NewManufacturerOUI:00E04C,NewModelName:D1500,NewDescription:Realtek
ADSL
Router,NewProductClass:00000000-00000000,NewSerialNumber:A42B8C723B60,NewSoftwareVersion:V1.0.0.15_1.0.1PE,NewModemFirmwareVersion:4926de702,NewSpecVersion:TR-064
v1.0,NewUpTime:102282,SerialNumber:**********}
t = 20.116
trying to getSystemInfo...
HTTP request Failed. Status Code: 500
{lastResponse:500}
{}
t = 20.398
trying to get supportFeatures...
HTTP request Failed. Status Code: 500
{lastResponse:500}
{}
t = 21.037
trying to get the LAN configuration...
HTTP request Failed. Status Code: 500
{lastResponse:500}
{}
t = 21.277
trying to get the WAN configuration...
HTTP request Failed. Status Code: 500
{lastResponse:500}
{}
t = 22.852
trying to get the Traffic Meter Enabled Status...
HTTP request Failed. Status Code: 500
{lastResponse:500}
Traffic Meter Enabled: [object Object]
t = 23.398
trying to get trafficMeter...
HTTP request Failed. Status Code: 500
{lastResponse:500}
{}
t = 23.548
trying to get the Traffic Meter Options...
HTTP request Failed. Status Code: 500
{lastResponse:500}
{}
t = 23.787
trying to get System Uptime (hh:mm:ss)...
HTTP request Failed. Status Code: 500
{lastResponse:500}
{}
t = 24.112
trying to get the Device configuration...
HTTP request Failed. Status Code: 500
{lastResponse:500}
{}
t = 24.51
trying to get Parental Control Status...
HTTP request Failed. Status Code: 500
{lastResponse:500}
Parental Control Enabled: [object Object]
t = 25.11
trying to get Qos Status...
HTTP request Failed. Status Code: 500
{lastResponse:500}
Qos Enabled: [object Object]
t = 25.448
trying to get Qos Bandwidth options...
HTTP request Failed. Status Code: 500
{lastResponse:500}
{}
t = 25.825
trying to get available and selected WiFi channels...
2.4G-1 channels are not available
selected channel 2.4G-1: 8
5.0G-1 channels are not available
5.0G-1 channel is not available
5.0G-2 channels are not available
5.0G-2 channel is not available
t = 27.799
trying to get Smart Connect Status...
HTTP request Failed. Status Code: 500
{lastResponse:500}
Smart Connect Enabled: [object Object]
t = 28.659
trying to get router logs...
HTTP request Failed. Status Code: 500
{lastResponse:500}
last log: undefined
t = 28.985
trying to get Guest Wifi Status...
2.4G-1 Guest wifi enabled: false
5.0G-1 Guest wifi is not available, method: 1
5.0G-2 Guest wifi is not available
t = 30.161
trying to get Device Access Control Status...
HTTP request Failed. Status Code: 500
{lastResponse:500}
Block Device Enabled: [object Object]
t = 30.47
trying to get attachedDevices method 1...
HTTP request Failed. Status Code: 500
{lastResponse:500}
Number of attached devices: undefined
First attached device:
null
t = 30.952
trying to get attachedDevices method 2...
HTTP request Failed. Status Code: 500
{lastResponse:500}
Number of attached devices: undefined
First attached device:
null
t = 31.244
trying to check newFirmware...
HTTP request Failed. Status Code: 500
{lastResponse:500}
check newFirmware method: 1
{}
t = 31.823
trying to logout...
HTTP request Failed. Status Code: 500
{lastResponse:500}
{host:192.168.1.1,port:80,tls:false,username:admin,password:*****,timeout:18000,sessionId:A7D88AE69687E58D9A00,cookie:false,loggedIn:true,configStarted:true,soapVersion:1,loginMethod:1,getAttachedDevicesMethod:2,checkNewFirmwareMethod:1,guestWifiMethod:{get50_1:1},lastResponse:...,queue:{queue:{},overheat:1594034689373,pending:true,params:{default:{rule:common,key:common},rules:{common:{rate:3,limit:1,priority:1}},overall:{rate:10,limit:1},retryTime:2,ignoreOverallOverheat:true},heatPart:100}}
t = 32.179
test finished with 19 errors


Domenico Di Bonaventura

Il Lun 6 Lug 2020, 14:18 gruijter <notifications@github.com> ha scritto:

**Comment by gruijter** [comment]
Wow, Netgear made a mess of their response here:

```
{NewManufacturerName:NETGEAR,
Inc.,NewManufacturerOUI:00E04C,NewModelName:D1500,NewDescription:Realtek
ADSL
Router,NewProductClass:00000000-00000000,NewSerialNumber:A42B8C723B60,NewSoftwareVersion:V1.0.0.15_1.0.1PE,NewModemFirmwareVersion:4926de702,NewSpecVersion:TR-064
v1.0,NewUpTime:102282}
```

I have to make an exception to handle your router type and remove all the `New` from the response:
NewModelName
NewSerialNumber
NewSoftwareVersion
etc.

**Comment by dokmadeinitaly** [comment]
Must i do something?

Domenico Di Bonaventura

Il Lun 6 Lug 2020, 15:17 gruijter <notifications@github.com> ha scritto:

**Comment by gruijter** [comment]
Only show patience until I find some time to fix this for you :)

**Comment by dokmadeinitaly** [comment]
No problem! Thanks so much!!!

Domenico Di Bonaventura

Il Lun 6 Lug 2020, 15:21 gruijter <notifications@github.com> ha scritto:

**Comment by gruijter** [comment]
Or in the meantime try to upgrade to the latest firmware and run the test again. 

https://kb.netgear.com/000060209/D1500-Firmware-Version-1-0-0-28

**Comment by dokmadeinitaly** [comment]
Already Done ;)

Domenico Di Bonaventura
Mobile 3312782815

Il Lun 6 Lug 2020, 15:30 gruijter <notifications@github.com> ha scritto:

**Comment by dokmadeinitaly** [comment]
No new firmware

Domenico Di Bonaventura
Mobile 3312782815

Il Lun 6 Lug 2020, 15:30 gruijter <notifications@github.com> ha scritto:

**Comment by gruijter** [comment]
Did you try manual upgrade? Because your firmware now is NewSoftwareVersion:**V1.0.0.15**_1.0.1PE, while on the website it says the present firmware is **1.0.0.28**

**Comment by dokmadeinitaly** [comment]
I'v tried. Maybe italian no update?

Domenico Di Bonaventura
Mobile 3312782815

Il Lun 6 Lug 2020, 15:43 gruijter <notifications@github.com> ha scritto:

**Comment by dokmadeinitaly** [comment]
Ho!
No news?

Domenico Di Bonaventura

Il Lun 6 Lug 2020, 20:29 Domenico Di Bonaventura <dokmadeinitaly@gmail.com>
ha scritto:

**Comment by gruijter** [comment]
Pairing bug fixed in version 3.2.1. But after taking a closer look at your test response, it doesn't bring anything to using the D1500 with Homey. Judging from the test response the D1500 cannot work with the SOAP protocol as used by the Nighthawk app from Netgear: https://www.netgear.com/home/apps-services/nighthawk-app/

Can you manage your router with an app? If so, what app works with your router?

When you test it again with homey, make sure to give your router a cold restart first (power off and on)

Homey app version with fixed pairing:
https://homey.app/a/com.gruijter.netgear/test/

**Comment by dokmadeinitaly** [comment]
Thanks a lot! Work Great! 👍🏻👍🏻👍🏻

Domenico Di Bonaventura

Il Gio 16 Lug 2020, 15:38 gruijter <notifications@github.com> ha scritto:

**Comment by gruijter** [comment]
Can you do another compatibility test and post it here?

**Comment by dokmadeinitaly** [comment]
========== STARTING TEST ==========
Node version: v12.16.1
Netgear package version: 4.2.0
OS: linux 4.14.15-g3c513a6eca
Info: Homey fw:4.2.0 app: 3.2.1
t = 0
trying to auto discover Netgear routers...
[{Firmware:V1.0.0.15_1.0.1PE,RegionTag:D1500,Region:ww,Model:D1500,InternetConnectionStatus:Up,ParentalControlSupported:0,SOAPVersion:1.11,ReadyShareSupportedLevel:0,host:192.168.1.1,port:80}]
t = 11.353
trying to login using method 1...
method 1 ok.
trying to login using method 2...
method 2 failed.
trying to login using auto method...
reported login method: 1
t = 12.114
trying to getInfo...
{ManufacturerName:NETGEAR,
Inc.,ManufacturerOUI:00E04C,ModelName:D1500,Description:Realtek ADSL
Router,ProductClass:00000000-00000000,SerialNumber:**********,SoftwareVersion:V1.0.0.15_1.0.1PE,ModemFirmwareVersion:4926de702,SpecVersion:TR-064
v1.0,UpTime:13472}
t = 12.466
trying to getSystemInfo...
HTTP request Failed. Status Code: 500
{lastResponse:500}
{}
t = 12.745
trying to get supportFeatures...
HTTP request Failed. Status Code: 500
{lastResponse:500}
{}
t = 13.126
trying to get the LAN configuration...
HTTP request Failed. Status Code: 500
{lastResponse:500}
{}
t = 13.458
trying to get the WAN configuration...
HTTP request Failed. Status Code: 500
{lastResponse:500}
{}
t = 13.736
trying to get the Traffic Meter Enabled Status...
HTTP request Failed. Status Code: 500
{lastResponse:500}
Traffic Meter Enabled: [object Object]
t = 14.126
trying to get trafficMeter...
HTTP request Failed. Status Code: 500
{lastResponse:500}
{}
t = 14.48
trying to get the Traffic Meter Options...
HTTP request Failed. Status Code: 500
{lastResponse:500}
{}
t = 14.775
trying to get System Uptime (hh:mm:ss)...
HTTP request Failed. Status Code: 500
{lastResponse:500}
{}
t = 15.083
trying to get the Device configuration...
HTTP request Failed. Status Code: 500
{lastResponse:500}
{}
t = 15.456
trying to get Parental Control Status...
HTTP request Failed. Status Code: 500
{lastResponse:500}
Parental Control Enabled: [object Object]
t = 16.361
trying to get Qos Status...
HTTP request Failed. Status Code: 500
{lastResponse:500}
Qos Enabled: [object Object]
t = 16.748
trying to get Qos Bandwidth options...
HTTP request Failed. Status Code: 500
{lastResponse:500}
{}
t = 17.081
trying to get available and selected WiFi channels...
2.4G-1 channels are not available
selected channel 2.4G-1: 8
5.0G-1 channels are not available
5.0G-1 channel is not available
5.0G-2 channels are not available
5.0G-2 channel is not available
t = 19.141
trying to get Smart Connect Status...
HTTP request Failed. Status Code: 500
{lastResponse:500}
Smart Connect Enabled: [object Object]
t = 19.777
trying to get router logs...
HTTP request Failed. Status Code: 500
{lastResponse:500}
last log: undefined
t = 20.144
trying to get Guest Wifi Status...
2.4G-1 Guest wifi enabled: false
5.0G-1 Guest wifi is not available, method: 1
5.0G-2 Guest wifi is not available
t = 21.464
trying to get Device Access Control Status...
HTTP request Failed. Status Code: 500
{lastResponse:500}
Block Device Enabled: [object Object]
t = 21.819
trying to get attachedDevices method 1...
HTTP request Failed. Status Code: 500
{lastResponse:500}
Number of attached devices: undefined
First attached device:
null
t = 22.165
trying to get attachedDevices method 2...
HTTP request Failed. Status Code: 500
{lastResponse:500}
Number of attached devices: undefined
First attached device:
null
t = 22.473
trying to check newFirmware...
HTTP request Failed. Status Code: 500
{lastResponse:500}
check newFirmware method: 1
{}
t = 23.151
trying to logout...
HTTP request Failed. Status Code: 500
{lastResponse:500}
{host:192.168.1.1,port:80,tls:false,username:admin,password:*****,timeout:18000,sessionId:A7D88AE69687E58D9A00,cookie:false,loggedIn:true,configStarted:true,soapVersion:1,loginMethod:1,getAttachedDevicesMethod:2,checkNewFirmwareMethod:1,guestWifiMethod:{get50_1:1},lastResponse:...,queue:{queue:{},overheat:1594907472877,pending:true,params:{default:{rule:common,key:common},rules:{common:{rate:3,limit:1,priority:1}},overall:{rate:10,limit:1},retryTime:2,ignoreOverallOverheat:true},heatPart:100}}
t = 23.483
test finished with 19 errors


Domenico Di Bonaventura
Mobile 3312782815

Il Gio 16 Lug 2020, 23:38 gruijter <notifications@github.com> ha scritto:

**Comment by gruijter** [comment]
Thats what I figured. All commands lead to error 500. So you will not be able to do anything usefull with it. I still suspect you should manually be able to upgrade the firmware. Did you try Netgear support?

**Comment by dokmadeinitaly** [comment]
I'll try.
At the moment i use for reboot router (i'v got it in an other house). It's
not so match, but it work, and i only need this.

Thanks.

Domenico Di Bonaventura

Il Gio 16 Lug 2020, 23:48 gruijter <notifications@github.com> ha scritto:
