### ISSUE TITLE
Kan aangesloten apparaten niet installeren 

### ISSUE THREAD

**Issue by MarcelR66** [gruijter/com.gruijter.netgear#48]
Hoi ik heb sinds vandaag een orbi systeem en de test laten draaien. 3 errors gevonden. 
Ik kan de aangesloten apparaten niet installeren 

Ik hoop dat je er iets aan hebt

groet. Marcèl Rijskamp
Testresultaten :  
========== STARTING TEST ==========
Node version: v12.16.1
Netgear package version: 4.2.0
OS: linux 4.14.15-g3c513a6eca
Info: Homey fw:5.0.0-rc.18 app: 3.2.1
t = 0
trying to auto discover Netgear routers...
[{Firmware:V2.5.1.16WW,RegionTag:RBR50_WW,Region:ww,Model:RBR50,InternetConnectionStatus:Up,ParentalControlSupported:1,OpenDNSEnabled:0,CircleEnabled:0,DeviceMode:0,SOAPVersion:3.63,ReadyShareSupportedLevel:4,XCloudSupported:1,isBlankState:0,LoginMethod:2.0,host:192.168.0.1,port:80},{Firmware:V2.5.1.16WW,RegionTag:RBS50_WW,Region:ww,Model:RBS50,InternetConnectionStatus:Down,ParentalControlSupported:1,OpenDNSEnabled:0,CircleEnabled:0,DeviceMode:3,SOAPVersion:3.63,ReadyShareSupportedLevel:4,XCloudSupported:1,isBlankState:1,LoginMethod:2.0,host:192.168.0.101,port:80}]
t = 131.892
trying to login using method 1...
method 1 ok.
trying to login using method 2...
method 2 ok.
trying to login using auto method...
reported login method: 2
t = 133.341
trying to getInfo...
{Description:Netgear Smart Wizard 3.0, specification 1.6 version,SignalStrength:-4,SmartAgentversion:3.0,FirewallVersion:net-wall 2.0,OthersoftwareVersion:N/A,Hardwareversion:N/A,Otherhardwareversion:N/A,FirstUseDate:Sunday, 30 Sep 2007 01:10:03,DeviceMode:0,ModelName:RBR50,SerialNumber:**********,Firmwareversion:V2.5.1.16,DeviceName:RBR50,DeviceNameUserSet:false,FirmwareDLmethod:HTTPS,FirmwareLastUpdate:2020_7.26_16:14:46,FirmwareLastChecked:2020_7.27_18:52:24,DeviceModeCapability:0;1}
t = 135.786
trying to getSystemInfo...
{NewCPUUtilization:28,NewPhysicalMemory:32,NewMemoryUtilization:48,NewPhysicalFlash:128,NewAvailableFlash:9.87}
t = 138.205
trying to get supportFeatures...
{OpenDNSParentalControl:1.0,CircleParentalControl:1.0,AccessControl:3.0,SpeedTest:2.0,GuestNetworkSchedule:1.0,TCAcceptance:1.0,SmartConnect:1.0,LightingLED:1.0,SatelliteInfo:2.0,NameNTGRDevice:1.0,AttachedDevice:2.0,MaxMonthlyTrafficLimitation:4293918720,SupportXMLEncoded:1.0,TimeZone:3.1,AvsSupport:1.0,ControlledFwRollout:1.0,BitDefenderSecurity:1.0,DeviceTypeIcon:2.1}
t = 138.368
trying to get the LAN configuration...
{NewLANSubnet:255.255.255.0,NewWANLAN_Subnet_Match:1,NewLANMACAddress:3894ED3547F4,NewLANIP:192.168.0.1,NewDHCPEnabled:true}
t = 138.717
trying to get the WAN configuration...
{NewEnable:1,NewConnectionType:DHCP,NewExternalIPAddress:157.97.52.46,NewSubnetMask:255.255.255.0,NewAddressingType:DHCP,NewDefaultGateway:157.97.52.1,NewMACAddress:3894ED3547F5,NewMACAddressOverride:0,NewMaxMTUSize:1500,NewDNSEnabled:1,NewDNSServers:213.109.112.112 157.97.63.63}
t = 139.028
trying to get the Traffic Meter Enabled Status...
Traffic Meter Enabled: true
t = 139.38
trying to get trafficMeter...
{newTodayUpload:3788,newTodayDownload:6865,newMonthUpload:4779,newMonthDownload:9752}
t = 139.691
trying to get the Traffic Meter Options...
{newControlOption:No Limit,newNewMonthlyLimit:0,restartHour:0,restartMinute:0,restartDay:1}
t = 140.024
trying to get System Uptime (hh:mm:ss)...
24:37:10
t = 140.378
trying to get the Device configuration...
{TimeZoneOffset:60,TimeZoneState:1,BlankState:0,NewBlockSiteEnable:0,NewBlockSiteName:0,NewTimeZone:+1,NewDaylightSaving:1}
t = 140.733
trying to get Parental Control Status...
Parental Control Enabled: false
t = 142.789
trying to get Qos Status...
404 Not Found. The requested function/page is not available
Qos Enabled: [object Object]
t = 142.964
trying to get Qos Bandwidth options...
404 Not Found. The requested function/page is not available
{}
t = 143.302
trying to get available and selected WiFi channels...
Available channels 2.4G-1: Auto,1,2,3,4,5,6,7,8,9,10,11,12,13
selected channel 2.4G-1: Auto
Available channels 5.0G-1: 36,40,44,48
selected channel 5.0G-1: 40
5.0G-2 channels are not available
5.0G-2 channel is not available
t = 148.48
trying to get Smart Connect Status...
404 Not Found. The requested function/page is not available
Smart Connect Enabled: [object Object]
t = 149.216
trying to get router logs...
last log: [DoS Attack: SYN/ACK Scan] from source: 47.108.135.220, port 21, Monday, July 27, 2020 18:28:20
t = 149.596
trying to get Guest Wifi Status...
2.4G-1 Guest wifi enabled: true
5.0G-1 Guest wifi enabled: true, method: 1
5.0G-2 Guest wifi is not available
t = 150.856
trying to get Device Access Control Status...
Block Device Enabled: true
t = 151.18
trying to get attachedDevices method 1...
Number of attached devices: 20
First attached device:
{IP:192.168.0.111,Name:plugwise,MAC:C4:93:00:07:D0:A6,ConnectionType:wired,Linkspeed:null,SignalStrength:100,AllowOrBlock:Allow}
t = 162.41
trying to get attachedDevices method 2...
Number of attached devices: 20
First attached device:
{SignalStrength:100,Schedule:false,Upload:0,Download:0,QosPriority:4,Grouping:0,SchedulePeriod:0,AllowOrBlock:Allow,IP:192.168.0.111,Name:plugwise,NameUserSet:true,MAC:C4:93:00:07:D0:A6,ConnectionType:wired,DeviceType:24,DeviceTypeUserSet:true,DeviceModel:Smile P1,ConnAPMAC:38:94:ED:35:47:F4,DeviceModelUserSet:true,DeviceTypeV2:11,DeviceTypeNameV2:IoT (Generic)}
t = 165.037
trying to check newFirmware...
check newFirmware method: 2
{currentVersion:V2.5.1.16,newVersion:,releaseNote:}
t = 166.391
trying to logout...
{host:192.168.0.1,port:80,tls:false,username:admin,password:*****,timeout:18000,sessionId:A7D88AE69687E58D9A00,cookie:true,loggedIn:false,configStarted:true,soapVersion:3,loginMethod:2,getAttachedDevicesMethod:2,checkNewFirmwareMethod:2,guestWifiMethod:{get50_1:1},lastResponse:...,queue:{queue:{},overheat:1595846676110,pending:true,params:{default:{rule:common,key:common},rules:{common:{rate:3,limit:1,priority:1}},overall:{rate:10,limit:1},retryTime:2,ignoreOverallOverheat:true},heatPart:100}}
t = 166.616
test finished with 3 errors

**Comment by gruijter** [comment]
Looks like same issue as #47. Has to do with beta Homey fw 5+

**Comment by pjmpessers** [comment]
Ik heb hier ook een melding van gemaakt. Wat voor mij werkte is dat je even een rollback doet naar de vorige firmware (4.2.0) en dan het orbi-systeem er aan koppelt. Dan kan je terug naar fw 5.0 en bij mij bleef het apparaat werken. Of beter blijf even op fw 4.2.0. Bij mij werkte een aantal apps niet meer, zoals smart presence, netscan, led-editor en xiaomi zigbee op fw 5.0.0

**Comment by gruijter** [comment]
fixed in 3.2.2.

https://homey.app/a/com.gruijter.netgear/test/

**Comment by pjmpessers** [comment]
I want to buy you a beer, but i don’t have and want to install Paypall.

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: gruijter<mailto:notifications@github.com>
Verzonden: dinsdag 11 augustus 2020 14:06
Aan: gruijter/com.gruijter.netgear<mailto:com.gruijter.netgear@noreply.github.com>
CC: Pieter<mailto:pieterpessers@hotmail.com>; Comment<mailto:comment@noreply.github.com>
Onderwerp: Re: [gruijter/com.gruijter.netgear] Kan aangesloten apparaten niet installeren (#48)


Closed #48<https://github.com/gruijter/com.gruijter.netgear/issues/48>.

**Comment by gruijter** [comment]
Whahaha, you dont get away that easy pal!

https://www.paypal-community.com/t5/Payments/Sending-money-without-registering-for-Paypal/m-p/464923#M4807

gruijter@hotmail.com

**Comment by pjmpessers** [comment]
Sorry, but i can't find frontpage on paypall or sent online. It just keeps asking for a account. Do you have a iban number?


-------- Oorspronkelijk bericht --------
Van: gruijter <notifications@github.com>
Datum: 11-08-2020 18:26 (GMT+01:00)
Aan: "gruijter/com.gruijter.netgear" <com.gruijter.netgear@noreply.github.com>
Cc: Pieter <pieterpessers@hotmail.com>, Comment <comment@noreply.github.com>
Onderwerp: Re: [gruijter/com.gruijter.netgear] Kan aangesloten apparaten niet installeren  (#48)


Whahaha, you dont get away that easy pal!

https://www.paypal-community.com/t5/Payments/Sending-money-without-registering-for-Paypal/m-p/464923#M4807

**Comment by gruijter** [comment]
Darn, paypal now indeed forces you to create an account.

Well, there is no need to donate off course. But a cool drink does motivate me 😜

https://www.ing.nl/particulier/betaalverzoek/index.html?trxid=z1TQfLeC6dRyy9ePi3yIeIZINn5aRz7B

**Comment by pjmpessers** [comment]
Happy with the result. So a small appreciation for the good job is needed. 😉

Enjoy.


-------- Oorspronkelijk bericht --------
Van: gruijter <notifications@github.com>
Datum: 11-08-2020 19:19 (GMT+01:00)
Aan: "gruijter/com.gruijter.netgear" <com.gruijter.netgear@noreply.github.com>
Cc: Pieter <pieterpessers@hotmail.com>, Comment <comment@noreply.github.com>
Onderwerp: Re: [gruijter/com.gruijter.netgear] Kan aangesloten apparaten niet installeren  (#48)


Darn, paypal now indeed forces you to create an account.

Well, there is no need to donate off course. But a cool drink does motivate me 😜

https://www.ing.nl/particulier/betaalverzoek/index.html?trxid=z1TQfLeC6dRyy9ePi3yIeIZINn5aRz7B

**Comment by gruijter** [comment]
Enjoying now. Many thx!

**Comment by pjmpessers** [comment]
👍


-------- Oorspronkelijk bericht --------
Van: gruijter <notifications@github.com>
Datum: 11-08-2020 20:28 (GMT+01:00)
Aan: "gruijter/com.gruijter.netgear" <com.gruijter.netgear@noreply.github.com>
Cc: Pieter <pieterpessers@hotmail.com>, Comment <comment@noreply.github.com>
Onderwerp: Re: [gruijter/com.gruijter.netgear] Kan aangesloten apparaten niet installeren  (#48)


Enjoying now. Many thx!
