### ISSUE TITLE
[Feature request/improvement] Add device recognition by name and/or IP to "condition"-card

### ISSUE THREAD

**Issue by cbho** [gruijter/com.gruijter.netgear#5]
Just added two of Netgear's Nighthawk mesh-extenders (a [Nighthawk X4S](https://www.netgear.com/support/product/EX7500) and a [Nighthawk X6S](https://www.netgear.com/home/products/networking/wifi-range-extenders/EX8000.aspx)) to my network (a [Nighthawk X6 R8000](https://www.netgear.com/home/products/networking/wifi-routers/R8000.aspx)).

Now the problem is, that some devices are not recognised as online via the Homey app - even if they appear online in the Netgear control panel (www.routerlogin.com).
The trouble is, that if a device connects via one of the extenders, the system makes a new MAC-adress for the device instead of using the original (described under "I have enabled a wireless MAC filter" almost in the bottom at [NETGEAR WiFi Range Extender FAQ](https://kb.netgear.com/23568/NETGEAR-WiFi-Range-Extender-Frequently-Asked-Questions)).

Consequently, the mac adress on my laptop can now be both F4:8C:50:ED:1F:CF (connected to the router), 02:0F:B5:ED:1F:CF (connected to the X6S), and 92:3B:AD:ED:1F:CF (connected to the X4S).

Now, that is highly annoying, as MAC-adresses are used widely to identify devices (not only by the Homey Netgear app) - e.g. this somehow breaks cloud communication with all my Miele devices, if they are connected using the mesh, but that's another story) - and I've raised a question at Netgear on the subject.

No to the point:
There is a flow card for "when" named "A device came online" with three tags: ip, name and mac.
However, the flow card for "and" named "Device is online" only allows for identification of the device by mac-adress.
1) Would it be possible to add flow cards for the "and" column that recognises online/offline status of devices based on ip and/or name?
and/or
2) Is it possible to add wildcard use in the mac-adress you enter in the card(s) (might be useful for ip-adress or name as well)?
(as the last six numbers in the mac-adress are left unchanged, that could be a workaround that would most likely cover almost al cases - I guess the probability of someone having several devices that share the last six digits purely by coincidence is rather low)...

(If you need access to look into the settings or do some diagnostics, e.g. via Team Viewer, pm me on Slack to arrange :-) ).

**Comment by gruijter** [comment]
Let me think about that. Something should be possible. Just need to make sure it works in a way that more people can benefit in a use case. Not just your (pretty weird :)) example.

**Comment by cbho** [comment]
Excel in "pretty weird examples" - and yes, of course.

Think wildcards could be usefull in general, especially on ip-adresses, as it could make it possible to make e.g. "some devices are online in the interval of x.x.x.02#" (or, perhaps cards with "IP >" and "IP <" or a range is better). 
Then, if you use a systematic approach on ip-adress reservation (like computers on x.x.x.twenties, phones x.x.x.thirties, Sonos x.x.x.forties, and so on, think you get my point), you could include conditions in your flows that check if all devices of a certain kind (within a certain range of IP-adresses) where online or not before continuing...

**Comment by gruijter** [comment]
I'm thinking of doing  IP range, where the range can only be set as single number between 1 - 254 (I'm assuming always a class C network) . E.g. from 50 to 65. Would that work for you?

**Comment by gruijter** [comment]
![2018-10-18](https://user-images.githubusercontent.com/19174120/47174455-e46baf00-d310-11e8-98d3-dd8bf9b71894.png)

done :)

**Comment by gruijter** [comment]
v2.0.8 go get it here, and let me know if it works for you. It also has a new xml parser, so I really would like to know if that is causing any problems or not :)

https://github.com/gruijter/com.gruijter.netgear

**Comment by gruijter** [comment]
Confirmed working in 2.0.8

**Comment by cbho** [comment]
Sorry for being late with my feedback - but yes, new feature is working - cool!
Thank you very much...

Still, would be immensely cool if the "and" column also included a card with "Device is/isn't online (name)" and, if in any way possible that wildcards could be used in the MAC-adress card :-)
