### ISSUE TITLE
Not able to add new connected device as new device

### ISSUE THREAD

**Issue by mwolfs** [gruijter/com.gruijter.netgear#50]
I'm unable to add new connected device. Devices (phones) that are already added as a device seems to work fine. 
Below the result of the test.

========== STARTING TEST ==========
Node version: v12.16.1
Netgear package version: 4.2.0
OS: linux 4.14.15-g3c513a6eca
Info: Homey fw:4.2.0 app: 3.2.2
t = 0
trying to auto discover Netgear routers...
[{Firmware:V2.5.1.16WW,RegionTag:RBR50_WW,Region:ww,Model:RBR50,InternetConnectionStatus:Up,ParentalControlSupported:1,OpenDNSEnabled:0,CircleEnabled:0,DeviceMode:0,SOAPVersion:3.63,ReadyShareSupportedLevel:4,XCloudSupported:1,isBlankState:0,LoginMethod:2.0,host:192.168.1.1,port:80},{Firmware:V2.5.1.16WW,RegionTag:RBS50_WW,Region:ww,Model:RBS50,InternetConnectionStatus:Down,ParentalControlSupported:1,OpenDNSEnabled:0,CircleEnabled:0,DeviceMode:3,SOAPVersion:3.63,ReadyShareSupportedLevel:4,XCloudSupported:1,isBlankState:1,LoginMethod:2.0,host:192.168.1.2,port:80},{Firmware:V2.5.1.16WW,RegionTag:RBS50_WW,Region:ww,Model:RBS50,InternetConnectionStatus:Down,ParentalControlSupported:1,OpenDNSEnabled:0,CircleEnabled:0,DeviceMode:3,SOAPVersion:3.63,ReadyShareSupportedLevel:4,XCloudSupported:1,isBlankState:1,LoginMethod:2.0,host:192.168.1.17,port:80}]
t = 133.916
trying to login using method 1...
method 1 ok.
trying to login using method 2...
method 2 ok.
trying to login using auto method...
reported login method: 2
t = 134.73
trying to getInfo...
{Description:Netgear Smart Wizard 3.0, specification 1.6 version,SignalStrength:-4,SmartAgentversion:3.0,FirewallVersion:net-wall 2.0,OthersoftwareVersion:N/A,Hardwareversion:N/A,Otherhardwareversion:N/A,FirstUseDate:Sunday, 30 Sep 2007 01:10:03,DeviceMode:0,ModelName:RBR50,SerialNumber:**********,Firmwareversion:V2.5.1.16,DeviceName:RBR50,DeviceNameUserSet:false,FirmwareLastChecked:2020_8.18_0:46:8,DeviceModeCapability:0;1}
t = 137.166
trying to getSystemInfo...
{NewCPUUtilization:15,NewPhysicalMemory:32,NewMemoryUtilization:55,NewPhysicalFlash:128,NewAvailableFlash:8.99}
t = 139.439
trying to get supportFeatures...
{OpenDNSParentalControl:1.0,CircleParentalControl:1.0,AccessControl:3.0,SpeedTest:2.0,GuestNetworkSchedule:1.0,TCAcceptance:1.0,SmartConnect:1.0,LightingLED:1.0,SatelliteInfo:2.0,NameNTGRDevice:1.0,AttachedDevice:2.0,MaxMonthlyTrafficLimitation:4293918720,SupportXMLEncoded:1.0,TimeZone:3.1,AvsSupport:1.0,ControlledFwRollout:1.0,BitDefenderSecurity:1.0,DeviceTypeIcon:2.1}
t = 139.586
trying to get the LAN configuration...
{NewLANSubnet:255.255.255.0,NewWANLAN_Subnet_Match:0,NewLANMACAddress:BCA511BF79DC,NewLANIP:192.168.1.1,NewDHCPEnabled:true}
t = 139.924
trying to get the WAN configuration...
{NewEnable:1,NewConnectionType:DHCP,NewExternalIPAddress:89.220.141.103,NewSubnetMask:255.255.254.0,NewAddressingType:DHCP,NewDefaultGateway:89.220.140.1,NewMACAddress:BCA511BF79DD,NewMACAddressOverride:0,NewMaxMTUSize:1500,NewDNSEnabled:1,NewDNSServers:84.116.46.22 84.116.46.23}
t = 140.273
trying to get the Traffic Meter Enabled Status...
Traffic Meter Enabled: false
t = 140.585
trying to get trafficMeter...
{newTodayUpload:0,newTodayDownload:0,newMonthUpload:0,newMonthDownload:0}
t = 140.904
trying to get the Traffic Meter Options...
{newControlOption:No Limit,newNewMonthlyLimit:0,restartHour:0,restartMinute:0,restartDay:1}
t = 141.268
trying to get System Uptime (hh:mm:ss)...
3:50:06
t = 141.575
trying to get the Device configuration...
{TimeZoneOffset:60,TimeZoneState:1,BlankState:0,NewBlockSiteEnable:0,NewBlockSiteName:0,NewTimeZone:+1,NewDaylightSaving:1}
t = 141.914
trying to get Parental Control Status...
Parental Control Enabled: false
t = 143.678
trying to get Qos Status...
404 Not Found. The requested function/page is not available
Qos Enabled: [object Object]
t = 143.907
trying to get Qos Bandwidth options...
404 Not Found. The requested function/page is not available
{}
t = 144.193
trying to get available and selected WiFi channels...
Available channels 2.4G-1: Auto,1,2,3,4,5,6,7,8,9,10,11,12,13
selected channel 2.4G-1: Auto
Available channels 5.0G-1: 36,40,44,48
selected channel 5.0G-1: 36
5.0G-2 channels are not available
5.0G-2 channel is not available
t = 146.199
trying to get Smart Connect Status...
404 Not Found. The requested function/page is not available
Smart Connect Enabled: [object Object]
t = 146.907
trying to get router logs...
last log: [DoS Attack: RST Scan] from source: 3.11.183.67, port 443, Tuesday, August 18, 2020 00:32:52
t = 147.188
trying to get Guest Wifi Status...
2.4G-1 Guest wifi enabled: true
5.0G-1 Guest wifi enabled: true, method: 1
5.0G-2 Guest wifi is not available
t = 148.527
trying to get Device Access Control Status...
Block Device Enabled: true
t = 148.881
trying to get attachedDevices method 1...
Number of attached devices: 26
First attached device:
{IP:192.168.1.33,Name:Philips-Philips hue bridge,MAC:00:17:88:4A:55:K5,ConnectionType:wired,Linkspeed:null,SignalStrength:100,AllowOrBlock:Allow}
t = 158.238
trying to get attachedDevices method 2...
Number of attached devices: 26
First attached device:
{SignalStrength:100,Schedule:false,Upload:0,Download:0,QosPriority:4,Grouping:0,SchedulePeriod:0,AllowOrBlock:Allow,IP:192.168.1.33,Name:Philips-Philips hue bridge,NameUserSet:true,MAC:00:17:88:4A:55:K5,ConnectionType:wired,DeviceType:24,DeviceTypeUserSet:false,DeviceModel:Philips hue bridge,ConnAPMAC:BC:A5:11:BF:79:CC,DeviceModelUserSet:false,DeviceTypeV2:11,DeviceTypeNameV2:IoT (Generic)}
t = 160.791
trying to check newFirmware...
check newFirmware method: 2
{currentVersion:V2.5.1.16,newVersion:,releaseNote:}
t = 162.445
trying to logout...
{host:192.168.1.1,port:80,tls:false,username:admin,password:*****,timeout:18000,sessionId:A7D88AE69687E58D9A00,cookie:true,loggedIn:false,configStarted:true,soapVersion:3,loginMethod:2,getAttachedDevicesMethod:2,checkNewFirmwareMethod:2,guestWifiMethod:{get50_1:1},lastResponse:...,queue:{queue:{},overheat:1597691251790,pending:true,params:{default:{rule:common,key:common},rules:{common:{rate:3,limit:1,priority:1}},overall:{rate:10,limit:1},retryTime:2,ignoreOverallOverheat:true},heatPart:100}}
t = 162.741
test finished with 3 errors

**Comment by gruijter** [comment]
can you also post the app log after trying to pair a device?

**Comment by mwolfs** [comment]
Done, this is the code 7c96e6ae-863b-4559-8234-4eb80fdd8f9c

**Comment by gruijter** [comment]
fixed in v3.2.3 https://homey.app/a/com.gruijter.netgear/test/
