### ISSUE TITLE
Support test for Netgear EX6200

### ISSUE THREAD

**Issue by dxfoxd** [gruijter/com.gruijter.netgear#63]
========== STARTING TEST ==========
Node version: v12.16.1
Netgear package version: 4.3.3
OS: linux 4.14.15-g3c513a6eca
Info: Homey fw:7.2.0 app: 3.2.5
t = 0
trying to auto discover Netgear routers...
[{Firmware:V1.0.2.86WW,RegionTag:R7800_WW,Region:ww,Model:R7800,InternetConnectionStatus:Up,ParentalControlSupported:0,SOAPVersion:3.43,ReadyShareSupportedLevel:21,XCloudSupported:1,isBlankState:0,LoginMethod:2.0,SOAP_HTTPs_Port:443,host:192.168.10.1,port:80},{Firmware:V1.0.3.90_1.1.125,RegionTag:EX6200_WW,Region:ww,Model:EX6200,InternetConnectionStatus:Up,ParentalControlSupported:0,SOAPVersion:1.8,ReadyShareSupportedLevel:13,SmartNetworkSupported:0,LanguageVersion:English:1.0.0.46_2.1.30.1;German:1.0.0.46_2.1.30.1;French:1.0.0.46_2.1.30.1;Dutch:1.0.0.46_2.1.30.1;Swedish:1.0.0.46_2.1.30.1;Russian:1.0.0.46_2.1.30.1,host:192.168.10.2},{Firmware:V1.0.3.90_1.1.125,RegionTag:EX6200_WW,Region:ww,Model:EX6200,InternetConnectionStatus:Up,ParentalControlSupported:0,SOAPVersion:1.8,ReadyShareSupportedLevel:13,SmartNetworkSupported:0,LanguageVersion:English:1.0.1.60_2.1.30.1;German:1.0.1.60_2.1.30.1;French:1.0.1.60_2.1.30.1;Dutch:1.0.1.60_2.1.30.1;Swedish:1.0.1.60_2.1.30.1;Russian:1.0.1.60_2.1.30.1,host:192.168.10.3}]
t = 2.312
trying to login using method 1...
method 1 failed.
trying to login using method 2...
method 2 failed.
trying to login using auto method...
{}
{host:192.168.10.2,port:80,tls:false,username:admin,password:*****,timeout:18000,sessionId:A7D88AE69687E58D9A00,loggedIn:false,configStarted:false,soapVersion:3,loginMethod:2,guestWifiMethod:{},lastResponse:<html><head>\n<META name=\description\ content=\EX6200\>\n<META http-equiv=\Content-Type\ content=\text/html; charset=utf-8\>\n<META http-equiv=\Content-Style-Type\ content=\text/css\>\n<META http-equiv=\Pragma\ content=\no-cache\>\n<META HTTP-equiv=\Cache-Control\ content=\no-cache\>\n<META HTTP-EQUIV=\Expires\ CONTENT=\Mon, 06 Jan 1990 00:00:01 GMT\>\n<meta http-equiv=\X-UA-Compatible\ content=\IE=edge,chrome=1\>\n<meta name=\viewport\ content=\width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no\>\n\n<title>NETGEAR EX6200</title>\n<script language=\javascript\ type=\text/javascript\>\n\n/**\n * note: conditional comments has been removed in Internet Explorer 10\n */\nvar ie = (function(){\n    var undef,\n        v = 3,\n        div = document.createElement('div'),\n        all = div.getElementsByTagName('i');\n\n    while (\n        div.innerHTML = '',\n        all[0]\n    );\n\n    return v > 4 ? v : undef;\n\n}());\n\nfunction checkBrowser() {\n    if (ie && ie < 8)\n        return true;\n\n    return false;\n}\n\nfunction loadnext() {\n    var showit=(document.layers)?\show\:\block\;\n    var hideit=(document.layers)?\hide\:\none\;\n    var el = \alltext\;\n    var is_repeater=\1\;\n    var lan_ip = \192.168.10.2\;\n    var wan_ip = \192.168.10.2\;\n    var url = \\;\n    \n    if (document.all)\n        document.all(el).style.display = hideit ;\n    else if (document.getElementById)\n        document.getElementById(el).style.display = hideit ;\n    else if (document.layers)\n        document.layers[el].visibility = hideit ;\n\n    if (checkBrowser())\n    {\n        document.getElementById(\header_str\).innerHTML = \<h4>NETGEAR recommend you to upgrade your Internet Explorer browser to Internet Explorer 8 or higher to use NETGEAR genie for installation.</h4>\;\n        return;\n    }\n    \n    if(is_repeater == \1\)\n    {\n        if (top.location.href.indexOf(lan_ip) >= 0)\n            url = \http://\+lan_ip+\/\;\n        else if (top.location.href.indexOf(wan_ip) >= 0)\n            url = \http://\+wan_ip+\/\;\n        else if (top.location.href.indexOf(\www.mywifiext.com\) >= 0)\n            url = \http://www.mywifiext.com/\;\n        else if (top.location.href.indexOf(\mywifiext.com\) >= 0)\n            url = \http://mywifiext.com/\;\n        else if (top.location.href.indexOf(\www.mywifiext.net\) >= 0)\n            url = \http://www.mywifiext.net/\;\n        else if (top.location.href.indexOf(\mywifiext.net\) >= 0)\n            url = \http://mywifiext.net/\;\n        else\n        {\n            url = \http://www.mywifiext.net/\;\n            top.location.replace(\http://www.mywifiext.net\);\n        }\n    }\n    \n    if(\0\ == \1\)\n    {\n        if (\1\ != \1\) {\n            if ((\1\ != \1\) \n                && (\0\ == \3\))\n            {\n                top.location.replace(url + \start.htm\);\n            }\n            else\n            {\n                top.location.replace(url + \web_login.html\);\n            }\n        } else if (is_repeater == \1\) {\n            if((\1\ == \0\) \n                && (\WW\ == \WW\\n                    || \\ == \WW\))\n                top.location.replace(url + \IA_welcome.htm\);\n            else if (\0\ == \3\)\n            {\n                top.location.replace(url + \IA_review_setting.htm\);\n            }\n            else\n                top.location.replace(url + \IA_index.htm\);\n        } else if (\\ == \1\)\n            top.location.replace(\welcome.htm\);\n        else\n            top.location.replace(\start.htm\);\n    }\n    else if (is_repeater == \1\)\n    {\n        if (\0\ == \3\)\n        {\n            top.location.replace(url + \IA_review_setting.htm\);\n        }\n        else if (\Enable\ == \Disable\)\n            top.location.replace(url + \IA_sche_hijack.htm\);\n        else if(\0\ == \1\)\n            top.location.replace(url + \IA_hijack.htm\);\n        else\n            top.location.replace(url + \start.htm\);\n    }\n    else if (\0\ == \1\)\n        top.location.replace(url + \start.htm\);\n    else if (\0\ == \1\ || \n             \0\ == \3\)\n        top.location.replace(url + \traffic_start_update.htm\);\n    else\n        top.location.replace(\start.htm\); \n}\n</script></head>\n<body bgcolor=\#ffffff\ text=\#666666\ onload=\loadnext()\> \n  <font face=\Arial,Helvetica\>\n    <div id=\header_str\ STYLE=\position:absolute;left:20px;top:50px;\>\n    </div>\n    <div ID=\alltext\ STYLE=\position:absolute;left:50px;top:200px;\>\n    <h4>Checking JavaScript Support</h4>\n    <p>To provide an enhanced user interface, this Router uses JavaScript extensively.\n    <P>If this page is not quickly replaced, your Browser does NOT support JavaScript.\n    <P>Please enable JavaScript in your Browser, or use a different Browser.</p>\n    </div>\n  </font>\n</body>\n</html>\n\n,queue:{queue:{},overheat:1638754377115,pending:true,params:{default:{rule:common,key:common},rules:{common:{rate:3,limit:1,priority:1}},overall:{rate:10,limit:1},retryTime:2,ignoreOverallOverheat:true},heatPart:100}}

**Comment by gruijter** [comment]
From google I gather the EX6200 is an extender. Your router is the R7800 (from what I can tell from the test report). This means there is no need to have Homey connect to the EX6200. All is handled by the R7800, so you need to add that as a device to Homey.

**Comment by dxfoxd** [comment]
Well I did. On the other hand, EX6200 can be used as a router too when flashed with custom firmware. 
I was triggered by the flow card "Attached device - Turn off" (or ON or TOGGLE). This made me assume that the EX6200 could be switched off and on (cold reboot) by the R7800m, but this is not the case. I then tried to add my 2 EX6200 extender as a separate router, because there is a flow card "Reboot Router". I guess I have to buy 2 new z-wave power plugs to achieve this.

**Comment by gruijter** [comment]
Well you could try to run a test on the ex6200 with manual settings. Type in the ip, and try 80, 443, 5000 and 5555 as port. If any of those settings result in a testreport with a succesful login, you might be able to add it to Homey and use the reboot flow card.
