### ISSUE TITLE
Error parsing device-list - invalid mac format

### ISSUE THREAD

**Issue by llentjes** [gruijter/com.gruijter.netgear#69]
Since a month or two I get on a regular base the error "Error parsing device-list - invalid mac format".
What can I do?
I am using homey 7.30 and app version 4.0.2

**Comment by gruijter** [comment]
Power off - on your router

Check if you are running the latest firmware

Try using soap port 443 if you are now using 80

Try setting the 'attached devices method' to old (or new if it was on old)

**Comment by llentjes** [comment]
Changing the SOAP port seems to do the trick. (strange since it worked like this for some years)
thanks for your help.
