### ISSUE TITLE
Netgear Orbi RBRE960

### ISSUE THREAD

**Issue by MichSouth** [gruijter/com.gruijter.netgear#70]
Hi, I have a new Orbi router and i like to connect it to my Homey. I get a error ‘ cannot read properties of null ( reading password). 
can you help please?

regards,
Mich

========== STARTING TEST ==========
Node version: v16.14.2
Netgear package version: 4.4.2
OS: linux 4.14.15-g3c513a6eca
Info: Homey fw:7.4.1-rc.2 app: 4.0.2
t = 0
trying to auto discover Netgear routers...
[{id:\currentsetting\>,Firmware:V6.0.3.85_3.1.15,RegionTag:RBRE960_WW,Region:ww,Model:RBRE960,InternetConnectionStatus:Up,SOAPVersion:3.46,XCloudSupported:1,LoginMethod:2.0,DeviceMode:0,isBlankState:0,SOAP_HTTPs_Port:443,host:10.0.1.1,port:443,tls:true}]
t = 4.259
trying to login using method 1...
method 1 failed.
trying to login using method 2...
method 2 failed.
trying to login using auto method...
{}
{host:10.0.1.1,port:443,tls:true,username:admin,password:*****,timeout:18000,sessionId:A7D88AE69687E58D9A00,loggedIn:false,configStarted:false,soapVersion:3,loginMethod:2,guestWifiMethod:{},lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<soap-env:Envelope\r\n        xmlns:soap-env=\http://schemas.xmlsoap.org/soap/envelope/\\r\n        soap-env:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\\r\n        >\r\n<soap-env:Body>\r\n    <m:SOAPLoginResponse\r\n        xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceConfig:1\>\r\n    </m:SOAPLoginResponse>\r\n    <ResponseCode>401</ResponseCode>\r\n</soap-env:Body>\r\n</soap-env:Envelope>\r\n,queue:{queue:{},overheat:1651606918722,pending:true,params:{default:{rule:common,key:common},rules:{common:{rate:3,limit:1,priority:1}},overall:{rate:10,limit:1},retryTime:2,ignoreOverallOverheat:true},heatPart:100}}

**Comment by gruijter** [comment]
Can you try again with manually setting the SOAP port to 80, 5000 or 5555?

**Comment by gruijter** [comment]
No feedback from you. Closing the issue now.

**Comment by MichSouth** [comment]
Sorry i forgot to reply. It worked using your tip to use another port number. Op 10 sep. 2022 om 11:55 heeft gruijter ***@***.***> het volgende geschreven:﻿
No feedback from you. Closing the issue now.
