### ISSUE TITLE
password error

### ISSUE THREAD

**Issue by Rickyfr1987** [gruijter/com.gruijter.netgear#71]
Device could not connect anymore. I tried to reinstall but get a password (null) error.

========== STARTING TEST ==========

Node version: v16.14.2
Netgear package version: 4.4.2
OS: linux 4.14.15-g3c513a6eca
Info: Homey fw:7.4.1 app: 4.0.2
t = 0
trying to auto discover Netgear routers...
[{id:\currentsetting\>,Firmware:V4.6.5.14_2.0.54,RegionTag:RBR750_WW,Region:ww,Model:RBR750,InternetConnectionStatus:Up,SOAPVersion:3.46,XCloudSupported:1,LoginMethod:2.0,DeviceMode:0,isBlankState:0,SOAP_HTTPs_Port:443,host:10.0.0.1,port:443,tls:true}]
t = 4.298
trying to login using method 1...
method 1 ok.
trying to login using method 2...
method 2 ok.
trying to login using auto method...
reported login method: 2
t = 5.049
trying to getInfo...
{ModelName:RBR750,DeviceName:Meterkast,Description:Netgear Smart Wizard 3.0, specification 0.7 version,SerialNumber:**********,SignalStrength:100,Firmwareversion:V4.6.5.14,SmartAgentversion:3.0,FirewallVersion:ACOS NAT-Netfilter v3.0.0.5 (Linux Cone NAT Hot Patch 06/11/2010),VPNVersion:N/A,OthersoftwareVersion:2.0.54,Hardwareversion:RBR750,Otherhardwareversion:N/A,FirstUseDate:Sunday, 16 Jan 2022 15:10:57,FirmwareLastUpdate:2022_00.16_15:17:49,FirmwareLastChecked:2022_04.12_16:36:13,DeviceMode:0,DeviceModeCapability:0;1,DeviceNameUserSet:true}
t = 5.398
trying to getSystemInfo...
{NewCPUUtilization:100,NewPhysicalMemory:256,NewMemoryUtilization:61,NewPhysicalFlash:128,NewAvailableFlash:2616}
t = 5.986
trying to get supportFeatures...
{DynamicQoS:1.0,OpenDNSParentalControl:1.0,SpeedTest:2.0,AccessControl:3.0,GuestNetworkSchedule:1.0,TCAcceptance:1.0,DeviceTypeIdentification:1.0,SmartConnect:1.0,LightingLED:1.0,SatelliteInfo:2.0,AvsSupport:1.0,AttachedDevice:2.0,NameNTGRDevice:1.0,TimeZone:3.0,MaxMonthlyTrafficLimitation:4095000000,PasswordReset:1.0,CircleParentalControlV2:1.0,WanAggregation:1.0,SupportWPA3:1.0,DeviceTypeIcon:2.1,CDIL:1.0,BitDefenderSecurity:1.0}
t = 6.104
trying to get the LAN configuration...
{NewLANSubnet:255.255.255.0,NewWANLAN_Subnet_Match:1,NewLANMACAddress:6CCDD6DA1557,NewLANIP:10.0.0.1,NewDHCPEnabled:true}
t = 6.456
trying to get the WAN configuration...
{NewEnable:1,NewConnectionType:DHCP,NewExternalIPAddress:192.168.1.176,NewSubnetMask:255.255.255.0,NewAddressingType:DHCP,NewDefaultGateway:192.168.1.1,NewMACAddress:6CCDD6DA1558,NewMACAddressOverride:0,NewMaxMTUSize:1500,NewDNSEnabled:1,NewDNSServers:192.168.1.1 }
t = 6.793
trying to get the Traffic Meter Enabled Status...
Traffic Meter Enabled: true
t = 7.055
trying to get trafficMeter...
{newTodayUpload:518.8,newTodayDownload:17261,newMonthUpload:11100,newMonthDownload:157032}
t = 7.462
trying to get the Traffic Meter Options...
{newControlOption:No Limit,newNewMonthlyLimit:0,restartHour:0,restartMinute:0,restartDay:1}
t = 7.744
trying to get System Uptime (hh:mm:ss)...
 5 days 13:20:07
t = 8.076
trying to get the Device configuration...
{BlankState:0,NewBlockSiteEnable:0,NewBlockSiteName:0,NewTimeZone:+1,NewDaylightSaving:0,TimeZoneOffset:60,TimeZoneState:1}
t = 8.465
trying to get Qos Status...
Qos Enabled: false
t = 8.78
trying to get Qos Bandwidth options...
404 Not Found. The requested function/page is not available
{}
t = 9.073
trying to get available and selected WiFi channels...
Available channels 2.4G-1: Auto,1,2,3,4,5,6,7,8,9,10,11,12,13
selected channel 2.4G-1: Auto
Available channels 5.0G-1: 36,40,44,48
selected channel 5.0G-1: 36
5.0G-2 channels are not available
5.0G-2 channel is not available
t = 11.122
trying to get Smart Connect Status...
404 Not Found. The requested function/page is not available
Smart Connect Enabled: [object Object]
t = 11.749
trying to get router logs...
No log entries found
{lastResponse:<?xml version=\1.0\ encoding=\UTF-8\?>\r\n<soap-env:Envelope\r\n        xmlns:soap-env=\http://schemas.xmlsoap.org/soap/envelope/\\r\n        soap-env:encodingStyle=\http://schemas.xmlsoap.org/soap/encoding/\\r\n        >\r\n<soap-env:Body>\r\n    <m:GetSystemLogsResponse\r\n        xmlns:m=\urn:NETGEAR-ROUTER:service:DeviceInfo:1\>\r\n        <NewLogDetails></NewLogDetails>\r\n    </m:GetSystemLogsResponse>\r\n    <ResponseCode>000</ResponseCode>\r\n</soap-env:Body>\r\n</soap-env:Envelope>\r\n}
last log: undefined
t = 12.12
trying to get Guest Wifi Status...
2.4G-1 Guest wifi enabled: false
5.0G-1 Guest wifi enabled: false, method: 1
5.0G-2 Guest wifi is not available
t = 13.477
trying to get Device Access Control Status...
Block Device Enabled: true
t = 13.771
trying to get attachedDevices method 1...
Number of attached devices: 13
First attached device:
{IP:10.0.0.26,Name:homey-5d0b679104252e03d415eaed,MAC:0C:1C:57:C4:25:28,ConnectionType:wireless,Linkspeed:null,SignalStrength:100,AllowOrBlock:Allow}
t = 15.467
trying to get attachedDevices method 2...
Number of attached devices: 13
First attached device:
{IP:10.0.0.26,Name:homey-5d0b679104252e03d415eaed,NameUserSet:false,MAC:0C:1C:57:C4:25:28,ConnectionType:2.4GHz,SSID:Mupkes,Linkspeed:72,SignalStrength:70,AllowOrBlock:Allow,Schedule:false,DeviceType:24,DeviceTypeUserSet:true,DeviceTypeV2:21,DeviceTypeNameV2:Router,Upload:0,Download:0,QosPriority:4,DeviceModelUserSet:false,Grouping:0,SchedulePeriod:0,ConnAPMAC:6C:CD:D6:DA:15:57}
t = 17.822
trying to check newFirmware...
check newFirmware method: 2
{currentVersion:,newVersion:,releaseNote:}
t = 17.952
trying to logout...
{host:10.0.0.1,port:443,tls:true,username:admin,password:*****,timeout:18000,sessionId:A7D88AE69687E58D9A00,cookie:true,loggedIn:false,configStarted:true,soapVersion:3,loginMethod:2,getAttachedDevicesMethod:2,checkNewFirmwareMethod:2,guestWifiMethod:{get50_1:1},lastResponse:...,queue:{queue:{},overheat:1652369500651,pending:true,params:{default:{rule:common,key:common},rules:{common:{rate:3,limit:1,priority:1}},overall:{rate:10,limit:1},retryTime:2,ignoreOverallOverheat:true},heatPart:100}}
t = 18.241
test finished with 3 errors

**Comment by gruijter** [comment]
Fixed in v4.1.0

Can you please test and let me know if it works
https://homey.app/a/com.gruijter.netgear/test/

**Comment by gruijter** [comment]
Shame you do not give any feedback after my work for you....
