### ISSUE TITLE
args.device.getCapabilityValue(...).catch is not a function

### ISSUE THREAD

**Issue by KevinJoss** [gruijter/com.gruijter.netgear#73]
Hello Robin de Gruijter,

One more time, many thanks for your app! This one automates my life everyday without any problem until several days / or 1-2 weeks, I don't know exactly...
But since that it seems the flow card condition IS ONLINE or its invert doesn't work anymore.
I saw that by trying the new AdvancedFlow (it's also in error with standard flow, I also tested) feature today. (I also use to automatically shutdown my PC with an alarm and another app, but few times it doesn't shutdown correctly, now i know why...)

I join you a picture of the error i saw in the advanced flow test.
I also used the button in the app to send report.
(625160eb-825c-4f28-9606-f0a13c725834)

Hope you will find the problem!

Best regards

![image](https://user-images.githubusercontent.com/37264503/176502111-1d32a8cb-daa0-4580-a67a-f6c3b4905b9d.png)

**Comment by gruijter** [comment]
Yep thats a bug. Thx 4 reporting!

**Comment by gruijter** [comment]
Is fixed in version 4.1.2.

Can you please test and confirm?

Thx!

**Comment by KevinJoss** [comment]
Hi,
Many thanks for your reactivity! 
Yep, i tried and it works. The conditions have been passed without any problem.

Thank you one more time.
Have a nice day !

Best regards
