### ISSUE TITLE
Attached devicelist came back empty

### ISSUE THREAD

**Issue by llentjes** [gruijter/com.gruijter.netgear#74]
Since a few weeks I keep getting an red warning sign and exclamation mark in my RBR50-device.
restarting the app sometimes works for a day or two.
When I click on this device, the error "Attached devicelist came back empty".
Do you have some hints to solve this problem?

**Comment by llentjes** [comment]
I restarted the router and homey and everything seems to work again.
Next time I will try this first. (And want to determine who is causing the problem.)

**Comment by gruijter** [comment]
Firmware of Netgear can be flaky. Make sure you are on the last firmware version. A hard reboot (power off - wait 30s - power on) every now and then is advised.
