### ISSUE TITLE
netgear sxr80

### ISSUE THREAD

**Issue by SirWinter** [gruijter/com.gruijter.netgear#75]
========== STARTING TEST ==========
Node version: v16.14.2
Netgear package version: 4.4.2
OS: linux 4.14.15-g3c513a6eca
Info: Homey fw:8.0.5 app: 4.1.2
t = 0
trying to auto discover Netgear routers...
{}
{host:10.1.1.1,port:5000,tls:true,username:admin,password:*****,timeout:18000,sessionId:A7D88AE69687E58D9A00,loggedIn:false,configStarted:false,guestWifiMethod:{},lastResponse:{},queue:{queue:{},overheat:1662752434352,pending:false,params:{default:{rule:common,key:common},rules:{common:{rate:3,limit:1,priority:1}},overall:{rate:10,limit:1},retryTime:2,ignoreOverallOverheat:true},heatPart:100}}

**Comment by SirWinter** [comment]
i cant get sxr80 to work.

**Comment by SirWinter** [comment]
Orbi Pro SXR80

**Comment by gruijter** [comment]
did you already try setting the ip and port manually?

**Comment by SirWinter** [comment]
Yes, port 5000 and 5555
I have uninstalled and installed the application.

**Comment by SirWinter** [comment]
Error: http request failed
Status code 401

**Comment by gruijter** [comment]
Also try 443 and 80

**Comment by gruijter** [comment]
Oh, and do a hard reboot of your router before trying (power off, wait 30 seconds, power on)

And make sure you are on the latest firmware

**Comment by SirWinter** [comment]
Hi
I use a /20 subnet
I changed the Homey ip to 10.1.1.6/20 (router 10.1.1.1/20)
Before Momey used 10.1.12.1/20

Now I auto connect to the router on port 80 and 443.
But....after connecting the is no status. Error code 401
Is this app only working on a /24 submask?

**Comment by SirWinter** [comment]
[err] 2022-09-11 07:09:27 [netgear] [dev] Error: This is not a valid Netgear router at NetgearRouter.getCurrentSetting (/node_modules/netgear/netgear.js:279:11) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async NetgearRouter.login (/node_modules/netgear/netgear.js:195:28) at async NetgearDevice.login (/drivers/netgear/device.js:39:5) at async NetgearDevice.updateRouterDeviceState (/drivers/netgear/device.js:500:4) at async NetgearDevice.onInit (/drivers/netgear/device.js:581:4) at async NetgearDevice.restartDevice (/drivers/netgear/device.js:644:3) at async NetgearDevice.onSettings (/drivers/netgear/device.js:716:3) at async NetgearDevice._onSettings (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/Device.js:1:3452)

**Comment by gruijter** [comment]
Can you use a native netgear app to see the status of the router and the attached devices? What app?

**Comment by SirWinter** [comment]
Yes that is not a problem from netgear

I uninstalled/reinstalled the netgear homey app.
Reboot the router and then change the ip on homey

Then I got connected, but then I got the error 401 and then I send you the log from netgear homey app

Hope you understand

**Comment by gruijter** [comment]
Fixed in v4.1.3
