### ISSUE TITLE
can't connect

### ISSUE THREAD

**Issue by sanderapp** [gruijter/com.gruijter.netgear#77]
Hi, 
i can't connect to Homey, i try to test en connect ( see below)

do have an idee what goes wrong?

Thanks.

TEST:

{Firmware:V1.0.9.92_1,RegionTag:RAX30_WW,Region:EU,Model:RAX30,InternetConnectionStatus:Up,SOAPVersion:3.84,ReadyShareSupportedLevel:25,XCloudSupported:1,isBlankState:0,LoginMethod:2.0,SOAP_HTTPs_Port:5043,host:192.168.1.1,tls:false}

Node version: v16.14.2
Netgear package version: 4.4.2
OS: linux 4.14.15-g3c513a6eca
Info: Homey fw:8.1.2 app: 4.1.2
t = 0
trying to auto discover Netgear routers...
[{Firmware:V1.0.9.92_1,RegionTag:RAX30_WW,Region:EU,Model:RAX30,InternetConnectionStatus:Up,SOAPVersion:3.84,ReadyShareSupportedLevel:25,XCloudSupported:1,isBlankState:0,LoginMethod:2.0,SOAP_HTTPs_Port:5043,host:192.168.1.1,tls:false}]
t = 5.114
trying to login using method 1...
method 1 failed.
trying to login using method 2...
method 2 failed.
trying to login using auto method...
{}
{host:192.168.1.1,port:80,tls:false,username:admin,password:*****,timeout:18000,sessionId:A7D88AE69687E58D9A00,loggedIn:false,configStarted:false,soapVersion:3,loginMethod:2,guestWifiMethod:{},lastResponse:401,queue:{queue:{},overheat:1675166403466,pending:true,params:{default:{rule:common,key:common},rules:{common:{rate:3,limit:1,priority:1}},overall:{rate:10,limit:1},retryTime:2,ignoreOverallOverheat:true},heatPart:100}}

**Comment by gruijter** [comment]
Try with manually setting the SOAP port to 5043
Https on ip 192.168.1.1

**Comment by sanderapp** [comment]
Hi,

thanks for the repons 🙂!


it tried evrything but it i can't get i worked.
see below




[cid:c65e967b-8100-4428-8757-973c1e804926]

========== STARTING TEST ==========
Node version: v16.14.2
Netgear package version: 4.4.2
OS: linux 4.14.15-g3c513a6eca
Info: Homey fw:8.1.2 app: 4.1.2
t = 0
trying to auto discover Netgear routers...
[{Firmware:V1.0.9.92_1,RegionTag:RAX30_WW,Region:EU,Model:RAX30,InternetConnectionStatus:Up,SOAPVersion:3.84,ReadyShareSupportedLevel:25,XCloudSupported:1,isBlankState:0,LoginMethod:2.0,SOAP_HTTPs_Port:5043,host:192.168.1.1,tls:false}]
t = 4.258
trying to login using method 1...
method 1 failed.
trying to login using method 2...
method 2 failed.
trying to login using auto method...
{}
{host:192.168.1.1,port:5043,tls:false,username:admin,password:*****,timeout:18000,sessionId:A7D88AE69687E58D9A00,loggedIn:false,configStarted:false,soapVersion:3,loginMethod:2,guestWifiMethod:{},lastResponse:{code:ECONNRESET},queue:{queue:{},overheat:1675166403466,pending:true,params:{default:{rule:common,key:common},rules:{common:{rate:3,limit:1,priority:1}},overall:{rate:10,limit:1},retryTime:2,ignoreOverallOverheat:true},heatPart:100}}








________________________________

**Comment by gruijter** [comment]
Fixed in v4.1.3

**Comment by sanderapp** [comment]
Hi ,

i stil can't get it working, can we check it toghter on teamview?

________________________________
